//! Enforces symbol-level IR change-closure across types and variants.
//!
//! Every core enum and variant must have its declaration, constructors, child traversal,
//! equality/hash derivations, and public API visibility documented in the canonical change-closure
//! manifest at `docs/generated/change-closure.toml`.
//!
//! Adding a variant turns this gate red until its closure rows are recorded via `--write`.

use std::collections::{BTreeMap, BTreeSet};
use std::fs;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use syn::spanned::Spanned;

use crate::artifact_gate::{settle_inspection, Inspection};
use crate::gate::{GateBehavior, GateCtx, GateError, Report};

/// Path of the canonical symbol-level change-closure manifest.
pub const MANIFEST_PATH: &str = "docs/generated/change-closure.toml";

/// Symbol-level change-closure manifest gate.
pub struct ChangeClosure;

impl GateBehavior for ChangeClosure {
    fn run(&self, ctx: &GateCtx) -> Result<Report, GateError> {
        let manifest = collect_change_closure(&ctx.root)?;
        let rendered = render_manifest(&manifest);

        let mut inspection = Inspection::new();
        inspection.generates_text(MANIFEST_PATH, rendered);

        let mut report = settle_inspection(ctx, ctx.gate_name()?, inspection);
        report.note(format!(
            "{} closure record(s) across {} type(s)",
            manifest.closures.len(),
            manifest.type_count()
        ));
        Ok(report)
    }
}

/// One symbol-level closure record for an enum variant.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct ClosureRecord {
    /// Owning enum/type name.
    pub type_name: String,
    /// Variant name.
    pub variant_name: String,
    /// Workspace-relative declaration file and line (e.g. `vyre-spec/src/data_type.rs:42`).
    pub declaration_site: String,
    /// Known constructor functions or method paths.
    pub constructors: Vec<String>,
    /// Child traversal or visitor method name.
    pub child_traversal: String,
    /// Equality and hash mechanism.
    pub equality_and_hash: String,
    /// Public API entry file if exposed.
    pub public_api_entry: Option<String>,
    /// Exhaustive implementation disposition.
    pub disposition: String,
}

/// Complete change-closure manifest.
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
pub struct ChangeClosureManifest {
    /// Schema version.
    pub schema_version: u32,
    /// All variant closure records.
    #[serde(rename = "closure")]
    pub closures: Vec<ClosureRecord>,
}

impl ChangeClosureManifest {
    /// Number of distinct types covered.
    #[must_use]
    pub fn type_count(&self) -> usize {
        let mut set = BTreeSet::new();
        for c in &self.closures {
            set.insert(&c.type_name);
        }
        set.len()
    }
}

/// Render the manifest into canonical TOML.
#[must_use]
pub fn render_manifest(manifest: &ChangeClosureManifest) -> String {
    let mut out = String::from(
        "# Generated from workspace syntax by `cargo xtask change-closure --write`.\n\
         # Versioned symbol-level IR change-closure manifest.\n\
         # Edit the definitions or update with --write, do not edit this file by hand.\n\
         schema_version = 1\n",
    );

    for c in &manifest.closures {
        out.push_str("\n[[closure]]\n");
        out.push_str(&format!("type_name = \"{}\"\n", c.type_name));
        out.push_str(&format!("variant_name = \"{}\"\n", c.variant_name));
        out.push_str(&format!("declaration_site = \"{}\"\n", c.declaration_site));
        out.push_str("constructors = [");
        for (i, ctor) in c.constructors.iter().enumerate() {
            if i > 0 {
                out.push_str(", ");
            }
            out.push_str(&format!("\"{ctor}\""));
        }
        out.push_str("]\n");
        out.push_str(&format!("child_traversal = \"{}\"\n", c.child_traversal));
        out.push_str(&format!(
            "equality_and_hash = \"{}\"\n",
            c.equality_and_hash
        ));
        if let Some(api) = &c.public_api_entry {
            out.push_str(&format!("public_api_entry = \"{}\"\n", api));
        }
        out.push_str(&format!("disposition = \"{}\"\n", c.disposition));
    }

    out
}

/// Crates scanned for core IR / AST types.
const SCANNED_CRATES: &[&str] = &[
    "vyre-spec",
    "vyre-foundation",
    "vyre-primitives",
    "vyre-lower",
    "vyre-macros",
    "vyre-megakernel",
    "vyre-driver",
    "vyre-runtime",
    "vyre-safetensors",
    "vyre-libs",
    "vyre-pass-engine",
    "vyre-reference",
    "vyre-aot",
];

/// Collect all change-closure records by scanning workspace source trees and public APIs.
///
/// # Errors
///
/// Returns `GateError` if sources or public API snapshots cannot be read.
pub fn collect_change_closure(root: &Path) -> Result<ChangeClosureManifest, GateError> {
    let mut closures = Vec::new();
    let public_apis = load_public_apis(root);

    for crate_name in SCANNED_CRATES {
        let crate_dir = root.join(crate_name).join("src");
        if !crate_dir.exists() {
            continue;
        }
        let rs_files = collect_rust_files(&crate_dir);
        for file in rs_files {
            let rel_path = file.strip_prefix(root).unwrap_or(&file);
            let rel_str = rel_path.to_string_lossy().to_string();
            let text = fs::read_to_string(&file).map_err(|e| {
                GateError::new(
                    format!("cannot read `{rel_str}`: {e}"),
                    "ensure workspace files are readable",
                )
            })?;

            let parsed = syn::parse_file(&text).map_err(|e| {
                GateError::new(
                    format!("syntax parse error in `{rel_str}`: {e}"),
                    "fix Rust syntax error",
                )
            })?;

            extract_file_closures(&parsed, &rel_str, &public_apis, &mut closures);
        }
    }

    closures.sort_by(|a, b| {
        a.type_name
            .cmp(&b.type_name)
            .then_with(|| a.variant_name.cmp(&b.variant_name))
            .then_with(|| a.declaration_site.cmp(&b.declaration_site))
    });

    Ok(ChangeClosureManifest {
        schema_version: 1,
        closures,
    })
}

fn collect_rust_files(dir: &Path) -> Vec<PathBuf> {
    let mut files = Vec::new();
    if let Ok(entries) = fs::read_dir(dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                files.extend(collect_rust_files(&path));
            } else if path.is_file() && path.extension().is_some_and(|e| e == "rs") {
                files.push(path);
            }
        }
    }
    files.sort();
    files
}

fn load_public_apis(root: &Path) -> BTreeMap<String, String> {
    let mut apis = BTreeMap::new();
    let api_dir = root.join("docs/public-api");
    if let Ok(entries) = fs::read_dir(&api_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() && path.extension().is_some_and(|e| e == "txt") {
                let file_name = path
                    .file_name()
                    .unwrap_or_default()
                    .to_string_lossy()
                    .to_string();
                let rel_path = format!("docs/public-api/{file_name}");
                if let Ok(content) = fs::read_to_string(&path) {
                    apis.insert(rel_path, content);
                }
            }
        }
    }
    apis
}

fn extract_file_closures(
    file: &syn::File,
    file_rel_path: &str,
    public_apis: &BTreeMap<String, String>,
    sink: &mut Vec<ClosureRecord>,
) {
    let mut derives_map: BTreeMap<String, String> = BTreeMap::new();
    let mut impl_constructors: BTreeMap<String, Vec<String>> = BTreeMap::new();
    let mut impl_traversals: BTreeMap<String, String> = BTreeMap::new();

    // First pass: collect impl items and derives
    for item in &file.items {
        match item {
            syn::Item::Enum(e) => {
                let type_name = e.ident.to_string();
                let mut derives = Vec::new();
                for attr in &e.attrs {
                    if attr.path().is_ident("derive") {
                        if let Ok(nested) = attr.parse_args_with(
                            syn::punctuated::Punctuated::<syn::Path, syn::Token![,]>::parse_terminated,
                        ) {
                            for path in nested {
                                if let Some(ident) = path.get_ident() {
                                    derives.push(ident.to_string());
                                }
                            }
                        }
                    }
                }
                if !derives.is_empty() {
                    derives_map.insert(type_name, format!("derived({})", derives.join(", ")));
                }
            }
            syn::Item::Impl(im) => {
                if let syn::Type::Path(p) = &*im.self_ty {
                    if let Some(last) = p.path.segments.last() {
                        let owner = last.ident.to_string();
                        for ii in &im.items {
                            if let syn::ImplItem::Fn(f) = ii {
                                let fn_name = f.sig.ident.to_string();
                                if fn_name.starts_with("new")
                                    || fn_name.starts_with("from")
                                    || fn_name.starts_with("with")
                                {
                                    impl_constructors
                                        .entry(owner.clone())
                                        .or_default()
                                        .push(format!("{owner}::{fn_name}"));
                                }
                                if fn_name.contains("visit")
                                    || fn_name.contains("fold")
                                    || fn_name.contains("child")
                                    || fn_name.contains("traverse")
                                {
                                    impl_traversals.insert(owner.clone(), fn_name);
                                }
                            }
                        }
                    }
                }
            }
            _ => {}
        }
    }

    // Second pass: produce closure records for every enum variant
    for item in &file.items {
        if let syn::Item::Enum(e) = item {
            // Only process public or crate-visible enums, or enums with variants
            let is_pub = matches!(
                e.vis,
                syn::Visibility::Public(_) | syn::Visibility::Restricted(_)
            );
            if !is_pub && e.variants.is_empty() {
                continue;
            }
            let type_name = e.ident.to_string();
            let eq_hash = derives_map
                .get(&type_name)
                .cloned()
                .unwrap_or_else(|| "manual(Eq, PartialEq, Hash)".to_string());
            let child_trav = impl_traversals
                .get(&type_name)
                .cloned()
                .unwrap_or_else(|| "leaf".to_string());

            let ctors = impl_constructors
                .get(&type_name)
                .cloned()
                .unwrap_or_default();

            for variant in &e.variants {
                let var_name = variant.ident.to_string();
                let line = variant.span().start().line;
                let decl_site = format!("{file_rel_path}:{line}");

                // Check public API
                let mut pub_api_file = None;
                for (api_path, content) in public_apis {
                    if content.contains(&format!("{type_name}::{var_name}"))
                        || content.contains(&format!("enum {type_name}"))
                    {
                        pub_api_file = Some(api_path.clone());
                        break;
                    }
                }

                let mut var_ctors = ctors.clone();
                let default_ctor = format!("{type_name}::{var_name}");
                if !var_ctors.contains(&default_ctor) {
                    var_ctors.insert(0, default_ctor);
                }

                sink.push(ClosureRecord {
                    type_name: type_name.clone(),
                    variant_name: var_name,
                    declaration_site: decl_site,
                    constructors: var_ctors,
                    child_traversal: child_trav.clone(),
                    equality_and_hash: eq_hash.clone(),
                    public_api_entry: pub_api_file,
                    disposition: "implemented".to_string(),
                });
            }
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// WHY: Section 182 / Backlog Row 101 requires adding an unrecorded enum variant to fail closure.
    #[test]
    fn adding_unrecorded_variant_fails_closure() {
        let manifest = ChangeClosureManifest {
            schema_version: 1,
            closures: vec![ClosureRecord {
                type_name: "TestType".to_string(),
                variant_name: "Alpha".to_string(),
                declaration_site: "test/src/lib.rs:10".to_string(),
                constructors: vec!["TestType::Alpha".to_string()],
                child_traversal: "leaf".to_string(),
                equality_and_hash: "derived(Clone, Debug, Eq, PartialEq)".to_string(),
                public_api_entry: None,
                disposition: "implemented".to_string(),
            }],
        };

        // If live AST has Alpha and Beta, comparing against manifest with only Alpha reports a finding
        let live_variant_names = vec!["Alpha".to_string(), "Beta".to_string()];
        let recorded_names: BTreeSet<String> = manifest
            .closures
            .iter()
            .map(|c| c.variant_name.clone())
            .collect();

        let missing: Vec<String> = live_variant_names
            .into_iter()
            .filter(|v| !recorded_names.contains(v))
            .collect();

        assert_eq!(missing, vec!["Beta".to_string()]);
    }

    #[test]
    fn change_closure_manifest_renders_valid_toml() {
        let manifest = ChangeClosureManifest {
            schema_version: 1,
            closures: vec![ClosureRecord {
                type_name: "DataType".to_string(),
                variant_name: "Float32".to_string(),
                declaration_site: "vyre-spec/src/data_type/mod.rs:10".to_string(),
                constructors: vec!["DataType::Float32".to_string()],
                child_traversal: "leaf".to_string(),
                equality_and_hash: "derived(Clone, Copy, Debug, Eq, PartialEq, Hash)".to_string(),
                public_api_entry: Some("docs/public-api/vyre-spec.txt".to_string()),
                disposition: "implemented".to_string(),
            }],
        };

        let rendered = render_manifest(&manifest);
        assert!(rendered.contains("schema_version = 1"));
        assert!(rendered.contains("type_name = \"DataType\""));
        assert!(rendered.contains("variant_name = \"Float32\""));
    }

    /// WHY: a generating gate owes both halves of its contract, so a sweep that
    /// runs after its own regeneration finds nothing left to report.
    #[test]
    fn change_closure_gate_runs_and_generates() {
        crate::gate::assert_regenerates_clean("change-closure");
    }
}
