//! One protected-boundary manifest, one CODEOWNERS, no second copy.
//!
//! GitHub reads the first CODEOWNERS it finds at `CODEOWNERS`, then
//! `.github/CODEOWNERS`, then `docs/CODEOWNERS`, and ignores the rest. A
//! repository carrying two therefore has one file that is policy and one that
//! only looks like policy, which is how this tree ended up with a root file
//! naming `spec/`, `vyre-wgpu/` and `core/src/ir/` long after those paths were
//! gone. A pattern that matches nothing protects nothing, and a reader cannot
//! tell the two files apart.
//!
//! So `.github/CODEOWNERS` is generated here from
//! `docs/PROTECTED_BOUNDARIES.toml` and nowhere else. The manifest joins each
//! protected path with the packages it covers, and every workspace member must
//! appear exactly once across the boundaries and the recorded-open roster. A
//! new crate belongs to neither and turns this gate red until someone writes
//! down which it is.
//!
//! Branch protection is the other half. `require_code_owner_reviews` is what
//! makes an owner line mean anything; without it CODEOWNERS is a suggestion.
//! This gate cannot reach the GitHub API, so it judges the script that applies
//! the protection: the payload must require the code-owner review on the branch
//! the manifest names.

use std::collections::BTreeSet;
use std::path::PathBuf;

use serde::Deserialize;

use crate::gate::{Finding, GateCtx, GateError, Report};
use crate::gates::scan::Tree;

/// Where the manifest lives.
const MANIFEST: &str = "docs/PROTECTED_BOUNDARIES.toml";

/// The one CODEOWNERS GitHub is allowed to find.
const ACTIVE: &str = ".github/CODEOWNERS";

/// Every location GitHub consults, in the precedence order it consults them.
///
/// A file at an earlier entry replaces every later one, so a shadow at
/// `CODEOWNERS` silently retires the whole active policy.
const LOCATIONS: &[&str] = &["CODEOWNERS", ".github/CODEOWNERS", "docs/CODEOWNERS"];

/// The script that applies branch protection.
const PROTECTION_SCRIPT: &str = "scripts/apply-branch-protection.sh";

/// The schema revision this reader understands.
const SCHEMA_VERSION: u32 = 1;

/// A protected path and the packages it covers.
#[derive(Debug, Deserialize)]
pub struct Boundary {
    /// CODEOWNERS pattern, rooted with a leading slash.
    pub pattern: String,
    /// Workspace members this pattern covers, empty for a non-package path.
    pub packages: Vec<String>,
    /// Why the path is protected.
    pub reason: String,
    /// The failure class the protection defends against.
    pub defends: String,
}

/// A workspace member deliberately left unprotected.
#[derive(Debug, Deserialize)]
pub struct Open {
    /// Workspace member name as it appears in the root manifest.
    pub package: String,
    /// Why no maintainer review is required for it.
    pub reason: String,
}

/// The protected-boundary manifest.
#[derive(Debug, Deserialize)]
pub struct Manifest {
    /// Schema revision.
    pub schema_version: u32,
    /// The review team every boundary names.
    pub owner: String,
    /// The branch whose protection must require that review.
    pub protected_branch: String,
    /// Protected paths.
    #[serde(default)]
    pub boundary: Vec<Boundary>,
    /// Members with the decision recorded not to protect them.
    #[serde(default)]
    pub open: Vec<Open>,
}

/// Read the manifest, refusing a revision this reader does not understand.
pub fn parse_manifest(text: &str) -> Result<Manifest, GateError> {
    let manifest: Manifest = toml::from_str(text).map_err(|error| {
        GateError::new(
            format!("{MANIFEST} does not parse: {error}"),
            "fix the manifest; the active CODEOWNERS is generated from it",
        )
    })?;
    if manifest.schema_version != SCHEMA_VERSION {
        return Err(GateError::new(
            format!(
                "{MANIFEST} declares schema_version {}, and this reader understands {SCHEMA_VERSION}",
                manifest.schema_version
            ),
            "migrate the manifest or teach the gate the new revision; a silently \
             half-read manifest generates a CODEOWNERS missing boundaries",
        ));
    }
    Ok(manifest)
}

/// Render the CODEOWNERS body the manifest describes.
#[must_use]
pub fn render(manifest: &Manifest) -> String {
    let mut out = String::new();
    out.push_str(
        "# Generated from docs/PROTECTED_BOUNDARIES.toml by `xtask codeowners --write`.\n",
    );
    out.push_str("# Do not edit this file. Edit the manifest and regenerate.\n");
    out.push_str("#\n");
    out.push_str(
        "# GitHub reads the first CODEOWNERS it finds at CODEOWNERS, .github/CODEOWNERS or\n\
         # docs/CODEOWNERS. A file at an earlier location replaces this one in full, so the\n\
         # `codeowners` gate refuses a second file at any of them.\n",
    );
    for boundary in &manifest.boundary {
        out.push('\n');
        out.push_str(&format!("# {}\n", boundary.reason));
        out.push_str(&format!("# Defends: {}\n", boundary.defends));
        out.push_str(&format!("{} {}\n", boundary.pattern, manifest.owner));
    }
    out
}

/// Whether a tracked path is covered by a CODEOWNERS pattern.
///
/// Only the two shapes the manifest uses: a directory prefix ending in `/`, and
/// an exact file path. A glob would need GitHub's own matcher to be trustworthy,
/// so the manifest does not permit one and this function does not pretend to.
#[must_use]
pub fn pattern_matches(pattern: &str, path: &str) -> bool {
    let rooted = pattern.strip_prefix('/').unwrap_or(pattern);
    if let Some(directory) = rooted.strip_suffix('/') {
        path.starts_with(directory) && path.as_bytes().get(directory.len()) == Some(&b'/')
    } else {
        path == rooted
    }
}

/// Everything wrong with the protection surface.
///
/// Pure in its inputs so each mutation the row names can be tested by changing
/// one argument: a deleted active file, a renamed boundary, a shadow at a
/// higher-precedence location, a pattern matching nothing, a member in neither
/// roster, and a protection payload that stops requiring the owner review.
#[must_use]
pub fn audit(
    manifest: &Manifest,
    members: &[String],
    tracked: &[PathBuf],
    active: Option<&str>,
    present_locations: &[&str],
    protection_script: Option<&str>,
) -> Vec<Finding> {
    let mut findings = Vec::new();
    let paths: Vec<String> = tracked
        .iter()
        .map(|path| path.to_string_lossy().replace('\\', "/"))
        .collect();

    for location in present_locations {
        if *location != ACTIVE {
            findings.push(Finding::in_file(
                *location,
                format!("a second CODEOWNERS at `{location}` takes precedence over `{ACTIVE}`"),
                format!(
                    "delete it; {MANIFEST} is the one policy source and {ACTIVE} is the one \
                     file generated from it"
                ),
            ));
        }
    }

    for boundary in &manifest.boundary {
        if !boundary.pattern.starts_with('/') {
            findings.push(Finding::in_file(
                MANIFEST,
                format!("boundary pattern `{}` is not rooted", boundary.pattern),
                "start the pattern with `/`; an unrooted pattern matches the same name at \
                 every depth, which is wider than the boundary it claims",
            ));
        }
        if !paths
            .iter()
            .any(|path| pattern_matches(&boundary.pattern, path))
        {
            findings.push(Finding::in_file(
                MANIFEST,
                format!(
                    "boundary pattern `{}` matches no tracked path",
                    boundary.pattern
                ),
                "point it at a path this tree carries or delete the row; a pattern that \
                 matches nothing protects nothing while reading as policy",
            ));
        }
        for package in &boundary.packages {
            if !members.iter().any(|member| member == package) {
                findings.push(Finding::in_file(
                    MANIFEST,
                    format!(
                        "boundary `{}` covers `{package}`, which is not a workspace member",
                        boundary.pattern
                    ),
                    "name a current member or drop it; the package moved and the boundary \
                     did not follow",
                ));
            } else if !pattern_matches(&boundary.pattern, &format!("{package}/Cargo.toml")) {
                findings.push(Finding::in_file(
                    MANIFEST,
                    format!(
                        "boundary `{}` claims to cover `{package}`, whose directory it does \
                         not match",
                        boundary.pattern
                    ),
                    "match the pattern to the member directory; the claim and the pattern \
                     disagree, so review lands on the wrong tree",
                ));
            }
        }
    }

    let mut decided: BTreeSet<&str> = BTreeSet::new();
    let mut duplicated: Vec<String> = Vec::new();
    for package in manifest
        .boundary
        .iter()
        .flat_map(|boundary| boundary.packages.iter())
        .chain(manifest.open.iter().map(|open| &open.package))
    {
        if !decided.insert(package.as_str()) {
            duplicated.push(package.clone());
        }
    }
    for package in duplicated {
        findings.push(Finding::in_file(
            MANIFEST,
            format!("`{package}` records two protection decisions"),
            "keep one; two rows for one member means the effective decision depends on \
             which a reader stops at",
        ));
    }
    for member in members {
        if !decided.contains(member.as_str()) {
            findings.push(Finding::in_file(
                MANIFEST,
                format!("workspace member `{member}` records no protection decision"),
                "cover it with a boundary, or add an `[[open]]` row saying why no \
                 maintainer review is required for it",
            ));
        }
    }
    for package in &decided {
        if !members.iter().any(|member| member == *package) && !package.is_empty() {
            findings.push(Finding::in_file(
                MANIFEST,
                format!("`{package}` is recorded but is not a workspace member"),
                "remove the row; it decides nothing and hides the member that replaced it",
            ));
        }
    }

    for required in [MANIFEST, ACTIVE, "xtask/src/gates/codeowners.rs"] {
        if !manifest
            .boundary
            .iter()
            .any(|boundary| pattern_matches(&boundary.pattern, required))
        {
            findings.push(Finding::in_file(
                MANIFEST,
                format!("`{required}` is not protected by any boundary"),
                "add a boundary for it; the policy, the file it generates and the generator \
                 must each require the review they impose on everything else",
            ));
        }
    }

    let expected = render(manifest);
    match active {
        None => findings.push(Finding::in_file(
            ACTIVE,
            "the active CODEOWNERS is missing",
            "run `xtask codeowners --write`; with no file GitHub requires no owner review \
             anywhere",
        )),
        Some(text) if text != expected => findings.push(Finding::in_file(
            ACTIVE,
            "the active CODEOWNERS is not what the manifest generates",
            format!("run `xtask codeowners --write`; edit {MANIFEST}, never the generated file"),
        )),
        Some(_) => {}
    }

    match protection_script {
        None => findings.push(Finding::in_file(
            PROTECTION_SCRIPT,
            "the branch-protection script is missing",
            "restore it; nothing else applies the protection that makes an owner line \
             required",
        )),
        Some(text) => {
            if !text.contains("require_code_owner_reviews") {
                findings.push(Finding::in_file(
                    PROTECTION_SCRIPT,
                    "branch protection does not require the code-owner review",
                    format!(
                        "set `require_code_owner_reviews` in the payload; without it every \
                         line of {ACTIVE} is advisory"
                    ),
                ));
            }
            if !text.contains(&manifest.protected_branch) {
                findings.push(Finding::in_file(
                    PROTECTION_SCRIPT,
                    format!(
                        "branch protection never names `{}`, the branch the manifest protects",
                        manifest.protected_branch
                    ),
                    "apply the protection to that branch, or record the branch the manifest \
                     actually means",
                ));
            }
        }
    }

    findings
}

/// The active CODEOWNERS is what the protected-boundary manifest generates.
pub struct Codeowners;

impl crate::gate::GateBehavior for Codeowners {
    fn usage(&self) -> &'static [&'static str] {
        &["--write    regenerate .github/CODEOWNERS from docs/PROTECTED_BOUNDARIES.toml"]
    }

    fn run(&self, ctx: &GateCtx) -> Result<Report, GateError> {
        let tree = Tree::open(&ctx.root)?;
        let manifest = parse_manifest(&tree.read(MANIFEST)?)?;
        let members = tree.members()?;

        let mut report = Report::clean();
        report.cover_complete("workspace members", members.len());
        report.note(format!(
            "{} protected boundar(ies), {} member(s) recorded open",
            manifest.boundary.len(),
            manifest.open.len()
        ));

        if ctx.write {
            std::fs::write(tree.absolute(ACTIVE), render(&manifest)).map_err(|error| {
                GateError::new(
                    format!("cannot write {ACTIVE}: {error}"),
                    "check the checkout is writable",
                )
            })?;
        }
        report.produced(ACTIVE);

        let present: Vec<&str> = LOCATIONS
            .iter()
            .copied()
            .filter(|location| tree.absolute(location).exists())
            .collect();
        let active = present
            .contains(&ACTIVE)
            .then(|| tree.read(ACTIVE))
            .transpose()?;
        let script = tree
            .absolute(PROTECTION_SCRIPT)
            .exists()
            .then(|| tree.read(PROTECTION_SCRIPT))
            .transpose()?;

        for finding in audit(
            &manifest,
            &members,
            tree.paths(),
            active.as_deref(),
            &present,
            script.as_deref(),
        ) {
            report.find(finding);
        }
        Ok(report)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Read the committed manifest for a test that needs the real roster.
    ///
    /// The root is resolved from the working directory at run time. A compiled
    /// unit is reused across checkouts that share a target directory, so a root
    /// baked in at compile time names whichever tree built last and this test
    /// would judge that tree's manifest while claiming to judge this one.
    fn committed_manifest() -> Manifest {
        let root = crate::checkout::checkout_root();
        let text = std::fs::read_to_string(root.join(MANIFEST)).expect("the manifest is committed");
        parse_manifest(&text).expect("the committed manifest parses")
    }

    /// A boundary the tests can mutate without restating every field.
    fn boundary(pattern: &str, packages: &[&str]) -> Boundary {
        Boundary {
            pattern: pattern.to_string(),
            packages: packages.iter().map(|name| (*name).to_string()).collect(),
            reason: "reason".to_string(),
            defends: "class".to_string(),
        }
    }

    /// A manifest that is clean against the fixture tree below.
    fn fixture() -> Manifest {
        Manifest {
            schema_version: SCHEMA_VERSION,
            owner: "@team".to_string(),
            protected_branch: "main".to_string(),
            boundary: vec![
                boundary("/vyre-spec/", &["vyre-spec"]),
                boundary(&format!("/{MANIFEST}"), &[]),
                boundary(&format!("/{ACTIVE}"), &[]),
                boundary("/xtask/src/gates/codeowners.rs", &[]),
            ],
            open: vec![Open {
                package: "vyre-libs".to_string(),
                reason: "reason".to_string(),
            }],
        }
    }

    /// Tracked paths the fixture manifest's patterns resolve against.
    fn tracked() -> Vec<PathBuf> {
        [
            "vyre-spec/src/lib.rs",
            "vyre-libs/src/lib.rs",
            MANIFEST,
            ACTIVE,
            "xtask/src/gates/codeowners.rs",
            PROTECTION_SCRIPT,
        ]
        .iter()
        .map(PathBuf::from)
        .collect()
    }

    fn members() -> Vec<String> {
        vec!["vyre-spec".to_string(), "vyre-libs".to_string()]
    }

    /// A protection payload that requires the owner review on `main`.
    const GOOD_SCRIPT: &str = "BRANCH=\"${1:-main}\"\nrequire_code_owner_reviews: true\n";

    fn run(manifest: &Manifest) -> Vec<String> {
        let rendered = render(manifest);
        audit(
            manifest,
            &members(),
            &tracked(),
            Some(&rendered),
            &[ACTIVE],
            Some(GOOD_SCRIPT),
        )
        .iter()
        .map(|finding| finding.message.to_string())
        .collect()
    }

    #[test]
    fn a_manifest_whose_every_claim_holds_reports_nothing() {
        assert!(run(&fixture()).is_empty(), "{:?}", run(&fixture()));
    }

    /// WHY: a manifest revision this reader does not understand would be
    /// half-read, and the CODEOWNERS generated from the half would be missing
    /// boundaries while looking generated.
    #[test]
    fn a_future_schema_revision_is_refused_rather_than_partly_read() {
        let text = "schema_version = 99\nowner = \"@team\"\nprotected_branch = \"main\"\n";
        assert!(parse_manifest(text).is_err());
    }

    /// WHY: the row's deletion mutation. With no file GitHub requires no owner
    /// review anywhere, and nothing else in the tree notices.
    #[test]
    fn a_deleted_active_file_is_reported() {
        let manifest = fixture();
        let findings = audit(
            &manifest,
            &members(),
            &tracked(),
            None,
            &[],
            Some(GOOD_SCRIPT),
        );
        assert!(findings
            .iter()
            .any(|finding| finding.message.contains("missing")));
    }

    /// WHY: the row's shadow mutation. A file at `CODEOWNERS` replaces
    /// `.github/CODEOWNERS` in full, which is the exact defect this row opened
    /// with, and neither file's own content shows it.
    #[test]
    fn a_shadow_at_a_higher_precedence_location_is_reported() {
        let manifest = fixture();
        let rendered = render(&manifest);
        let findings = audit(
            &manifest,
            &members(),
            &tracked(),
            Some(&rendered),
            &["CODEOWNERS", ACTIVE],
            Some(GOOD_SCRIPT),
        );
        assert!(findings
            .iter()
            .any(|finding| finding.message.contains("takes precedence")));
    }

    /// WHY: the row's rename mutation. A package that moves leaves a pattern
    /// aimed at a path that no longer exists, which reads as protection.
    #[test]
    fn a_pattern_matching_no_tracked_path_is_reported() {
        let mut manifest = fixture();
        manifest.boundary[0] = boundary("/vyre-wgpu/", &[]);
        assert!(run(&manifest)
            .iter()
            .any(|message| message.contains("matches no tracked path")));
    }

    /// WHY: the same rename seen from the package side. The directory moved and
    /// the pattern stayed, so the boundary claims a member it does not cover.
    #[test]
    fn a_boundary_claiming_a_package_it_does_not_cover_is_reported() {
        let mut manifest = fixture();
        manifest.boundary[0] = boundary("/vyre-libs/", &["vyre-spec"]);
        assert!(run(&manifest)
            .iter()
            .any(|message| message.contains("whose directory it does")));
    }

    /// WHY: the row's unowned-new-crate mutation. Adding a member must turn this
    /// red until the decision is written down, otherwise the roster drifts in
    /// silence and the gate certifies a closure it never had.
    #[test]
    fn a_member_in_neither_roster_is_reported() {
        let manifest = fixture();
        let mut roster = members();
        roster.push("vyre-newcomer".to_string());
        let rendered = render(&manifest);
        let findings = audit(
            &manifest,
            &roster,
            &tracked(),
            Some(&rendered),
            &[ACTIVE],
            Some(GOOD_SCRIPT),
        );
        assert!(findings
            .iter()
            .any(|finding| finding.message.contains("vyre-newcomer")));
    }

    /// WHY: a member recorded twice makes the effective decision depend on which
    /// row a reader stops at, and one of the two is silently dead.
    #[test]
    fn a_member_recorded_twice_is_reported() {
        let mut manifest = fixture();
        manifest.open.push(Open {
            package: "vyre-spec".to_string(),
            reason: "second".to_string(),
        });
        assert!(run(&manifest)
            .iter()
            .any(|message| message.contains("two protection decisions")));
    }

    /// WHY: the row's ownership-weakening mutation. A contributor who can edit
    /// the manifest, the generated file, or the generator can remove every other
    /// restriction, so all three must protect themselves.
    #[test]
    fn dropping_the_self_protecting_boundaries_is_reported() {
        for index in 1..4 {
            let mut manifest = fixture();
            let dropped = manifest.boundary.remove(index);
            let messages = run(&manifest);
            assert!(
                messages
                    .iter()
                    .any(|message| message.contains("is not protected by any boundary")),
                "dropping {} went unreported: {messages:?}",
                dropped.pattern
            );
        }
    }

    /// WHY: this is the weakening that leaves every other check green. CODEOWNERS
    /// is advisory unless branch protection asks for the owner review, so a
    /// payload that stops asking retires the whole boundary without touching a
    /// single owner line.
    #[test]
    fn a_protection_payload_that_stops_requiring_the_owner_review_is_reported() {
        let manifest = fixture();
        let rendered = render(&manifest);
        let findings = audit(
            &manifest,
            &members(),
            &tracked(),
            Some(&rendered),
            &[ACTIVE],
            Some("BRANCH=\"${1:-main}\"\nrequired_pull_request_reviews=null\n"),
        );
        assert!(findings
            .iter()
            .any(|finding| finding.message.contains("code-owner review")));
    }

    /// WHY: protecting a branch nobody merges into is protection theatre.
    #[test]
    fn protecting_a_branch_the_manifest_does_not_name_is_reported() {
        let manifest = fixture();
        let rendered = render(&manifest);
        let findings = audit(
            &manifest,
            &members(),
            &tracked(),
            Some(&rendered),
            &[ACTIVE],
            Some("BRANCH=\"${1:-trunk}\"\nrequire_code_owner_reviews: true\n"),
        );
        assert!(findings
            .iter()
            .any(|finding| finding.message.contains("protected_branch")
                || finding.message.contains("the branch the manifest protects")));
    }

    /// WHY: a hand edit to the generated file is the one change that survives
    /// review unnoticed, because the file looks exactly like a generated file.
    #[test]
    fn a_hand_edited_active_file_is_reported() {
        let manifest = fixture();
        let mut edited = render(&manifest);
        edited.push_str("/vyre-libs/ @someone-else\n");
        let findings = audit(
            &manifest,
            &members(),
            &tracked(),
            Some(&edited),
            &[ACTIVE],
            Some(GOOD_SCRIPT),
        );
        assert!(findings
            .iter()
            .any(|finding| finding.message.contains("not what the manifest generates")));
    }

    /// WHY: an unrooted pattern matches the same name at every depth, so it is
    /// wider than the boundary it appears to describe.
    #[test]
    fn an_unrooted_pattern_is_reported() {
        let mut manifest = fixture();
        manifest.boundary[0] = boundary("vyre-spec/", &["vyre-spec"]);
        assert!(run(&manifest)
            .iter()
            .any(|message| message.contains("is not rooted")));
    }

    /// WHY: prefix matching that forgets the separator would let `/vyre-spec/`
    /// claim `vyre-spec-extra/`, quietly widening every directory boundary.
    #[test]
    fn a_directory_pattern_does_not_claim_a_sibling_sharing_its_prefix() {
        assert!(pattern_matches("/vyre-spec/", "vyre-spec/src/lib.rs"));
        assert!(!pattern_matches(
            "/vyre-spec/",
            "vyre-spec-extra/src/lib.rs"
        ));
        assert!(pattern_matches("/Cargo.toml", "Cargo.toml"));
        assert!(!pattern_matches("/Cargo.toml", "xtask/Cargo.toml"));
    }

    /// WHY: the roster in the committed manifest is the thing that goes stale,
    /// and a fixture-only suite would never notice.
    #[test]
    fn the_committed_manifest_names_one_owner_for_every_boundary() {
        let manifest = committed_manifest();
        assert!(manifest.owner.starts_with('@'));
        assert!(!manifest.boundary.is_empty());
        for boundary in &manifest.boundary {
            assert!(
                boundary.reason.len() > 20 && boundary.defends.len() > 4,
                "boundary {} states no reason a reviewer can act on",
                boundary.pattern
            );
        }
        for open in &manifest.open {
            assert!(
                open.reason.len() > 20,
                "`{}` is open with no reason recorded",
                open.package
            );
        }
    }
}
