//! Every evidence artifact states the tree, host and device behind it, or
//! states in writing that its origin is unknown.
//!
//! `evidence-provenance` asks whether a recorded fingerprint resolves against
//! the commit that carries it. That question only has an answer for an artifact
//! that recorded one, and 46 of the 88 artifacts in this corpus recorded
//! nothing at all, so nothing judged them. None of the 88 named a host, and the
//! device facts a performance claim requires had no field to live in.
//!
//! This gate judges the record itself, over the complete artifact set derived
//! from the directory at run time rather than from a list that goes stale. An
//! artifact carrying no record is not skipped: it is either regenerated by the
//! gate that owns it, or it appears in the ledger this gate owns, which states
//! for each such artifact why its origin is unknown and the exact command that
//! recaptures it.
//!
//! The ledger is what makes an unverifiable measurement uncommittable in
//! silence. Without `--write` the generated ledger is compared against the
//! committed one and every difference is a finding, so a new artifact with no
//! provenance fails the sweep. Recording it requires `evidence-attribution
//! --write` and a committed diff that says the number's origin is unknown.
//! Nothing here ever gives a measurement a commit it did not come from.
//!
//! A ledger row is refused for an artifact whose owning gate does not need a
//! device. That artifact is regenerable wherever the compiler builds, so the
//! honest state of it is regenerated, and the finding says which gate does it.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};
use std::process::Command;

use serde::Serialize;

use crate::artifact_gate::{self, Inspection};
use crate::evidence_record::{self, MeasurementRecord, ProvenanceIssue};
use crate::gate::{Finding, GateCtx, GateError, Report, ResourceClass};
use crate::gate_metadata;

/// Where release evidence lives.
const EVIDENCE_DIR: &str = "release/evidence";

/// The ledger of artifacts this tree cannot attribute.
pub const UNATTRIBUTED_LEDGER: &str = "release/evidence/metadata/unattributed-evidence.json";

/// Version of the ledger shape.
const LEDGER_SCHEMA_VERSION: u32 = 1;

/// What to do about a ledger that no longer describes the corpus.
const LEDGER_FIX: &str = "run `./cargo_full run -p xtask --bin xtask -- evidence-attribution \
                          --write` and commit the ledger, which records in writing that the \
                          origins of the artifacts it names are unknown";

/// One artifact whose origin this tree cannot establish.
#[derive(Clone, Debug, Serialize)]
struct UnattributedArtifact {
    /// Workspace-relative path of the artifact.
    path: String,
    /// Why nothing in this tree identifies where its numbers came from.
    reason: String,
    /// The exact command that replaces it with an attributable record.
    recapture: String,
}

/// The complete set of evidence artifacts carrying no provenance record.
#[derive(Clone, Debug, Serialize)]
struct UnattributedLedger {
    /// Version of this shape.
    schema_version: u32,
    /// How many evidence artifacts state no origin.
    unattributed_count: usize,
    /// How many state one, and are judged against it.
    attributed_count: usize,
    /// Every artifact whose origin is unknown, sorted by path.
    artifacts: Vec<UnattributedArtifact>,
}

/// Every evidence artifact is attributable, or recorded as not being.
pub struct EvidenceAttribution;

impl crate::gate::GateBehavior for EvidenceAttribution {
    fn run(&self, ctx: &GateCtx) -> Result<Report, GateError> {
        let artifacts = evidence_artifacts(&ctx.root)?;
        let owners = evidence_owners();
        let mut ancestry = Ancestry::new(&ctx.root);
        let mut inspection = Inspection::new();
        let mut rows = Vec::new();
        let mut attributed = 0_usize;
        let mut recorded_unknown = 0_usize;
        let mut prose = 0_usize;

        for relative in &artifacts {
            if relative == UNATTRIBUTED_LEDGER {
                continue;
            }
            if !artifact_gate::records_provenance(Path::new(relative)) {
                prose += 1;
                continue;
            }
            let text = match crate::output_arg::read_text_bounded(
                &ctx.root.join(relative),
                artifact_gate::MAX_ARTIFACT_BYTES,
                "release evidence artifact",
            ) {
                Ok(text) => text,
                Err(error) => {
                    inspection.find(Finding::in_file(
                        PathBuf::from(relative),
                        format!("`{relative}` could not be read: {error}"),
                        "restore the artifact or delete it, so the corpus names only records \
                         that exist",
                    ));
                    continue;
                }
            };
            let (record, _) = artifact_gate::split_provenance(&text);
            let record = match record {
                Ok(record) => record,
                Err(ProvenanceIssue::Absent) => {
                    match unattributed_row(relative, owners.get(relative.as_str()).copied()) {
                        Ok(row) => rows.push(row),
                        Err(finding) => inspection.find(finding),
                    }
                    continue;
                }
                Err(issue) => {
                    inspection.find(Finding::in_file(
                        PathBuf::from(relative),
                        format!("`{relative}` {}", issue.predicate()),
                        LEDGER_FIX,
                    ));
                    continue;
                }
            };
            if record.is_unattributable() {
                recorded_unknown += 1;
            } else {
                attributed += 1;
            }
            for issue in evidence_record::issues(&record, &mut |commit| ancestry.contains(commit)) {
                inspection.find(Finding::in_file(
                    PathBuf::from(relative),
                    format!("`{relative}` {}", issue.predicate()),
                    recapture_of(relative, owners.get(relative.as_str()).copied()),
                ));
            }
        }

        rows.sort_by(|left, right| left.path.cmp(&right.path));
        let ledger = UnattributedLedger {
            schema_version: LEDGER_SCHEMA_VERSION,
            unattributed_count: rows.len(),
            attributed_count: attributed,
            artifacts: rows,
        };
        let unattributed = ledger.unattributed_count;
        inspection.generates_evidence(UNATTRIBUTED_LEDGER, MeasurementRecord::HostOnly, &ledger);
        let mut report = artifact_gate::settle_inspection(ctx, ctx.gate_name()?, inspection);
        report.coverage.clear();
        report.cover(crate::gate::Coverage::complete_identities(
            "release evidence artifacts",
            artifacts.clone(),
        ));
        report.note(format!(
            "{attributed} artifact(s) name the tree, host and device behind them, \
             {recorded_unknown} record that their origin is unknown, {unattributed} carry no \
             record and are named in the ledger, {prose} are prose and carry none"
        ));
        Ok(report)
    }
}

/// Every file under [`EVIDENCE_DIR`], workspace-relative, sorted.
///
/// The set comes from the directory rather than a constant. An artifact added
/// beside the others is judged the moment it lands, which is the only way this
/// gate cannot certify a corpus it never read.
fn evidence_artifacts(root: &Path) -> Result<Vec<String>, GateError> {
    let mut found = Vec::new();
    for entry in walkdir::WalkDir::new(root.join(EVIDENCE_DIR)) {
        let entry = entry.map_err(|error| {
            GateError::new(
                format!("`{EVIDENCE_DIR}` could not be walked: {error}"),
                "restore the evidence directory",
            )
        })?;
        if !entry.file_type().is_file() {
            continue;
        }
        let relative = entry
            .path()
            .strip_prefix(root)
            .map_err(|error| {
                GateError::new(
                    format!(
                        "`{}` is not under the checkout root: {error}",
                        entry.path().display()
                    ),
                    "run the gate against the workspace that holds the evidence",
                )
            })?
            .to_string_lossy()
            .replace('\\', "/");
        found.push(relative);
    }
    found.sort();
    Ok(found)
}

/// The owning gate and its resource class for every declared evidence artifact.
fn evidence_owners() -> BTreeMap<&'static str, (&'static str, ResourceClass)> {
    let mut owners = BTreeMap::new();
    for (artifact, gate) in gate_metadata::generated_artifacts() {
        if !artifact.starts_with(EVIDENCE_DIR) {
            continue;
        }
        let class = gate_metadata::descriptor(gate)
            .map_or(ResourceClass::Cpu, |descriptor| descriptor.resource_class);
        owners.insert(artifact, (gate, class));
    }
    owners
}

/// The command that produces an attributable record of `relative`.
fn recapture_of(relative: &str, owner: Option<(&'static str, ResourceClass)>) -> String {
    match owner {
        Some((gate, ResourceClass::Device)) => format!(
            "run `./cargo_full run -p xtask --bin xtask -- {gate} --write` on a host carrying the \
             device the record names, and commit `{relative}` with the provenance it wrote"
        ),
        Some((gate, _)) => format!(
            "run `./cargo_full run -p xtask --bin xtask -- {gate} --write` and commit \
             `{relative}` with the provenance it wrote"
        ),
        None => format!(
            "declare `{relative}` in the artifacts of the gate that produces it, so one gate \
             regenerates it and its provenance"
        ),
    }
}

/// A ledger row for `relative`, or the finding that says to regenerate it instead.
///
/// A gate that needs no device produces its artifact wherever the compiler
/// builds, so an artifact of unknown origin that such a gate owns has a fix
/// rather than an excuse, and the ledger refuses to hold it.
fn unattributed_row(
    relative: &str,
    owner: Option<(&'static str, ResourceClass)>,
) -> Result<UnattributedArtifact, Finding> {
    let reason = match owner {
        Some((gate, ResourceClass::Device)) => format!(
            "carries no provenance record, and `{gate}` reproduces it only on a host carrying \
             the device it measured, which this tree cannot identify"
        ),
        Some((gate, _)) => {
            return Err(Finding::in_file(
                PathBuf::from(relative),
                format!(
                    "`{relative}` carries no provenance record and `{gate}` regenerates it \
                     without a device, so its origin is recoverable and must not be recorded as \
                     unknown"
                ),
                recapture_of(relative, owner),
            ));
        }
        None => "carries no provenance record, and no registered gate declares it, so nothing \
                 in this tree states what produced it"
            .to_string(),
    };
    Ok(UnattributedArtifact {
        path: relative.to_string(),
        reason,
        recapture: recapture_of(relative, owner),
    })
}

/// Whether a commit is one this branch contains, asked once per commit.
struct Ancestry<'a> {
    root: &'a Path,
    answered: BTreeMap<String, bool>,
}

impl<'a> Ancestry<'a> {
    /// Judge commits against the checkout at `root`.
    fn new(root: &'a Path) -> Self {
        Self {
            root,
            answered: BTreeMap::new(),
        }
    }

    /// Whether `HEAD` contains `commit`.
    ///
    /// A commit git cannot resolve is not contained. An artifact naming a
    /// commit this checkout does not carry describes a tree no reader can get
    /// to, which is the same defect as naming none.
    fn contains(&mut self, commit: &str) -> bool {
        if let Some(answer) = self.answered.get(commit) {
            return *answer;
        }
        let answer = Command::new("git")
            .arg("-C")
            .arg(self.root)
            .args(["merge-base", "--is-ancestor", commit, "HEAD"])
            .status()
            .is_ok_and(|status| status.success());
        self.answered.insert(commit.to_string(), answer);
        answer
    }
}

/// Artifacts the ledger holds, by path, for readers that need the set.
#[must_use]
pub fn ledger_paths(ledger: &str) -> BTreeSet<String> {
    serde_json::from_str::<serde_json::Value>(ledger)
        .ok()
        .and_then(|value| {
            value.get("artifacts")?.as_array().map(|rows| {
                rows.iter()
                    .filter_map(|row| row.get("path")?.as_str().map(str::to_string))
                    .collect()
            })
        })
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::evidence_record::{DeviceFacts, EvidenceProvenance, HostRecord, TreeRecord};

    fn owner(class: ResourceClass) -> Option<(&'static str, ResourceClass)> {
        Some(("release-benchmarks", class))
    }

    /// WHY: the defect this gate exists for is an artifact of unknown origin
    /// that nothing reports. A device-only artifact carrying no record earns a
    /// ledger row naming the command that recaptures it, never a commit.
    #[test]
    fn a_device_artifact_with_no_record_is_named_in_the_ledger() {
        let row = unattributed_row(
            "release/evidence/benchmarks/cuda-release-suite.json",
            owner(ResourceClass::Device),
        )
        .expect("a device artifact is ledger-eligible");
        assert_eq!(
            row.path,
            "release/evidence/benchmarks/cuda-release-suite.json"
        );
        assert!(
            row.reason.contains("carries no provenance record"),
            "the row states why the origin is unknown: {}",
            row.reason
        );
        assert!(
            row.recapture.contains("release-benchmarks --write")
                && row.recapture.contains("host carrying the device"),
            "the row names the command and where it runs: {}",
            row.recapture
        );
    }

    /// WHY: the ledger must never absorb an artifact this host can regenerate,
    /// which is the one way a waiver list becomes a place to hide numbers.
    #[test]
    fn a_host_reproducible_artifact_with_no_record_is_a_finding() {
        for class in [
            ResourceClass::Cpu,
            ResourceClass::Io,
            ResourceClass::Process,
        ] {
            let finding =
                unattributed_row("release/evidence/hygiene/hygiene-matrix.json", owner(class))
                    .expect_err("a gate needing no device has no excuse");
            assert!(
                finding.message.contains("must not be recorded as unknown"),
                "class {class} was allowed into the ledger: {}",
                finding.message
            );
            assert!(
                finding.fix.contains("release-benchmarks --write"),
                "the finding names the gate that regenerates it: {}",
                finding.fix
            );
        }
    }

    /// WHY: an artifact no gate declares has no regeneration path at all, and
    /// the fix is to declare it rather than to keep guessing at its origin.
    #[test]
    fn an_undeclared_artifact_is_told_to_be_declared() {
        let row = unattributed_row(
            "release/evidence/benchmarks/megakernel-default-routing.json",
            None,
        )
        .expect("an undeclared artifact is ledger-eligible");
        assert!(
            row.reason.contains("no registered gate declares it"),
            "the row states that nothing owns it: {}",
            row.reason
        );
        assert!(
            row.recapture.contains("declare"),
            "the row asks for a declaration: {}",
            row.recapture
        );
    }

    /// WHY: a dirty record names a worktree state no checkout reproduces, which
    /// is the state 23 artifacts in this corpus were committed in.
    #[test]
    fn a_dirty_record_is_reported() {
        let provenance = EvidenceProvenance {
            schema_version: crate::evidence_record::EVIDENCE_PROVENANCE_SCHEMA_VERSION,
            tree: TreeRecord::Attributed {
                branch: "integration".to_string(),
                commit: "24b6787218f5".to_string(),
                commit_timestamp: "1700000000".to_string(),
                parent_commit: "0000000000ff".to_string(),
                dirty: true,
                source_fingerprint: "git:24b6787218f5:dirty=true:worktree=abc".to_string(),
            },
            host: HostRecord::Recorded {
                hostname: "santhserver".to_string(),
                os: "linux".to_string(),
                architecture: "x86_64".to_string(),
                cpu_model: "AMD".to_string(),
                cpu_cores: 16,
            },
            measurement: MeasurementRecord::Device {
                devices: vec![DeviceFacts {
                    name: "NVIDIA GeForce RTX 3080 Ti".to_string(),
                    driver_version: "580.173.02".to_string(),
                }],
            },
        };
        let found = evidence_record::issues(&provenance, &mut |_| true);
        assert_eq!(
            found,
            vec![ProvenanceIssue::Dirty {
                commit: "24b6787218f5".to_string()
            }],
            "a dirty record is the only thing wrong with this one"
        );
    }

    /// WHY: the ledger is read back by the sweep comparison, so its shape has
    /// to survive a round trip through the serialized artifact.
    #[test]
    fn the_ledger_names_its_artifacts_after_a_round_trip() {
        let ledger = UnattributedLedger {
            schema_version: LEDGER_SCHEMA_VERSION,
            unattributed_count: 1,
            attributed_count: 2,
            artifacts: vec![UnattributedArtifact {
                path: "release/evidence/benchmarks/cuda-release-suite.json".to_string(),
                reason: "carries no provenance record".to_string(),
                recapture: "run the owning gate".to_string(),
            }],
        };
        let text = serde_json::to_string(&ledger).expect("the ledger serializes");
        assert_eq!(
            ledger_paths(&text),
            BTreeSet::from(["release/evidence/benchmarks/cuda-release-suite.json".to_string()])
        );
    }

    /// WHY: a hardcoded artifact list is how a corpus gate comes to certify
    /// files it never read. The set is the directory, so a new artifact is
    /// judged without anyone editing this gate.
    #[test]
    fn the_artifact_set_is_the_directory() {
        let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .expect("the xtask manifest has a workspace above it")
            .to_path_buf();
        let found = evidence_artifacts(&root).expect("the evidence directory is walkable");
        assert!(
            found.contains(&UNATTRIBUTED_LEDGER.to_string())
                || !root.join(UNATTRIBUTED_LEDGER).exists(),
            "the walk misses the ledger it owns"
        );
        for relative in &found {
            assert!(
                root.join(relative).is_file(),
                "`{relative}` came out of the walk and is not a file"
            );
        }
        let declared: BTreeSet<&str> = evidence_owners().keys().copied().collect();
        for artifact in declared {
            assert!(
                found.iter().any(|path| path == artifact),
                "gate metadata declares `{artifact}`, which is not in the evidence directory"
            );
        }
    }
}
