use serde::Serialize;

use super::artifact_status::ReleaseEvidenceArtifactStatus;

#[derive(Debug, Serialize)]
pub(crate) struct ReleaseEvidenceIndex {
    pub(crate) schema_version: u32,
    pub(crate) artifact_count: usize,
    pub(crate) artifacts: Vec<ReleaseEvidenceIndexEntry>,
    pub(crate) blockers: Vec<String>,
}

#[derive(Debug, Clone, Serialize)]
pub(crate) struct ReleaseEvidenceIndexEntry {
    pub(crate) path: String,
    pub(crate) owner_lane: &'static str,
    pub(crate) generator_command: String,
    pub(crate) command_mode: &'static str,
    pub(crate) bytes: u64,
    pub(crate) content_sha256: Option<String>,
    pub(crate) source_fingerprint: Option<String>,
    pub(crate) freshness_fingerprint: Option<String>,
    pub(crate) blockers: Vec<String>,
}

pub(crate) fn build_evidence_index<'a>(
    command_artifacts: impl Iterator<Item = &'a ReleaseEvidenceArtifactStatus>,
) -> ReleaseEvidenceIndex {
    let mut artifacts = command_artifacts
        .map(|artifact| ReleaseEvidenceIndexEntry {
            path: artifact.path.clone(),
            owner_lane: artifact.owner_lane,
            generator_command: artifact.generator_command.clone(),
            command_mode: artifact.command_mode,
            bytes: artifact.bytes,
            content_sha256: artifact.content_sha256.clone(),
            source_fingerprint: artifact.source_fingerprint.clone(),
            freshness_fingerprint: artifact.freshness_fingerprint.clone(),
            blockers: artifact.blockers.clone(),
        })
        .collect::<Vec<_>>();
    artifacts.sort_by(|left, right| left.path.cmp(&right.path));
    let blockers = artifacts
        .iter()
        .flat_map(|artifact| {
            artifact.blockers.iter().map(|blocker| {
                format!(
                    "`{}` generated by `{}`: {blocker}",
                    artifact.path, artifact.generator_command
                )
            })
        })
        .collect::<Vec<_>>();
    ReleaseEvidenceIndex {
        schema_version: 1,
        artifact_count: artifacts.len(),
        artifacts,
        blockers,
    }
}
