use super::fixtures::arb_program;
use super::*;
use crate::ir_inner::model::expr::Ident;
use std::collections::HashSet;
use std::sync::Arc;
use crate::ir::{AtomicOp, BufferDecl, DataType, Expr, Node, Program};
use proptest::prelude::*;

/// Legacy double-walk implementation for equivalence verification.
/// Mirrors every buffer-touching site that ProgramFacts::buffer_refs
/// records. `arb_node` generates every declared `Node` variant, so the
/// async and indirect-dispatch arms below are exercised rather than
/// carried for a corpus that never reached them.
fn referenced_buffers_legacy(program: &Program) -> HashSet<Ident> {
    let mut names = HashSet::new();
    walk_exprs(program, |expr| match expr {
        Expr::Load { buffer, .. }
        | Expr::BufLen { buffer }
        | Expr::BufferRef { buffer }
        | Expr::Atomic { buffer, .. } => {
            names.insert(buffer.clone());
        }
        _ => {}
    });
    walk_nodes(program, |node| match node {
        Node::Store { buffer, .. } => {
            names.insert(buffer.clone());
        }
        Node::IndirectDispatch { count_buffer, .. } => {
            names.insert(count_buffer.clone());
        }
        Node::AsyncLoad {
            source,
            destination,
            ..
        }
        | Node::AsyncStore {
            source,
            destination,
            ..
        } => {
            names.insert(source.clone());
            names.insert(destination.clone());
        }
        Node::AllReduce { buffer, .. } | Node::Broadcast { buffer, .. } => {
            names.insert(buffer.clone());
        }
        Node::AllGather { input, output, .. } | Node::ReduceScatter { input, output, .. } => {
            names.insert(input.clone());
            names.insert(output.clone());
        }
        _ => {}
    });
    names
}

proptest! {
    #![proptest_config(ProptestConfig {
        cases: 256,
        ..ProptestConfig::default()
    })]

    #[test]
    fn combined_walker_referenced_buffers_eq_legacy(program in arb_program()) {
        let combined = referenced_buffers(&program);
        let legacy = referenced_buffers_legacy(&program);
        prop_assert_eq!(combined, legacy);
    }
}

#[test]
fn referenced_buffers_collects_from_store_and_load() {
    let program = Program::wrapped(
        vec![
            BufferDecl::read("input", 0, DataType::U32).with_count(8),
            BufferDecl::output("out", 1, DataType::U32).with_count(8),
        ],
        [1, 1, 1],
        vec![
            Node::let_bind("x", Expr::load("input", Expr::u32(0))),
            Node::store("out", Expr::u32(0), Expr::var("x")),
            Node::Return,
        ],
    );

    let buffers = referenced_buffers(&program);
    assert!(buffers.contains(&Ident::from("input")));
    assert!(buffers.contains(&Ident::from("out")));
    assert_eq!(buffers.len(), 2);
}

#[test]
fn referenced_buffers_collects_from_atomic_and_indirect_dispatch() {
    let program = Program::wrapped(
        vec![
            BufferDecl::read_write("rw", 0, DataType::U32).with_count(8),
            BufferDecl::read("counts", 1, DataType::U32).with_count(8),
        ],
        [1, 1, 1],
        vec![
            Node::let_bind(
                "x",
                Expr::Atomic {
                    op: AtomicOp::Add,
                    buffer: "rw".into(),
                    index: Box::new(Expr::u32(0)),
                    expected: None,
                    value: Box::new(Expr::u32(1)),
                    ordering: crate::MemoryOrdering::SeqCst,
                },
            ),
            Node::IndirectDispatch {
                count_buffer: "counts".into(),
                count_offset: 0,
            },
            Node::Return,
        ],
    );

    let buffers = referenced_buffers(&program);
    assert!(buffers.contains(&Ident::from("rw")));
    assert!(buffers.contains(&Ident::from("counts")));
    assert_eq!(buffers.len(), 2);
}

/// The corpus must reach every `Node` variant the AST registry declares.
///
/// The variant set is read from `NODE_VARIANT_NAMES` at run time, so this
/// closes the class rather than one instance of it: adding a variant to the
/// `Node` declaration turns this RED until the variant is generated by
/// `fixtures::arb_node_with_depth` or listed in
/// `fixtures::CORPUS_EXCLUDED_NODE_VARIANTS` with a reason. Every corpus
/// consumer  -  the traversal properties here and the validator differential
/// property in `crate::validate`  -  inherits that coverage.
///
/// A hardcoded expectation would not: `arb_node` covered 8 of 20 variants
/// while its doc comment claimed the corpus was the union of what its callers
/// need, and nothing was red.
#[test]
fn corpus_generates_every_node_variant() {
    use crate::ir::{node_variant_name, NODE_VARIANT_NAMES};
    use fixtures::CORPUS_EXCLUDED_NODE_VARIANTS;
    use proptest::strategy::{Strategy, ValueTree};
    use proptest::test_runner::TestRunner;
    use std::collections::BTreeSet;

    let strategy = fixtures::arb_node_with_depth(3);
    let mut runner = TestRunner::deterministic();
    let mut generated = BTreeSet::new();
    for _ in 0..4096 {
        let node = strategy
            .new_tree(&mut runner)
            .expect("Fix: the IR-shape corpus must produce a value for every sample")
            .current();
        for_each_node(std::slice::from_ref(&node), |inner| {
            generated.insert(node_variant_name(inner));
        });
    }

    let declared: BTreeSet<&str> = NODE_VARIANT_NAMES.iter().copied().collect();
    let excluded: BTreeSet<&str> = CORPUS_EXCLUDED_NODE_VARIANTS
        .iter()
        .map(|(variant, _)| *variant)
        .collect();

    let unknown_exclusions: Vec<&str> = excluded.difference(&declared).copied().collect();
    assert!(
        unknown_exclusions.is_empty(),
        "Fix: CORPUS_EXCLUDED_NODE_VARIANTS names variants Node does not declare: \
         {unknown_exclusions:?}"
    );

    let generated_but_excluded: Vec<&str> =
        generated.intersection(&excluded).copied().collect();
    assert!(
        generated_but_excluded.is_empty(),
        "Fix: these variants are generated and also listed as excluded, so the recorded \
         reason is stale: {generated_but_excluded:?}"
    );

    let missing: Vec<&str> = declared
        .difference(&generated)
        .copied()
        .filter(|variant| !excluded.contains(variant))
        .collect();
    assert!(
        missing.is_empty(),
        "Fix: generate these Node variants in fixtures::arb_node_with_depth, or record why \
         each is excluded in fixtures::CORPUS_EXCLUDED_NODE_VARIANTS: {missing:?}"
    );
}

/// `any_descendant` stops at the first match instead of walking the rest.
///
/// The short circuit is the whole reason a scan uses it rather than
/// [`for_each_descendant`], and it is also why a visitor must NOT be
/// written as `any_descendant` with a predicate that always answers
/// `false`: the moment such a predicate answers `true` the visit becomes a
/// visit of a prefix, with no diagnostic.
#[test]
fn any_descendant_stops_at_the_first_match() {
    let store = |index: u32| Node::store("buf", Expr::u32(index), Expr::u32(index));
    let node = Node::Block(vec![store(0), store(1), store(2), store(3)]);
    let mut visited = 0;
    let found = any_descendant(&node, &mut |candidate| {
        visited += 1;
        matches!(candidate, Node::Store { .. })
    });
    assert!(found);
    assert_eq!(
        visited, 2,
        "Fix: any_descendant visited the Block and the first Store, then must stop"
    );
}

/// A predicate that never matches is offered every node and answers false.
#[test]
fn any_descendant_reaches_every_nested_body_and_reports_no_match() {
    let node = Node::Block(vec![Node::if_then(
        Expr::bool(true),
        vec![Node::Region {
            generator: Ident::from("vyre.visit.nested"),
            source_region: None,
            body: Arc::new(vec![Node::loop_for(
                "i",
                Expr::u32(0),
                Expr::u32(1),
                vec![Node::Return],
            )]),
        }],
    )]);
    let mut visited = 0;
    let found = any_descendant(&node, &mut |_| {
        visited += 1;
        false
    });
    assert!(!found);
    assert_eq!(
        visited, 5,
        "Fix: the walk must reach Block, If, Region, Loop and Return"
    );
}

/// The walk is an explicit worklist, so nesting depth costs heap.
///
/// The recursive descent this replaced overflowed the native stack on a
/// tree this deep, and the programs that reach that depth are exactly the
/// adversarial ones.
#[test]
fn any_descendant_survives_a_deeply_nested_tree() {
    let mut node = Node::store("buf", Expr::u32(0), Expr::u32(1));
    for _ in 0..1_000 {
        node = Node::if_then(Expr::bool(true), vec![node]);
    }
    assert!(
        any_descendant(&node, &mut |candidate| matches!(
            candidate,
            Node::Store { .. }
        )),
        "Fix: the store at the bottom of a 1000-deep tree must still be found"
    );
}
