[package]
name = "external_ir_extension"
version = "0.1.0"
edition = "2021"

[dependencies]
inventory = "=0.3.24"
vyre = "0.8.0"
vyre-driver = "0.8.0"
vyre-foundation = "0.8.0"

[workspace]

[patch.crates-io]
vyre = { path = "../../vyre" }
vyre-driver = { path = "../../vyre-driver" }
vyre-foundation = { path = "../../vyre-foundation" }
