//! Artifact constants for gate metadata declarations.

/// Exact generated artifacts for frozen contracts.
pub const FROZEN_CONTRACT_ARTIFACTS: &[&str] = &[
    "docs/frozen-traits/AlgebraicLaw.txt",
    "docs/frozen-traits/EnforceGate.txt",
    "docs/frozen-traits/ExprVisitor.txt",
    "docs/frozen-traits/Lowerable.txt",
    "docs/frozen-traits/MutationClass.txt",
    "docs/frozen-traits/PassBoundaryClass.txt",
    "docs/frozen-traits/VyreBackend.txt",
];

/// Exact generated artifacts for public API snapshots.
pub const PUBLIC_API_ARTIFACTS: &[&str] = &[
    "docs/public-api/vyre-aot.txt",
    "docs/public-api/vyre-debug.txt",
    "docs/public-api/vyre-driver-cuda.txt",
    "docs/public-api/vyre-driver-metal.txt",
    "docs/public-api/vyre-driver-reference.txt",
    "docs/public-api/vyre-driver-spirv.txt",
    "docs/public-api/vyre-driver-wgpu.txt",
    "docs/public-api/vyre-driver.txt",
    "docs/public-api/vyre-emit-metal.txt",
    "docs/public-api/vyre-emit-naga.txt",
    "docs/public-api/vyre-emit-ptx.txt",
    "docs/public-api/vyre-emit-spirv.txt",
    "docs/public-api/vyre-foundation.txt",
    "docs/public-api/vyre-libs.txt",
    "docs/public-api/vyre-lints.txt",
    "docs/public-api/vyre-lower.txt",
    "docs/public-api/vyre-macros.txt",
    "docs/public-api/vyre-megakernel.txt",
    "docs/public-api/vyre-pass-engine.txt",
    "docs/public-api/vyre-primitives.txt",
    "docs/public-api/vyre-reference.txt",
    "docs/public-api/vyre-runtime.txt",
    "docs/public-api/vyre-safetensors.txt",
    "docs/public-api/vyre-spec.txt",
    "docs/public-api/vyre.txt",
];

/// Exact generated artifacts for testing guides.
pub const TESTING_GUIDE_ARTIFACTS: &[&str] = &[
    "docs/testing/structure-gate.md",
    "docs/testing/vyre-alloc-probe.md",
    "docs/testing/vyre-aot.md",
    "docs/testing/vyre-bench.md",
    "docs/testing/vyre-conform-spec.md",
    "docs/testing/vyre-conform.md",
    "docs/testing/vyre-debug.md",
    "docs/testing/vyre-driver-cuda.md",
    "docs/testing/vyre-driver-metal.md",
    "docs/testing/vyre-driver-reference.md",
    "docs/testing/vyre-driver-spirv.md",
    "docs/testing/vyre-driver-wgpu.md",
    "docs/testing/vyre-driver.md",
    "docs/testing/vyre-emit-metal.md",
    "docs/testing/vyre-emit-naga.md",
    "docs/testing/vyre-emit-ptx.md",
    "docs/testing/vyre-emit-spirv.md",
    "docs/testing/vyre-foundation.md",
    "docs/testing/vyre-libs-analysis.md",
    "docs/testing/vyre-libs-bitset.md",
    "docs/testing/vyre-libs-builder.md",
    "docs/testing/vyre-libs-decode.md",
    "docs/testing/vyre-libs-device.md",
    "docs/testing/vyre-libs-encoding.md",
    "docs/testing/vyre-libs-fixpoint.md",
    "docs/testing/vyre-libs-graph.md",
    "docs/testing/vyre-libs-hash.md",
    "docs/testing/vyre-libs-math.md",
    "docs/testing/vyre-libs-nn.md",
    "docs/testing/vyre-libs-parsing.md",
    "docs/testing/vyre-libs-pattern.md",
    "docs/testing/vyre-libs-reasoning.md",
    "docs/testing/vyre-libs-reduce.md",
    "docs/testing/vyre-libs-rule.md",
    "docs/testing/vyre-libs-scheduling.md",
    "docs/testing/vyre-libs-security.md",
    "docs/testing/vyre-libs-solvers.md",
    "docs/testing/vyre-libs-text.md",
    "docs/testing/vyre-libs-vfs.md",
    "docs/testing/vyre-libs-visual.md",
    "docs/testing/vyre-libs.md",
    "docs/testing/vyre-lints.md",
    "docs/testing/vyre-lower.md",
    "docs/testing/vyre-macros.md",
    "docs/testing/vyre-megakernel.md",
    "docs/testing/vyre-pass-engine.md",
    "docs/testing/vyre-primitives.md",
    "docs/testing/vyre-reference.md",
    "docs/testing/vyre-registry-link.md",
    "docs/testing/vyre-runtime.md",
    "docs/testing/vyre-safetensors.md",
    "docs/testing/vyre-spec.md",
    "docs/testing/vyre-test-support.md",
    "docs/testing/vyre.md",
    "docs/testing/xtask-evidence.md",
    "docs/testing/xtask-registry.md",
    "docs/testing/xtask.md",
];
