//! Gate descriptors for gates starting with Q through Z.

use super::artifacts::*;
use crate::gate::{GateDescriptor, ResourceClass};

/// Static descriptor array for gates starting with Q through Z.
pub const GATES_Q_Z: [GateDescriptor; 39] = [
    GateDescriptor {
        name: "readback-ring",
        help: "Enforce readback-ring contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::frozen_contract::tests::neither_a_default_body_nor_a_comment_is_part_of_the_contract",
    },
    GateDescriptor {
        name: "release-benchmarks",
        help: "Hold release benchmark evidence artifacts under release/evidence/benchmarks/ to the \
        live benchmark registry and the committed evidence measurements. Proves every measured \
        benchmark case in the release suite exists in the registry, that no case is duplicated, \
        that measured speedups are positive and reproducible, and that no required release metric \
        is missing. The evidence is read from disk; --write updates the recorded artifacts.",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: crate::artifact_paths::RELEASE_BENCHMARKS_ARTIFACTS,
        prerequisites: &[],
        resource_class: ResourceClass::Device,
        proof: "xtask_evidence::bench::release_benchmarks::run::tests::authoritative_descriptor_declares_exact_release_benchmarks_artifacts",
    },
    GateDescriptor {
        name: "release-conformance",
        help: "Enforce the release conformance suite across the selected CUDA, WGPU, and CPU \
        reference backends. Proves every operation required by the current release OP_MATRIX \
        exists exactly once per selected backend and executes against vyre-reference. Non-F32 \
        outputs are byte-exact and F32 outputs stay within the Program-derived ULP cap. Proves \
        zero missing release rows, duplicate operation ids, malformed summaries, failed pairs, \
        and blockers. Runs the compiled suite on this host; CUDA and WGPU selections require \
        hardware acceleration. Run with --write to refresh release conformance evidence artifacts.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &[
            "release/evidence/conformance/cuda-conformance.json",
            "release/evidence/conformance/reference-conformance.json",
            "release/evidence/conformance/release-gate-log.json",
            "release/evidence/conformance/wgpu-conformance.json",
        ],
        prerequisites: &[],
        resource_class: ResourceClass::Device,
        proof: "crate::release::release_conformance::tests::diff_summary_validation_rejects_missing_and_wrong_backend_fields",
    },
    GateDescriptor {
        name: "release-docs",
        help: "Regenerate CHANGELOG.md's unreleased section and release/evidence/docs/release-notes-body.md from release/release-train.toml and the fragments under release/changes/unreleased, and report each line the committed copies disagree on. Proves the changelog keeps its `## [Unreleased]` heading and a released section under it, that at least one fragment is on disk, that every fragment carries exactly `category` and `text`, that the changelog carries every token the release train requires, that [versions] and [release_groups] declare a version, an owner repository and a package list with no package in two groups, and that every approval-gated external action has a unique id the launch record can name. Proves nothing about a historical release document or about what a registry has published: every fact is read from this checkout.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "owned documentation pages",
        inputs: &["release/release-train.toml", "release/changes/unreleased", "scripts/final-launch.sh", "scripts/publish-release.sh"],
        artifacts: &["CHANGELOG.md", "release/evidence/docs/release-notes-body.md"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::release::release_docs::tests::a_changelog_with_no_released_section_is_refused",
    },
    GateDescriptor {
        name: "release-evidence",
        help: "Regenerate release/evidence/final/release-evidence-run.json and expected-artifacts.json \
        and report each line the committed copies disagree on. Proves every required generator \
        declares at least one expected artifact, and that every declared artifact exists, is \
        non-empty, is readable and carries provenance. Proves nothing about whether those \
        generators pass: it no longer runs them. Each one is a registered gate, so the sweep \
        runs it and fails on it directly rather than through a spawn this gate reports \
        second-hand.",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &["docs/INDEX.md", "docs/SUMMARY.md", "release/evidence/backends/backend-matrix.json", "release/evidence/benchmarks/release-workload-matrix.json", "release/evidence/conformance/conformance-matrix.json", "release/evidence/hygiene/hygiene-matrix.json", "release/evidence/metadata/feature-matrix.json", "release/evidence/metadata/metadata-matrix.json", "release/evidence/optimization/optimization-corpus.json", "release/evidence/optimization/optimization-integration-matrix.json", "release/evidence/package/publish-readiness.json", "release/evidence/version/version-matrix.json"],
        artifacts: &[
            "release/evidence/final/expected-artifacts.json",
            "release/evidence/final/release-evidence-run.json",
        ],
        prerequisites: &["backend-matrix", "conformance-matrix", "docs-check", "feature-matrix", "hygiene-matrix", "metadata-matrix", "optimization-corpus", "optimization-matrix", "package-readiness", "release-workload-matrix", "version-matrix"],
        resource_class: ResourceClass::Process,
        proof: "xtask_evidence::release::release_evidence::tests::artifact_status_rejects_public_boundary_leaks",
    },
    GateDescriptor {
        name: "release-provenance",
        help: "Enforce dependency and release-provenance authority across crates, native tools, generators, baselines, schemas, and build scripts. Generates and verifies CycloneDX SBOM, signed SLSA provenance, and release provenance records.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "dependency and release provenance authority",
        inputs: &["Cargo.lock", "deny.toml", "Cargo.toml"],
        artifacts: &[
            "docs/generated/release-provenance.toml",
            "release/evidence/metadata/provenance-record.json",
            "release/evidence/metadata/sbom.json",
        ],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::release_provenance::tests::release_provenance_gate_enforces_clean_tree_and_rejects_unapproved_dependencies",
    },
    GateDescriptor {
        name: "release-workload-matrix",
        help: "Rebuild release/evidence/benchmarks/release-workload-matrix.json from the benchmark case \
        registry and the bench target manifest, and report each line the committed artifact \
        disagrees on. Proves every required release workload family matches at least one \
        registered case, that each family naming a CPU state-of-the-art baseline has one, and \
        that the matrix carries no blockers. Proves nothing about any measurement: no benchmark \
        runs here and no artifact any family names is read.",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &["release/evidence/benchmarks/release-workload-matrix.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Device,
        proof: "xtask_evidence::release::release_workload_matrix::tests::the_committed_matrix_body_is_what_the_registry_derives",
    },
    GateDescriptor {
        name: "repo-hygiene",
        help: "Enforce repo-hygiene contracts",
        package: "xtask",
        areas: &["prepublish"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::repo_hygiene::tests::a_double_extension_archive_is_still_an_artifact",
    },
    GateDescriptor {
        name: "schema-authority",
        help: "Enforce schema authority and typed decode contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "production sources across the workspace",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::schema_authority::tests::a_duplicated_version_literal_is_a_finding",
    },
    GateDescriptor {
        name: "schedule-ownership",
        help: "Enforce schedule-ownership contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "production sources outside the compiler boundary",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::schedule_ownership::tests::a_construction_with_no_received_decision_is_a_finding",
    },
    GateDescriptor {
        name: "script-ledger",
        help: "Enforce script-ledger contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &["xtask/script-assertion-ledger.md"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::script_ledger::tests::a_ledger_missing_a_structural_heading_is_an_error_not_a_clean_run",
    },
    GateDescriptor {
        name: "shader-source",
        help: "Enforce shader-source contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::shader_source::tests::only_shader_owning_paths_may_hold_shader_syntax",
    },
    GateDescriptor {
        name: "shrink",
        help: "Delta-debug every registered corpus case that fails its oracle down to a minimal reproducer; --program ID narrows to one, --oracle PATH replaces the oracle",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered IR corpus",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::shrink::tests::wire_round_trip_oracle_verifies_node_count_integrity",
    },
    GateDescriptor {
        name: "single-backlog",
        help: "Enforce single-backlog contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::repo_hygiene::tests::a_redirect_is_required_only_where_policy_is_tracked_and_a_policy_copy_is_always_reported",
    },
    GateDescriptor {
        name: "source-include-module",
        help: "Enforce source-include-module contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::source_reachability::include_module_tests::a_tracked_include_is_reported_and_a_generated_one_is_not",
    },
    GateDescriptor {
        name: "source-parses",
        help: "Enforce source-parses contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::source_reachability::tests::includes_and_trybuild_patterns_are_read",
    },
    GateDescriptor {
        name: "source-reachability",
        help: "Enforce source-reachability contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::source_reachability::tests::declarations_come_from_code_only",
    },
    GateDescriptor {
        name: "spirv-parity",
        help: "Enforce spirv-parity contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::backend_parity::tests::only_a_target_requiring_the_feature_counts_as_gated",
    },
    GateDescriptor {
        name: "supported-api",
        help: "Enforce that all public API items are classified by publication class, stability, and wire compatibility",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["docs/public-api", "docs/CRATE_OWNERSHIP.toml"],
        artifacts: &["docs/SUPPORTED_API.toml"],
        prerequisites: &["public-api-snapshot"],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::supported_api::tests::classify_line_identifies_kinds_and_stability",
    },
    GateDescriptor {
        name: "test-harness-isolation",
        help: "Enforce that every test naming a process-global API records a grouping decision",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "integration test files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::test_harness_isolation::tests::a_candidate_without_a_decision_is_reported_and_a_decided_one_is_not",
    },
    GateDescriptor {
        name: "test-material-placement",
        help: "Enforce test-material-placement contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &["Cargo.toml"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::test_material::tests::only_a_crate_that_declares_an_edge_can_be_a_referrer",
    },
    GateDescriptor {
        name: "test-only-capability",
        help: "Enforce that production crates do not declare capability compiled only for test builds",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "rust sources",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::test_only_capability::tests::a_test_only_pub_mod_in_a_production_crate_is_reported",
    },
    GateDescriptor {
        name: "test-target-membership",
        help: "Enforce that every integration-test file is declared by exactly one test target in its manifest",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "integration test files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::test_target_membership::tests::a_test_file_no_target_declares_is_reported_and_a_declared_one_is_not",
    },
    GateDescriptor {
        name: "testing-guides",
        help: "Enforce testing-guides contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "registered system invariants",
        inputs: &["docs/CRATE_OWNERSHIP.toml", "docs/testing/TESTING.toml", "Cargo.toml"],
        artifacts: TESTING_GUIDE_ARTIFACTS,
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::testing_guides::tests::a_field_missing_at_every_level_is_a_finding",
    },
    GateDescriptor {
        name: "trace-f32",
        help: "Run the recorded test inputs of every registered operation through the reference; --op-id ID narrows to one",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered IR corpus",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::trace_f32::tests::render_run_formats_hex_buffer_literals",
    },
    GateDescriptor {
        name: "tracked-modules",
        help: "Enforce that every committed module declaration has a tracked file",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "rust sources",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::tracked_modules::tests::an_untracked_file_behind_a_declaration_is_a_finding",
    },
    GateDescriptor {
        name: "unification",
        help: "Enforce unification contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::unification::tests::a_row_that_scans_a_missing_path_is_reported",
    },
    GateDescriptor {
        name: "variant-list-closure",
        help: "Enforce variant-list-closure contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "declared variant lists",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::variant_list_closure::tests::a_variant_the_list_omits_is_a_finding",
    },
    GateDescriptor {
        name: "verification-budget",
        help: "Measure what verification costs each tier and hold it to the budget its row \
        declares: the test targets built for it, the binaries they link, the test sources \
        byte-identical to a test source in another package, and the bytes the tier's test \
        sources occupy. The three counts are exact in both directions and disk use is a \
        ceiling. Also proves each shared contract body has one owning package and that no \
        `#[path]` include in a test resolves outside its own package. Proves nothing about \
        what the tests assert.",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace tiers",
        inputs: &["docs/CRATE_OWNERSHIP.toml", "docs/testing/VERIFICATION_BUDGET.toml"],
        artifacts: &["docs/testing/VERIFICATION_BUDGET.toml", "release/evidence/tests/verification-budget.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::verification_budget::tests::a_count_below_its_row_fails_as_loudly_as_one_above",
    },
    GateDescriptor {
        name: "verify-rewrite-proofs",
        help: "Verify every optimizer rewrite proof fixture",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered IR corpus",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::verify_rewrite_proofs::tests::solver_verdicts_are_classified_soundly",
    },
    GateDescriptor {
        name: "version-matrix",
        help: "Regenerate release/evidence/version/version-matrix.json and release/evidence/version/release-tag-plan.json from \
        the workspace manifests, Cargo.lock and the release docs, and report each line the \
        committed copies disagree on. Proves every publishable crate carries the version the \
        release train declares, that every required release package is present at its expected \
        version, that pinned dependency and lockfile versions match, that no release doc gives \
        a bare tag command, and that release notes carry no stale version token. Proves nothing \
        about what is published on a registry: every fact here is read from this checkout.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &[
            "release/evidence/version/version-matrix.json",
            "release/evidence/version/release-tag-plan.json",
        ],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::release::version_matrix::tests::bare_final_tag_commands_are_rejected",
    },
    GateDescriptor {
        name: "vyre-release-gate",
        help: "Enforce release evidence closure; the default judges the prepublication set, --launch-complete judges the post-ship set, --manifest PATH names another manifest",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_evidence::release::vyre_release_gate::paths::tests::evidence_paths_that_climb_past_the_repository_root_are_rejected",
    },
    GateDescriptor {
        name: "whats-similar",
        help: "Report duplicate operations by IR shape across the whole registry; --op-id ID adds a focused view",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[crate::artifact_paths::REGISTERED_OP_DUPLICATES_ARTIFACT],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::whats_similar::query::tests::a_skip_class_over_its_ceiling_is_a_finding",
    },
    GateDescriptor {
        name: "wire-determinism",
        help: "Enforce wire-determinism contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::wire_determinism::tests::a_suite_reserves_only_what_its_own_manifest_entry_names",
    },
    GateDescriptor {
        name: "workspace-check",
        help: "Enforce workspace-check contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::workspace_build::tests::workspace_check_invokes_cargo_check_across_all_features",
    },
    GateDescriptor {
        name: "workspace-clippy",
        help: "Enforce workspace-clippy contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::workspace_build::tests::the_driver_separator_bounds_the_cargo_arguments",
    },
    GateDescriptor {
        name: "workspace-docs",
        help: "Enforce workspace-docs contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["Cargo.toml"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::workspace_build::tests::only_the_gate_that_cannot_deny_a_warning_judges_one",
    },
    GateDescriptor {
        name: "workspace-membership",
        help: "Enforce workspace-membership contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::manifest_contract::tests::inheritance_without_an_entry_is_neither_versioned_nor_unversioned",
    },
    GateDescriptor {
        name: "workspace-tests",
        help: "Enforce workspace-tests contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::workspace_build::tests::workspace_tests_resolves_tested_layer_contract",
    },
];
