//! Gate descriptors for gates starting with H through P.

use super::artifacts::*;
use crate::gate::{GateDescriptor, ResourceClass};

/// Static descriptor array for gates starting with H through P.
pub const GATES_H_P: [GateDescriptor; 62] = [
    GateDescriptor {
        name: "heuristic-audit",
        help: "Enforce heuristic-audit contracts",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::heuristic_audit::tests::a_plain_comment_marker_is_a_finding_at_its_line",
    },
    GateDescriptor {
        name: "host-oracle-elimination",
        help: "Enforce zero production host-oracle / cpu_ref mathematical implementations in shipping crates",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::host_oracle_elimination::tests::mutation_oracle_detection_catches_production_cpu_ref_fn",
    },
    GateDescriptor {
        name: "hot-path-blocking-wait",
        help: "Enforce hot-path-blocking-wait contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::hot_path::tests::blocking_waits_on_dispatch_paths_are_detected",
    },
    GateDescriptor {
        name: "hot-path-inventory",
        help: "Enforce hot-path-inventory contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::inventory_walk::tests::a_walk_on_a_lookup_path_is_reported_with_its_statement",
    },
    GateDescriptor {
        name: "hot-path-nested-rows",
        help: "Enforce hot-path-nested-rows contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::dispatch_surface::tests::a_row_returning_trait_with_no_slot_form_is_reported",
    },
    GateDescriptor {
        name: "hot-path-owned-dispatch",
        help: "Enforce hot-path-owned-dispatch contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::dispatch_surface::tests::a_trait_that_requires_the_owned_form_reports_the_requirement_and_the_copy",
    },
    GateDescriptor {
        name: "hot-path-reserve",
        help: "Enforce hot-path-reserve contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::hot_path::tests::a_reserve_argument_is_read_across_the_whole_statement",
    },
    GateDescriptor {
        name: "hot-path-scan",
        help: "Enforce hot-path-scan contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::hot_path_scan::tests::an_allocation_that_builds_an_error_is_not_measured_but_is_counted",
    },
    GateDescriptor {
        name: "hot-path-unbounded-cache",
        help: "Enforce hot-path-unbounded-cache contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::hot_path::tests::unbounded_cache_constructors_are_flagged",
    },
    GateDescriptor {
        name: "hot-path-unbounded-read",
        help: "Enforce hot-path-unbounded-read contracts",
        package: "xtask",
        areas: &["hot-path"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::hot_path::tests::unbounded_read_to_end_without_take_is_flagged",
    },
    GateDescriptor {
        name: "hygiene-matrix",
        help: "Enforce hygiene-matrix contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[
            "release/evidence/hygiene/hygiene-matrix.json",
            "release/evidence/hygiene/implementation-intake.json",
            "release/evidence/hygiene/threshold-policy.json",
            "release/evidence/hygiene/no-stubs-scan.json",
            "release/evidence/hygiene/no-hidden-fallback-scan.json",
            "release/evidence/hygiene/resource-bound-scan.json",
            "release/evidence/hygiene/error-surface-scan.json",
            "release/evidence/hygiene/cargo-wrapper-scan.json",
        ],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::hygiene_matrix::tests::a_cargo_command_is_a_finding_when_a_comment_tells_a_reader_to_run_it",
    },
    GateDescriptor {
        name: "internal-dep-versions",
        help: "Enforce internal-dep-versions contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml", "Cargo.lock"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::manifest_contract::tests::a_rename_names_the_package_it_points_at",
    },
    GateDescriptor {
        name: "invariant-paths",
        help: "Enforce invariant-paths contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::evidence_paths::tests::a_cited_path_that_is_gitignored_is_reported",
    },
    GateDescriptor {
        name: "launch-state",
        help: "Regenerate release/evidence/final/public-launch-state.json from the launch completion \
        marker and the four prepublish gate artifacts, and report each line the committed \
        artifact disagrees on. Proves the recorded launch state matches the marker on disk, and \
        that each prepublish gate left an artifact carrying no blockers. A launch whose external \
        actions are still pending is recorded and noted, not reported: this gate runs on every \
        tree, and the gate that requires a closed launch is `vyre-release-gate --launch-complete`, \
        which reads this artifact in launch-complete mode. Proves nothing about whether the \
        external actions were really performed: the marker is written by the launch script and \
        this gate reads it, it does not contact crates.io or the git remote.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &["release/evidence/metadata/feature-matrix.json", "release/evidence/metadata/metadata-matrix.json", "release/evidence/package/publish-readiness.json", "release/evidence/version/version-matrix.json"],
        artifacts: &["release/evidence/final/public-launch-state.json"],
        prerequisites: &["feature-matrix", "metadata-matrix", "package-readiness", "version-matrix"],
        resource_class: ResourceClass::Io,
        proof: "crate::release::launch_state::tests::a_pending_launch_is_noted_and_a_missing_prepublish_artifact_is_reported",
    },
    GateDescriptor {
        name: "layering",
        help: "Enforce layering contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::layering::tests::a_neutral_crate_that_reaches_a_backend_api_only_through_a_third_party_crate_is_found",
    },
    GateDescriptor {
        name: "lego-composability",
        help: "Enforce LegoCheck 8: no operation is an island",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::composability::tests::island_operations_are_detected_and_connected_ops_pass",
    },
    GateDescriptor {
        name: "lego-composition-chains",
        help: "Enforce LegoCheck 6: non-leaf ops must have >= 1 child Region",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::composition_chain::tests::non_leaf_operations_without_children_are_flagged",
    },
    GateDescriptor {
        name: "lego-composition-depth",
        help: "Enforce LegoCheck 2: depth-of-composition",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &["Cargo.toml", "Cargo.lock"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::depth_of_composition::tests::below_quarter_composed_tier3_operation_fails_depth_gate",
    },
    GateDescriptor {
        name: "lego-cross-dialect",
        help: "Enforce LegoCheck 4: cross-dialect reach-through",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::cross_dialect::tests::the_substrate_is_an_exempt_target_and_still_an_audited_source",
    },
    GateDescriptor {
        name: "lego-duplicate-report",
        help: "Hold release/evidence/dedup/lego-audit-duplicates.json to the live registry; --write regenerates it",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[crate::artifact_paths::LEGO_AUDIT_DUPLICATES_ARTIFACT],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::duplicates::tests::both_detectors_reach_the_report",
    },
    GateDescriptor {
        name: "lego-exemption-liveness",
        help: "Enforce LegoCheck 0: every exemption is live",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::exemptions::tests::declared_leaf_classification_is_exact",
    },
    GateDescriptor {
        name: "lego-name-stems",
        help: "Enforce LegoCheck 9: name-stem collisions",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::name_stem::tests::leaf_stem_drops_first_underscore_suffix",
    },
    GateDescriptor {
        name: "lego-no-reinvention",
        help: "Enforce LegoCheck 1: no private reimplementation of primitives",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::no_reinvention::tests::ir_duplicate_analysis_judges_exactly_the_operations_that_carry_a_program",
    },
    GateDescriptor {
        name: "lego-operand-shapes",
        help: "Enforce LegoCheck 10: operand-shape duplicate review",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::operand_shape::tests::a_pair_that_agrees_only_where_the_bucket_key_reaches_is_not_a_duplicate",
    },
    GateDescriptor {
        name: "lego-primitive-coverage",
        help: "Enforce LegoCheck 3: primitive adoption coverage",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::primitive_coverage::tests::unregistered_primitive_family_fails_admission",
    },
    GateDescriptor {
        name: "lego-quick",
        help: "Enforce lego-quick contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lego_quick::tests::a_declared_dialect_edge_is_not_a_finding",
    },
    GateDescriptor {
        name: "lego-semantic-organization",
        help: "Enforce LegoCheck 11: semantic organization and file roles",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::semantic_organization::tests::overlapping_file_roles_fails_role_closure",
    },
    GateDescriptor {
        name: "lego-tier-claims",
        help: "Enforce LegoCheck 12: no file claims a tier its placement contradicts",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::tier_claim::tests::every_tier_maps_to_the_prefix_that_derives_it",
    },
    GateDescriptor {
        name: "lego-trend",
        help: "Enforce LegoCheck 7: composition trend ratchet; --write-baseline rewrites audits/lego-composition.tsv",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[crate::artifact_paths::LEGO_COMPOSITION_BASELINE],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::lego_audit::trend::tests::every_intended_collapse_is_also_a_declared_leaf",
    },
    GateDescriptor {
        name: "lint-denied-override",
        help: "Enforce lint-denied-override contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lint_hygiene::tests::a_production_allow_of_a_denied_lint_is_reported_and_an_expect_with_a_reason_is_not",
    },
    GateDescriptor {
        name: "lint-expect-fix",
        help: "Enforce lint-expect-fix contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lint_hygiene::tests::a_production_expect_owes_a_fix_and_a_test_item_does_not",
    },
    GateDescriptor {
        name: "lint-liveness-evasion",
        help: "Enforce lint-liveness-evasion contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lint_hygiene::tests::an_item_only_test_code_calls_is_reported_and_an_owned_one_is_not",
    },
    GateDescriptor {
        name: "lint-one-policy",
        help: "Enforce lint-one-policy contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lint_hygiene::tests::a_member_outside_the_workspace_policy_is_reported_and_an_inheriting_one_is_not",
    },
    GateDescriptor {
        name: "lint-unsafe-budget",
        help: "Enforce lint-unsafe-budget contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lint_hygiene::tests::only_a_real_override_counts_against_the_budget",
    },
    GateDescriptor {
        name: "lint-unsafe-justification",
        help: "Enforce lint-unsafe-justification contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lint_hygiene::tests::a_quoted_unsafe_block_is_data_and_a_real_one_still_needs_its_justification",
    },
    GateDescriptor {
        name: "list-ops",
        help: "Hold docs/generated/op-inventory.toml to the live operation registry; --write regenerates it",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &["docs/generated/op-inventory.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::docs::list_ops::tests::list_ops_renders_canonical_toml_schema",
    },
    GateDescriptor {
        name: "lock-poison-policy",
        help: "Enforce zero unhandled or ad-hoc lock poisoning in production source code",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lock_poison_policy::tests::lock_poison_policy_gate_reports_clean_on_workspace",
    },
    GateDescriptor {
        name: "lockfile-clean",
        help: "Enforce lockfile-clean contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml", "Cargo.lock"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::lockfile::tests::lockfile_findings_detect_porcelain_diff_and_pass_clean",
    },
    GateDescriptor {
        name: "metadata-matrix",
        help: "Regenerate release/evidence/metadata/metadata-matrix.json from every workspace  manifest and report each line the committed artifact disagrees on. Proves every package  declares its license, repository, description, authors, and publish status, that  workspace-inherited metadata is resolved, that the release version is uniform across the  workspace, and that no unreviewed package is marked for publication. Proves nothing about  what is published on crates.io: every fact here is read from this checkout.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &["release/evidence/metadata/metadata-matrix.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::release::metadata_matrix::tests::release_classification_is_vyre_owned",
    },
    GateDescriptor {
        name: "metal-parity",
        help: "Enforce metal-parity contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::metal_parity::tests::a_destination_that_opens_an_option_is_refused",
    },
    GateDescriptor {
        name: "module-layout",
        help: "Enforce module-layout contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::module_layout::tests::a_file_beside_its_own_directory_is_a_finding",
    },
    GateDescriptor {
        name: "neutral-crates",
        help: "Enforce neutral-crates contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::layering::tests::every_backend_word_is_reported_from_the_contract_rather_than_a_sample",
    },
    GateDescriptor {
        name: "op-matrix",
        help: "Hold docs/optimization/OP_MATRIX.toml to the live operation schema; --write regenerates it",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &["docs/optimization/OP_MATRIX.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::docs::op_matrix::validation::tests::an_op_with_no_live_registration_blocks_the_matrix",
    },
    GateDescriptor {
        name: "op-names",
        help: "Enforce op-names contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::op_names::tests::rejects_every_banned_shape_and_accepts_a_canonical_name",
    },
    GateDescriptor {
        name: "operation-law-decisions",
        help: "Enforce every registered semantic operation carries algebraic laws or an explicit recorded absence class",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "xtask_registry::gates::operation_law_decisions::tests::an_operation_without_a_decision_is_reported",
    },
    GateDescriptor {
        name: "operation-schema",
        help: "Hold docs/generated/OP_SCHEMA.json to the live operation registry; --write regenerates it",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &["docs/generated/OP_SCHEMA.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::docs::operation_schema::tests::the_architecture_contract_pins_the_same_operation_schema_version",
    },
    GateDescriptor {
        name: "optimization-corpus",
        help: "Regenerate the five artifacts under release/evidence/optimization from the semantic  Program optimizer corpus and report each line the committed copies disagree on. Proves  the corpus reaches its case floor, that every case verifies after optimization, that at  least one pass instance changed a program, that no case failed to converge, that every  required family carries its minimum case count, that no case id repeats, and that no  optimizer pass id repeats. Proves nothing about runtime performance: the corpus is  optimized and re-verified in process, never executed on a device.",
        package: "xtask-registry",
        areas: &["prepublish", "release-evidence"],
        subject: "registered IR corpus",
        inputs: &[],
        artifacts: &["release/evidence/optimization/optimization-corpus.json", "release/evidence/optimization/optimization-corpus-contracts.json", "release/evidence/optimization/optimization-family-manifest.json", "release/evidence/optimization/optimization-case-manifest.json", "release/evidence/optimization/optimizer-pass-manifest.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::release::optimization_corpus::tests::corpus_completeness_and_hex_encoding_are_exact",
    },
    GateDescriptor {
        name: "optimization-docs",
        help: "Hold docs/generated/optimizer-passes.toml to the live pass registry and supplemental catalog; --write regenerates it",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered optimizer passes",
        inputs: &[],
        artifacts: &["docs/generated/optimizer-passes.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::docs::optimization_docs::tests::a_dropped_supplemental_rule_row_is_reported_missing",
    },
    GateDescriptor {
        name: "optimization-matrix",
        help: "Regenerate release/evidence/optimization/optimization-integration-matrix.json from the  live optimizer pass catalog and report every line the committed artifact disagrees on.  Proves the artifact lists exactly the catalog entries the source registers, that no pass  id repeats, and that every entry names an owner, invariant, proof and benchmark. Proves  nothing about whether a pass is correct, ever fires, or improves anything: the named  proof and benchmark are strings the catalog carries, not results this gate reads.",
        package: "xtask-registry",
        areas: &["prepublish", "release-evidence"],
        subject: "registered IR corpus",
        inputs: &[],
        artifacts: &["release/evidence/optimization/optimization-integration-matrix.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::release::optimization_matrix::tests::optimization_matrix_detects_incomplete_catalog_entries",
    },
    GateDescriptor {
        name: "oracle-sweeps",
        help: "Enforce oracle-sweeps contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::oracle_sweeps::tests::a_sweep_source_names_the_member_directory_that_holds_it",
    },
    GateDescriptor {
        name: "package-readiness",
        help: "Enforce the release package readiness gate across every publishable workspace crate.  Proves all required packages exist, carry matching version declarations, contain only  allowed license tokens, and that archive contents match the published artifact  manifests byte-for-byte. Proves zero unpack errors, zero forbidden file extensions,  and that package sizes stay within declared bandwidth budgets.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "workspace manifests",
        inputs: &["release/evidence/metadata/metadata-matrix.json"],
        artifacts: &["release/evidence/package/publish-readiness.json"],
        prerequisites: &["metadata-matrix"],
        resource_class: ResourceClass::Io,
        proof: "crate::release::package_readiness::archive_contracts::malformed_package_content_evidence_reports_every_failed_invariant",
    },
    GateDescriptor {
        name: "parity-testing-isolated",
        help: "Enforce parity-testing-isolated contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::parity_testing::tests::allows_only_the_declaration_and_a_development_dependency",
    },
    GateDescriptor {
        name: "path-deps-resolve",
        help: "Enforce path-deps-resolve contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml", "Cargo.lock"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::manifest_contract::tests::path_resolution_is_lexical_and_bounded",
    },
    GateDescriptor {
        name: "placement-predicates",
        help: "Enforce placement-predicates contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::placement_predicate::tests::a_shell_left_by_a_departed_member_is_reported",
    },
    GateDescriptor {
        name: "platform-boundary",
        help: "Enforce platform-boundary contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::platform_boundary::tests::finds_consumer_names_in_comments_but_not_identifiers",
    },
    GateDescriptor {
        name: "platform-consumer-docs",
        help: "Enforce platform-consumer-docs contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["docs/optimization/OP_MATRIX.toml", "vyre-lints/rules/release_coordination_docs.txt", "vyre-primitives/README.md"],
        artifacts: &[],
        prerequisites: &["crate-readmes", "op-matrix"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::platform_docs::tests::the_exemption_covers_a_directory_and_a_bare_name",
    },
    GateDescriptor {
        name: "platform-support-matrix",
        help: "Hold docs/generated/platform-support-matrix.toml to the declared host OS, architecture, toolchain, driver, capability, and package feature population; --write regenerates it",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "platform support matrix",
        inputs: &[
            "Cargo.toml",
            ".github/workflows",
            "vyre-foundation/src/platform",
            "vyre-driver/src",
            "vyre-driver-cuda/src",
            "vyre-driver-metal/src",
            "vyre-driver-wgpu/src",
            "vyre-driver-spirv/src",
        ],
        artifacts: &["docs/generated/platform-support-matrix.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::platform_support_matrix::tests::unclaimed_or_missing_cell_fails_gate",
    },
    GateDescriptor {
        name: "print-composition",
        help: "Walk the decomposition chain of every registered operation; --op-id ID narrows to one",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered IR corpus",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::print_composition::tests::empty_region_bodies_are_detected_as_findings",
    },
    GateDescriptor {
        name: "program-wire-fields",
        help: "Enforce program-wire-fields contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::frozen_contract::tests::only_the_program_struct_fields_are_read",
    },
    GateDescriptor {
        name: "proptest-coverage",
        help: "Enforce proptest-coverage contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::proptest_coverage::tests::proptest_marker_detection_and_floor_accounting",
    },
    GateDescriptor {
        name: "public-api-paths",
        help: "Enforce public-api-paths contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["docs/public-api"],
        artifacts: &["xtask/public-api-paths.toml"],
        prerequisites: &["public-api-snapshot"],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::public_api_paths::tests::a_type_reachable_through_two_modules_is_one_duplicate",
    },
    GateDescriptor {
        name: "public-api-snapshot",
        help: "Enforce public-api-snapshot contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml"],
        artifacts: PUBLIC_API_ARTIFACTS,
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::public_api::tests::a_snapshot_for_an_unpublished_package_is_a_finding",
    },
];
