//! Gate descriptors for gates starting with A through G.

use super::artifacts::*;
use crate::gate::{GateDescriptor, ResourceClass};

/// Static descriptor array for gates starting with A through G.
pub const GATES_A_G: [GateDescriptor; 56] = [
    GateDescriptor {
        name: "abstraction-gate",
        help: "Enforce registered building-block boundaries",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::abstraction_gate::tests::a_finding_under_every_nesting_variant_is_reported",
    },
    GateDescriptor {
        name: "application-runnable",
        help: "Enforce whole-application production route and evidence receipts",
        package: "xtask-registry",
        areas: &["prepublish", "conformance"],
        subject: "whole-application execution readiness",
        inputs: &[
            "conform/vyre-conform/tests/connected_graph_conformance.rs",
            "release/evidence/benchmarks/release-workload-matrix.json",
            "release/evidence/conformance/cuda-conformance.json",
            "release/evidence/conformance/reference-conformance.json",
            "release/evidence/conformance/release-all-backends-certificate.json",
            "release/evidence/conformance/wgpu-conformance.json",
            "vyre-bench/tests/application_domain_release_evidence_contracts.rs",
            "vyre-foundation/src/dialect/schema.rs",
            "vyre-foundation/tests/dialect_schema_translation_closure_contracts.rs",
        ],
        artifacts: &["release/evidence/conformance/application-readiness.json"],
        prerequisites: &["release-conformance", "release-workload-matrix"],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::application_runnable::tests::application_runnable_proves_closure_and_receipts",
    },
    GateDescriptor {
        name: "architecture-contract",
        help: "Enforce architecture-contract contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["Cargo.toml", "docs/ARCHITECTURE.md", "docs/CRATE_OWNERSHIP.toml", "docs/DOCS.toml", "docs/generated/OP_SCHEMA.json", "docs/optimization/OWNERSHIP.toml", "release/evidence/backends/backend-matrix.json", "release/release-train.toml"],
        artifacts: &[],
        prerequisites: &["backend-matrix", "operation-schema"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::architecture_contract::tests::a_lane_entry_may_name_a_directory_or_a_directory_glob",
    },
    GateDescriptor {
        name: "backend-extension",
        help: "Enforce backend-extension contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::frozen_contract::tests::a_needle_counts_only_when_its_terminator_follows",
    },
    GateDescriptor {
        name: "backend-matrix",
        help: "Judge the CUDA-first, WGPU-fallback backend policy. Proves, on any host, that every  backend implementation file the policy names exists and carries its implementation  tokens with no unresolved marker left in it, and that no backend production source  states a hidden fallback. Proves, from the recorded probe, that CUDA acquires first,  that the WGPU fallback acquires, that the preferred dispatch backend is never the  reference one, and that the host met the release GPU floor. The probe is only as  current as the run that recorded it; --write re-probes this host and rewrites the  artifact.",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &["release/evidence/backends/backend-matrix.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_evidence::release::backend_matrix::feature_marker_tests::no_feature_marker_names_a_test_file",
    },
    GateDescriptor {
        name: "bench-baselines",
        help: "Enforce bench-baselines contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::bench::tests::every_missing_field_and_every_missing_section_is_reported_at_once",
    },
    GateDescriptor {
        name: "bench-coverage",
        help: "Enforce bench-coverage contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered benchmark cases",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::bench::tests::every_measured_dimension_is_judged_against_the_registry",
    },
    GateDescriptor {
        name: "bench-crossback",
        help: "Cross-validate every speedup cell across the three measured backend comparison  matrices. Proves every measured cell records positive speedup, is strictly reproducible  from its source probe, cites no placeholder, and is traceable back to its host, commit,  GPU model, driver version, and measurement timestamp. Proves nothing about benchmark  methodology: this gate reads the produced matrices and their source artifacts, never  starts a benchmark run. Run with --write to re-derive the markdown summary table.",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &["release/evidence/benchmarks/cross-backend-comparison.md"],
        prerequisites: &[],
        resource_class: ResourceClass::Device,
        proof: "xtask_evidence::bench::bench_crossback::tests::a_measurement_missing_any_provenance_field_is_a_finding",
    },
    GateDescriptor {
        name: "bench-release",
        help: "Judge the recorded release benchmark evidence across CUDA, WGPU, and CPU reference baselines.  Proves all 42 required release benchmark cases exist, passed on the recorded release host,  and achieved measured throughput and latency at or above the release floor. Proves zero  failed cases, zero unexplained regressions from the baseline, and that the recorded run  reached the required sample count. It measures nothing; regenerate the owned artifacts  with release-benchmarks before running this comparison gate.",
        package: "xtask-evidence",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Device,
        proof: "xtask_evidence::bench::bench_release::tests::bench_release_rejects_case_backend_drift_under_cuda_axes",
    },
    GateDescriptor {
        name: "bench-smoke-runtime",
        help: "Enforce bench-smoke-runtime contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::bench::tests::the_smoke_budget_comes_from_the_manifest",
    },
    GateDescriptor {
        name: "catalog",
        help: "Hold docs/generated/catalog.toml to the live operation inventory; --write regenerates it",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &["docs/generated/catalog.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::docs::catalog::tests::catalog_renders_subsystems_and_extracts_subsystem_names",
    },
    GateDescriptor {
        name: "change-closure",
        help: "Enforce versioned symbol-level IR change-closure across all enum types and variants",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "symbol-level IR change-closure",
        inputs: &["vyre-spec/src", "vyre-foundation/src", "vyre-primitives/src", "docs/public-api"],
        artifacts: &["docs/generated/change-closure.toml"],
        prerequisites: &["public-api-snapshot"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::change_closure::tests::adding_unrecorded_variant_fails_closure",
    },
    GateDescriptor {
        name: "check-tier-deps",
        help: "Enforce check-tier-deps contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml", "Cargo.lock"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::check_tier_deps::dependency_kind_tests::production_upward_workspace_inherited_dependency_fails",
    },
    GateDescriptor {
        name: "ci-concurrency",
        help: "Enforce ci-concurrency contracts",
        package: "xtask",
        areas: &["ci-rules"],
        subject: "ci workflows",
        inputs: &[".github/workflows"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::ci_contract::tests::a_job_scoped_concurrency_key_is_not_the_workflow_group",
    },
    GateDescriptor {
        name: "ci-matrix",
        help: "Enforce ci-matrix contracts",
        package: "xtask",
        areas: &["ci-rules"],
        subject: "ci workflows",
        inputs: &[".github/workflows"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::ci_contract::tests::only_a_matrix_axis_value_counts",
    },
    GateDescriptor {
        name: "ci-registry",
        help: "Enforce ci-registry contracts",
        package: "xtask",
        areas: &["ci-rules"],
        subject: "ci workflows",
        inputs: &[".github/workflows", ".github/workflows-paused"],
        artifacts: &["xtask/ci-registry.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::ci_registry::tests::a_row_and_a_gate_that_do_not_pair_up_both_fail",
    },
    GateDescriptor {
        name: "ci-required",
        help: "Enforce ci-required contracts",
        package: "xtask",
        areas: &["ci-rules"],
        subject: "ci workflows",
        inputs: &[".github/workflows"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::ci_contract::tests::a_fan_in_job_that_ignores_its_dependency_results_is_reported",
    },
    GateDescriptor {
        name: "ci-shell",
        help: "Enforce ci-shell contracts",
        package: "xtask",
        areas: &["ci-rules"],
        subject: "ci workflows",
        inputs: &[".github/workflows"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::ci_contract::tests::a_step_declares_no_shell_when_no_key_at_its_depth_does",
    },
    GateDescriptor {
        name: "ci-steps",
        help: "Enforce ci-steps contracts",
        package: "xtask",
        areas: &["ci-rules"],
        subject: "ci workflows",
        inputs: &[".github/workflows", ".github/workflows-paused"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::ci_steps::tests::a_matrix_expression_is_not_a_selector_the_tree_can_refuse",
    },
    GateDescriptor {
        name: "cli-docs",
        help: "Enforce cli-docs contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["docs/CLI.toml", "vyre/README.md", "xtask/README.md"],
        artifacts: &[],
        prerequisites: &["crate-readmes"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::docs::cli_docs::tests::every_row_defect_is_its_own_finding",
    },
    GateDescriptor {
        name: "codeowners",
        help: "Generate .github/CODEOWNERS from docs/PROTECTED_BOUNDARIES.toml and report \
        every way the protection surface has drifted from it: a second CODEOWNERS at a \
        location GitHub reads first, a pattern matching no tracked path, a boundary naming a \
        package that moved, a workspace member with no protection decision recorded, the \
        manifest or generator failing to protect itself, and a branch-protection payload that \
        stops requiring the code-owner review. Proves nothing about GitHub's live \
        configuration: the API is not reached, so the script that applies the protection is \
        what is judged.",
        package: "xtask",
        areas: &["contract-rules", "prepublish"],
        subject: "workspace members",
        inputs: &["docs/PROTECTED_BOUNDARIES.toml", "scripts/apply-branch-protection.sh", "Cargo.toml"],
        artifacts: &[".github/CODEOWNERS"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::codeowners::tests::a_protection_payload_that_stops_requiring_the_owner_review_is_reported",
    },
    GateDescriptor {
        name: "compile",
        help: "Lower a registered operation or an IR file to a target representation, verify the output against the target compiler (ptxas for PTX, spirv-val for SPIR-V, metal for MSL), and report binary size and register count; --op-id ID selects one operation, --file PATH selects an IR file, --target NAME (cuda, metal, wgpu, spirv, ptx) selects the backend",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::compile::tests::linked_target_compiler_emits_authenticated_payload",
    },
    GateDescriptor {
        name: "configuration-model",
        help: "Generate typed configuration space model from Cargo metadata, target predicates, backend capabilities, publication classes, and declared incompatibilities; proves satisfiability and isolated covering set closure",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "workspace configuration space",
        inputs: &["Cargo.toml"],
        artifacts: &["docs/generated/configuration-space.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::configuration_model::tests::configuration_space_model_is_satisfiable_and_deterministic",
    },
    GateDescriptor {
        name: "conformance-matrix",
        help: "Regenerate release/evidence/conformance/conformance-matrix.json from the live conformance suite across every registered operation and report each line the committed artifact disagrees on. Proves every registered operation has a conformance test, that all four backends achieve identical numeric results within declared precision bounds, that ULP drift stays below the gate ceiling, that no unsupported op is marked passing, and that every unsupported reason matches an approved class. Proves nothing about device execution: runs against the local host.",
        package: "xtask-registry",
        areas: &["prepublish", "release-evidence"],
        subject: "release evidence matrices",
        inputs: &["docs/optimization/OP_MATRIX.toml", "release/evidence/conformance/cuda-conformance.json", "release/evidence/conformance/reference-conformance.json", "release/evidence/conformance/wgpu-conformance.json"],
        artifacts: &["release/evidence/conformance/conformance-matrix.json"],
        prerequisites: &["op-matrix", "release-conformance"],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::release::conformance_matrix::case_classes::tests::release_backend_case_rows_block_non_supported_rows_without_unsupported_evidence",
    },
    GateDescriptor {
        name: "consumer-compilation",
        help: "Compile every out-of-workspace consumer package",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "out-of-workspace consumer packages",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "crate::gates::consumer_compilation::tests::finds_compile_failure_in_consumer",
    },
    GateDescriptor {
        name: "contract-in-source",
        help: "Enforce contract-in-source contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::doc_contract::tests::a_path_in_code_is_not_a_deferral",
    },
    GateDescriptor {
        name: "crate-ownership",
        help: "Enforce crate-ownership contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &["docs/CRATE_GRAPH.md", "docs/OWNERSHIP.md"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::crate_registry::tests::inherited_and_local_features_are_unioned",
    },
    GateDescriptor {
        name: "crate-pages",
        help: "Enforce crate-pages contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["Cargo.toml", "vyre/README.md"],
        artifacts: &[],
        prerequisites: &["crate-readmes"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::crate_pages::tests::an_empty_exclusion_section_is_reported",
    },
    GateDescriptor {
        name: "crate-readmes",
        help: "Enforce crate-readmes contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["Cargo.toml", "docs/CRATE_GUIDES.toml", "docs/CRATE_OWNERSHIP.toml", "release/release-train.toml"],
        artifacts: &[
            "conform/vyre-conform-spec/README.md",
            "conform/vyre-conform/README.md",
            "structure-gate/README.md",
            "vyre-alloc-probe/README.md",
            "vyre-aot/README.md",
            "vyre-bench/README.md",
            "vyre-debug/README.md",
            "vyre-driver-cuda/README.md",
            "vyre-driver-metal/README.md",
            "vyre-driver-reference/README.md",
            "vyre-driver-spirv/README.md",
            "vyre-driver-wgpu/README.md",
            "vyre-driver/README.md",
            "vyre-emit-metal/README.md",
            "vyre-emit-naga/README.md",
            "vyre-emit-ptx/README.md",
            "vyre-emit-spirv/README.md",
            "vyre-foundation/README.md",
            "vyre-libs-analysis/README.md",
            "vyre-libs-bitset/README.md",
            "vyre-libs-builder/README.md",
            "vyre-libs-decode/README.md",
            "vyre-libs-device/README.md",
            "vyre-libs-encoding/README.md",
            "vyre-libs-fixpoint/README.md",
            "vyre-libs-graph/README.md",
            "vyre-libs-hash/README.md",
            "vyre-libs-math/README.md",
            "vyre-libs-nn/README.md",
            "vyre-libs-parsing/README.md",
            "vyre-libs-pattern/README.md",
            "vyre-libs-reasoning/README.md",
            "vyre-libs-reduce/README.md",
            "vyre-libs-rule/README.md",
            "vyre-libs-scheduling/README.md",
            "vyre-libs-security/README.md",
            "vyre-libs-solvers/README.md",
            "vyre-libs-text/README.md",
            "vyre-libs-vfs/README.md",
            "vyre-libs-visual/README.md",
            "vyre-libs/README.md",
            "vyre-lints/README.md",
            "vyre-lower/README.md",
            "vyre-macros/README.md",
            "vyre-megakernel/README.md",
            "vyre-pass-engine/README.md",
            "vyre-primitives/README.md",
            "vyre-reference/README.md",
            "vyre-registry-link/README.md",
            "vyre-runtime/README.md",
            "vyre-safetensors/README.md",
            "vyre-spec/README.md",
            "vyre-test-support/README.md",
            "vyre/README.md",
            "xtask-evidence/README.md",
            "xtask-registry/README.md",
            "xtask/README.md",
        ],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::crate_readmes::tests::an_unbalanced_marker_pair_is_a_finding",
    },
    GateDescriptor {
        name: "cross-target",
        help: "Check that the workspace compiles cleanly for every non-host release target (aarch64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-pc-windows-msvc) through the workspace build wrapper; reports the first error per target",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::cross_target::tests::a_failure_with_no_error_line_still_names_itself",
    },
    GateDescriptor {
        name: "cuda-parity",
        help: "Enforce cuda-parity contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::backend_parity::tests::a_support_module_is_not_a_test_target",
    },
    GateDescriptor {
        name: "dep-drift",
        help: "Enforce dep-drift contracts",
        package: "xtask",
        areas: &["prepublish"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml", "Cargo.lock"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::dep_drift::tests::dep_drift_detects_mismatched_dependency_versions_and_ignores_workspace_inheritance",
    },
    GateDescriptor {
        name: "device-test-compilation",
        help: "Compile every device-tests admitted test target without running it",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "workspace test targets",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::device_test_compilation::tests::diagnostic_to_finding_formats_message_and_fix",
    },
    GateDescriptor {
        name: "device-test-gating",
        help: "Enforce device-test-gating contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "rust sources",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::device_test_gating::tests::a_per_test_device_cfg_admits_that_test_and_not_its_neighbour",
    },
    GateDescriptor {
        name: "dialect-lowering",
        help: "Enforce that a declared composition registers a program builder",
        package: "xtask-registry",
        areas: &["lego-audit"],
        subject: "registered dialect operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::dialect_lowering::tests::a_composable_operation_without_a_builder_is_reported",
    },
    GateDescriptor {
        name: "doc-claims",
        help: "Enforce doc-claims contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["contracts/doc_claims_manifest.toml", "vyre-driver-wgpu/CONFIG.md", "vyre-primitives/README.md", "vyre-driver-cuda/src/lib.rs"],
        artifacts: &[],
        prerequisites: &["crate-readmes"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::doc_contract::tests::only_a_published_document_path_is_a_deferral",
    },
    GateDescriptor {
        name: "docs-check",
        help: "Enforce docs-check contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["docs/DOCS.toml", "docs/CRATE_GRAPH.md", "docs/OWNERSHIP.md", "docs/testing"],
        artifacts: &["docs/SUMMARY.md", "docs/INDEX.md"],
        prerequisites: &["crate-ownership", "testing-guides"],
        resource_class: ResourceClass::Io,
        proof: "crate::docs::docs_check::tests::every_authority_and_lifecycle_drift_is_reported",
    },
    GateDescriptor {
        name: "docs-coupling",
        help: "Enforce docs-coupling contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["docs/DOCS.toml", "docs/ARCHITECTURE.md"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::docs::docs_coupling::tests::an_unreachable_base_ref_is_a_finding_and_not_a_crash",
    },
    GateDescriptor {
        name: "docs-references",
        help: "Enforce docs-references contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["docs/DOCS.toml", "docs/INDEX.md", "docs/SUMMARY.md", "docs/CRATE_GRAPH.md", "docs/OWNERSHIP.md", "docs/testing", "vyre/README.md"],
        artifacts: &[],
        prerequisites: &["crate-ownership", "crate-readmes", "docs-check", "testing-guides"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::docs_references::tests::a_single_backtick_span_is_read_and_a_double_one_is_not",
    },
    GateDescriptor {
        name: "docs-register",
        help: "Enforce docs-register contracts",
        package: "xtask",
        areas: &["docs"],
        subject: "owned documentation pages",
        inputs: &["docs/REGISTER.toml", "docs/DOCS.toml", "cargo_full", ".cargo/config.toml"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::docs::docs_register::tests::a_root_page_row_naming_no_page_is_reported",
    },
    GateDescriptor {
        name: "dup-scan",
        help: "Enforce dup-scan contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &["xtask/dup-baseline.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::dup_scan::tests::the_report_names_the_file_a_copy_was_made_from",
    },
    GateDescriptor {
        name: "engineering-scorecard",
        help: "Generate and enforce the all-axis engineering scorecard dynamically from live registries",
        package: "xtask",
        areas: &["release-evidence"],
        subject: "all-axis engineering scorecard",
        inputs: &["Cargo.toml", "docs/public-api", "docs/testing", "xtask/gate-baselines.toml"],
        artifacts: &["docs/generated/engineering-scorecard.toml"],
        prerequisites: &["public-api-snapshot", "testing-guides"],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::scorecard::tests::newly_added_crate_dynamically_appears_in_scorecard",
    },
    GateDescriptor {
        name: "error-codes",
        help: "Hold docs/generated/driver-error-codes.toml and docs/generated/error-codes.toml to the live driver and validation inventories; --write regenerates them",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "driver and validation error codes",
        inputs: &[],
        artifacts: &[
            "docs/generated/driver-error-codes.toml",
            "docs/generated/error-codes.toml",
        ],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::docs::error_codes::tests::each_catalog_uses_the_renderer_of_the_crate_that_owns_it",
    },
    GateDescriptor {
        name: "evidence-attribution",
        help: "Hold every release/evidence artifact to a complete provenance record; --write regenerates the ledger of the ones whose origin is unknown",
        package: "xtask",
        areas: &["contract-rules", "release-evidence"],
        subject: "release evidence artifacts",
        inputs: &["release/evidence"],
        artifacts: &["release/evidence/metadata/unattributed-evidence.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::evidence_attribution::tests::a_host_reproducible_artifact_with_no_record_is_a_finding",
    },
    GateDescriptor {
        name: "evidence-paths",
        help: "Enforce evidence-paths contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::evidence_paths::tests::a_citation_that_does_not_resolve_is_reported",
    },
    GateDescriptor {
        name: "evidence-provenance",
        help: "Enforce evidence-provenance contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "committed release evidence",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::evidence_provenance::tests::an_artifact_recorded_before_a_source_change_its_own_commit_carries_is_a_finding",
    },
    GateDescriptor {
        name: "example-capability",
        help: "Enforce example-capability contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::example_capability::tests::an_unknown_placeholder_is_named",
    },
    GateDescriptor {
        name: "feature-isolation",
        help: "Enforce feature-isolation contracts",
        package: "xtask",
        areas: &["prepublish"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &["xtask/feature-isolation.toml"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::feature_isolation::tests::a_recorded_outcome_that_disagrees_with_the_build_is_reported_both_ways",
    },
    GateDescriptor {
        name: "feature-matrix",
        help: "Regenerate release/evidence/metadata/feature-matrix.json from every workspace manifest  and report each line the committed artifact disagrees on. Proves every feature table  parses, every feature member resolves to a local feature, an optional dependency or a  dependency feature, every package that declares features declares a default policy, the  three release packages exist with empty defaults, and that vyre, vyre-driver-cuda and  vyre-driver-wgpu declare their release features. Proves nothing about whether any  feature selection compiles: that is feature-isolation.",
        package: "xtask",
        areas: &["prepublish", "release-evidence"],
        subject: "workspace manifests",
        inputs: &[],
        artifacts: &["release/evidence/metadata/feature-matrix.json"],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::release::feature_matrix::tests::unresolved_feature_members_and_release_policy_are_enforced",
    },
    GateDescriptor {
        name: "feature-msrv",
        help: "Enforce feature-msrv contracts",
        package: "xtask",
        areas: &["prepublish"],
        subject: "workspace manifests",
        inputs: &["Cargo.toml"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::feature_msrv::tests::the_finding_carries_the_compiler_error",
    },
    GateDescriptor {
        name: "file-size",
        help: "Enforce file-size contracts",
        package: "xtask",
        areas: &["prepublish"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::file_size::tests::measured_rows_grant_no_headroom",
    },
    GateDescriptor {
        name: "frozen-contracts",
        help: "Enforce frozen-contracts contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: FROZEN_CONTRACT_ARTIFACTS,
        prerequisites: &[],
        resource_class: ResourceClass::Io,
        proof: "crate::gates::frozen_contract::tests::a_snapshot_no_contract_claims_is_reported",
    },
    GateDescriptor {
        name: "gate-canon",
        help: "Enforce gate-canon contracts",
        package: "xtask",
        areas: &["prepublish"],
        subject: "registered system invariants",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::gate_canon::tests::a_row_with_nonzero_findings_fails_to_load",
    },
    GateDescriptor {
        name: "gate-dag",
        help: "Enforce DAG schema consistency, acyclicity, and prerequisite closure across all registered gates",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "registered gate DAG",
        inputs: &["xtask/src/gate.rs", "xtask/src/gate_metadata/mod.rs", "xtask/src/gate_dag.rs"],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gate_dag::tests::dag_validation_detects_cycles_and_missing_prerequisites",
    },
    GateDescriptor {
        name: "gate1",
        help: "Enforce Gate 1: loops <= 4 AND nodes <= 200 OR composed_fraction >= 60%",
        package: "xtask-registry",
        areas: &["prepublish"],
        subject: "registered operations",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Process,
        proof: "xtask_registry::gates::gate1::tests::the_finding_names_the_inline_work_it_collected",
    },
    GateDescriptor {
        name: "gpu-loudness",
        help: "Enforce gpu-loudness contracts",
        package: "xtask",
        areas: &["contract-rules"],
        subject: "tracked source files",
        inputs: &[],
        artifacts: &[],
        prerequisites: &[],
        resource_class: ResourceClass::Cpu,
        proof: "crate::gates::gpu_loudness::tests::a_loud_abort_covers_any_shape",
    },
];
