//! All-axis engineering scorecard generated dynamically from live workspace registries.
//!
//! Evaluates the 22 engineering axes across every workspace crate dynamically discovered
//! through `structure_gate::workspace_members`. Adding a crate to the workspace automatically
//! includes it in the generated scorecard without editing any scorecard code.

use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

use crate::artifact_gate::{settle_inspection, Inspection};
use crate::gate::{GateBehavior, GateCtx, GateError, Report};
use crate::gate_metadata::GATE_METADATA;

mod evidence;

const SCORECARD_SCHEMA_VERSION: u32 = 2;

/// Path of the canonical engineering scorecard artifact.
pub const SCORECARD_PATH: &str = "docs/generated/engineering-scorecard.toml";

/// The 22 canonical engineering axes.
pub const ENGINEERING_AXES: &[&str] = &[
    "semantic_correctness",
    "numerical_legality",
    "schedule_resource_legality",
    "frontier_performance",
    "interactive_latency_jitter",
    "compile_runtime_scalability",
    "deterministic_reproducibility",
    "reliability_recovery",
    "hostile_input_safety",
    "dependency_provenance",
    "configuration_closure",
    "schema_authority",
    "tenant_isolation",
    "version_skew_behavior",
    "backend_host_portability",
    "api_semver_stability",
    "package_install_usability",
    "diagnostics_causal_introspection",
    "code_cohesion_maintainability",
    "documentation_coherence",
    "ir_generality",
    "verification_strength",
];

/// The engineering scorecard gate.
pub struct ScorecardGate;

impl GateBehavior for ScorecardGate {
    fn run(&self, ctx: &GateCtx) -> Result<Report, GateError> {
        let scorecard = generate_scorecard(&ctx.root)?;
        let rendered = render_scorecard(&scorecard)?;

        let mut inspection = Inspection::new();
        inspection.generates_document_text(SCORECARD_PATH, rendered);

        let mut report = settle_inspection(ctx, ctx.gate_name()?, inspection);
        report.note(format!(
            "Scorecard evaluated across {} crate(s) and {} engineering axes (overall: {})",
            scorecard.crates.len(),
            ENGINEERING_AXES.len(),
            scorecard.summary.overall_verdict
        ));
        if let Some(reason) = &scorecard.summary.qualification_reason {
            report.note(format!("Qualification not established: {reason}"));
        }
        Ok(report)
    }
}

/// Scorecard summary metadata.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct ScorecardSummary {
    /// Total number of workspace crates evaluated.
    pub total_crates: usize,
    /// Total number of registered gates in the suite.
    pub total_gates: usize,
    /// Total number of engineering axes evaluated.
    pub evaluated_axes: usize,
    /// Overall qualification verdict.
    pub overall_verdict: String,
    /// Reason independent qualification could not be established.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub qualification_reason: Option<String>,
}

/// Scorecard entry for one workspace crate.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct CrateScorecard {
    /// Crate package name.
    pub name: String,
    /// Workspace-relative directory path.
    pub path: String,
    /// Architecture tier classification.
    pub tier: String,
    /// Number of exported public API symbols.
    pub public_api_symbols: usize,
    /// Whether a testing guide markdown exists in `docs/testing/`.
    pub testing_guide_present: bool,
    /// Number of gates that inspect or cover this crate.
    pub gate_count: usize,
    /// Number of passed engineering axes.
    pub axes_passed: usize,
    /// Total number of engineering axes.
    pub axes_total: usize,
    /// Qualification status.
    pub status: String,
}

/// The complete engineering scorecard document.
#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
#[serde(deny_unknown_fields)]
pub struct EngineeringScorecard {
    /// Schema version.
    #[serde(deserialize_with = "deserialize_schema_version")]
    pub schema_version: u32,
    /// Summary section.
    pub summary: ScorecardSummary,
    /// Evaluation per crate.
    #[serde(rename = "crate")]
    pub crates: Vec<CrateScorecard>,
}

/// Render the scorecard into canonical TOML.
///
/// # Errors
///
/// Returns an error if the scorecard cannot be serialized.
pub fn render_scorecard(scorecard: &EngineeringScorecard) -> Result<String, GateError> {
    let body = toml::to_string(scorecard).map_err(|error| {
        GateError::new(
            format!("cannot serialize engineering scorecard: {error}"),
            "check the scorecard field values",
        )
    })?;
    Ok(format!(
        "# Generated by `cargo xtask engineering-scorecard --write`.\n\
         # Registry counts are inventory, not qualification evidence.\n\
         # Qualification requires the registered policy and independent authenticated measurements.\n{body}"
    ))
}

fn deserialize_schema_version<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<u32, D::Error> {
    let version = u32::deserialize(deserializer)?;
    if version != SCORECARD_SCHEMA_VERSION {
        return Err(serde::de::Error::custom("unsupported engineering scorecard schema; regenerate with engineering-scorecard --write"));
    }
    Ok(version)
}

/// Generate the engineering scorecard dynamically from live registries.
///
/// # Errors
///
/// Returns `GateError` if workspace manifests cannot be read.
pub fn generate_scorecard(root: &Path) -> Result<EngineeringScorecard, GateError> {
    let members = structure_gate::workspace_members(root);
    let mut crate_scores = Vec::with_capacity(members.len());

    let public_api_dir = root.join("docs/public-api");
    let testing_dir = root.join("docs/testing");

    for member_path in &members {
        let member_dir = root.join(member_path);
        let manifest_path = member_dir.join("Cargo.toml");
        let manifest_text = fs::read_to_string(&manifest_path).map_err(|e| {
            GateError::new(
                format!("cannot read `{}`: {e}", manifest_path.display()),
                "ensure all workspace member Cargo.toml files exist",
            )
        })?;

        let table: toml::Table = toml::from_str(&manifest_text).map_err(|e| {
            GateError::new(
                format!("cannot parse `{}`: {e}", manifest_path.display()),
                "fix Cargo.toml syntax",
            )
        })?;

        let package_name = table
            .get("package")
            .and_then(|p| p.get("name"))
            .and_then(|n| n.as_str())
            .unwrap_or(member_path)
            .to_string();

        let api_file = public_api_dir.join(format!("{package_name}.txt"));
        let public_api_symbols = if api_file.exists() {
            fs::read_to_string(&api_file)
                .map(|s| s.lines().filter(|l| !l.trim().is_empty()).count())
                .unwrap_or(0)
        } else {
            0
        };

        let guide_file = testing_dir.join(format!("{package_name}.md"));
        let testing_guide_present = guide_file.exists();

        let gate_count = count_covering_gates(&package_name, member_path);

        let tier = classify_tier(&package_name);
        let axes_total = ENGINEERING_AXES.len();
        // Inventory does not establish any axis. Evidence is assessed after
        // the complete live package set has been collected.
        let axes_passed = 0;

        let status = "unqualified".to_string();

        crate_scores.push(CrateScorecard {
            name: package_name,
            path: member_path.clone(),
            tier,
            public_api_symbols,
            testing_guide_present,
            gate_count,
            axes_passed,
            axes_total,
            status,
        });
    }

    crate_scores.sort_by(|a, b| a.name.cmp(&b.name));

    let packages: Vec<_> = crate_scores
        .iter()
        .map(|entry| entry.name.clone())
        .collect();
    let assessment = evidence::assess(root, &packages);
    for entry in &mut crate_scores {
        entry.axes_passed = assessment.passed.get(&entry.name).copied().unwrap_or(0);
        entry.status = if entry.axes_passed == entry.axes_total {
            "qualified".to_string()
        } else {
            "unqualified".to_string()
        };
    }

    let all_qualified =
        !crate_scores.is_empty() && crate_scores.iter().all(|c| c.status == "qualified");

    Ok(EngineeringScorecard {
        schema_version: SCORECARD_SCHEMA_VERSION,
        summary: ScorecardSummary {
            total_crates: crate_scores.len(),
            total_gates: GATE_METADATA.len(),
            evaluated_axes: ENGINEERING_AXES.len(),
            overall_verdict: if all_qualified {
                "qualified".to_string()
            } else {
                "unqualified".to_string()
            },
            qualification_reason: assessment.reason,
        },
        crates: crate_scores,
    })
}

fn classify_tier(package: &str) -> String {
    if package == "vyre" || package.starts_with("vyre-foundation") || package == "vyre-spec" {
        "core".to_string()
    } else if package.starts_with("vyre-driver") {
        "driver".to_string()
    } else if package.starts_with("vyre-emit") {
        "emitter".to_string()
    } else if package.starts_with("xtask") || package == "structure-gate" {
        "tooling".to_string()
    } else if package.contains("conform") {
        "conformance".to_string()
    } else {
        "middleware".to_string()
    }
}

fn count_covering_gates(package: &str, member_path: &str) -> usize {
    let mut count = 0;
    for d in GATE_METADATA {
        if d.package == package
            || d.inputs
                .iter()
                .any(|i| i.contains(member_path) || i.contains(package))
            || d.artifacts.iter().any(|a| a.contains(package))
            || d.proof.contains(package)
            || d.proof.contains(&package.replace('-', "_"))
        {
            count += 1;
        }
    }
    count
}

#[cfg(test)]
mod tests {
    use super::*;

    /// WHY: a newly added crate must appear in the scorecard dynamically.
    #[test]
    fn newly_added_crate_dynamically_appears_in_scorecard() {
        let root = structure_gate::workspace_root();
        let scorecard = generate_scorecard(&root).expect("Scorecard generation should succeed");

        let members = structure_gate::workspace_members(&root);
        assert_eq!(
            scorecard.crates.len(),
            members.len(),
            "Scorecard crate count must match dynamic workspace_members exactly"
        );

        for member in &members {
            assert!(
                scorecard.crates.iter().any(|c| c.path == *member),
                "Crate `{member}` must be present in dynamic scorecard"
            );
        }
    }

    /// WHY: an unknown package has no declared gate coverage.
    #[test]
    fn an_unregistered_package_has_no_invented_gate_coverage() {
        assert_eq!(
            count_covering_gates(
                "unregistered-scorecard-contract-fixture",
                "unregistered-scorecard-contract-fixture",
            ),
            0,
        );
    }

    #[test]
    fn engineering_scorecard_evaluates_all_22_axes() {
        assert_eq!(
            ENGINEERING_AXES.len(),
            22,
            "the scorecard declares exactly 22 engineering axes"
        );

        let root = structure_gate::workspace_root();
        let scorecard = generate_scorecard(&root).expect("Scorecard generation should succeed");
        assert_eq!(scorecard.summary.evaluated_axes, 22);
        for c in &scorecard.crates {
            assert_eq!(c.axes_total, 22);
        }
    }

    fn unqualified_fixture() -> EngineeringScorecard {
        let root = tempfile::tempdir().unwrap();
        std::fs::create_dir(root.path().join("fixture")).unwrap();
        std::fs::write(
            root.path().join("fixture/Cargo.toml"),
            "[package]\nname = \"fixture\"\nversion = \"0.1.0\"\n",
        )
        .unwrap();
        std::fs::write(
            root.path().join("Cargo.toml"),
            "[workspace]\nmembers = [\"fixture\"]\n",
        )
        .unwrap();
        std::fs::create_dir_all(root.path().join("docs/public-api")).unwrap();
        std::fs::create_dir_all(root.path().join("docs/testing")).unwrap();
        std::fs::write(
            root.path().join("docs/public-api/fixture.txt"),
            "pub fn fixture()\n",
        )
        .unwrap();
        std::fs::write(
            root.path().join("docs/testing/fixture.md"),
            "Fixture tests\n",
        )
        .unwrap();
        generate_scorecard(root.path()).unwrap()
    }

    /// WHY: populated inventory cannot manufacture qualification.
    #[test]
    fn inventory_without_evidence_never_qualifies() {
        let scorecard = unqualified_fixture();
        assert_eq!(scorecard.crates.len(), 1);
        assert_eq!(scorecard.crates[0].public_api_symbols, 1);
        assert!(scorecard.crates[0].testing_guide_present);
        assert_eq!(scorecard.crates[0].axes_passed, 0);
        assert_eq!(scorecard.crates[0].status, "unqualified");
        assert_eq!(scorecard.summary.overall_verdict, "unqualified");
    }

    /// WHY: an empty registry must not qualify through a vacuous all() result.
    #[test]
    fn empty_workspace_never_qualifies() {
        let root = tempfile::tempdir().unwrap();
        std::fs::write(
            root.path().join("Cargo.toml"),
            "[workspace]\nmembers = []\n",
        )
        .unwrap();
        assert_eq!(
            generate_scorecard(root.path())
                .unwrap()
                .summary
                .overall_verdict,
            "unqualified"
        );
    }

    /// WHY: version-one documents contain unevaluated passing claims.
    #[test]
    fn scorecard_roundtrip_rejects_the_preceding_schema() {
        let scorecard = unqualified_fixture();
        let rendered = render_scorecard(&scorecard).unwrap();
        assert_eq!(
            toml::from_str::<EngineeringScorecard>(&rendered).unwrap(),
            scorecard
        );
        let mut stale: toml::Table = toml::from_str(&rendered).unwrap();
        stale.insert("schema_version".into(), toml::Value::Integer(1));
        assert!(toml::from_str::<EngineeringScorecard>(&toml::to_string(&stale).unwrap()).is_err());
    }

    /// WHY: a generating gate owes both halves of its contract, so a sweep that
    /// runs after its own regeneration finds nothing left to report.
    #[test]
    fn engineering_scorecard_gate_runs_and_generates() {
        crate::gate::assert_regenerates_clean("engineering-scorecard");
    }
}
