//! Typed external-resource schemas, datasets, AOT bundle manifests, and ingestion transactions.
//!
//! The contract defines a bounded typed-resource ingestion transaction that maps
//! files, byte ranges, generated data, or caller memory into artifact value ids
//! through concrete-driver transfers, verifying identity, dtype, element count,
//! access, generation, and lifetime before any allocation becomes dispatch-visible.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use thiserror::Error;
use vyre_driver::Resource;
use vyre_foundation::ir::DataType;
use vyre_megakernel::{AbiAccess, ArtifactValueId, Digest, ResourceLifetime};

/// Source of data for a typed resource ingestion.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ResourceDataSource {
    /// In-memory byte buffer provided by the caller.
    Memory(Vec<u8>),
    /// A file path, byte offset, and exact byte length.
    File {
        /// Path to the data file.
        path: PathBuf,
        /// Byte offset within the file.
        offset: u64,
        /// Length in bytes.
        length: u64,
    },
    /// A bounded byte range within an identified source.
    ByteRange {
        /// Canonical source identity.
        source_id: Digest,
        /// Byte offset within the source.
        offset: u64,
        /// Length in bytes.
        length: u64,
        /// In-memory byte payload.
        bytes: Vec<u8>,
    },
    /// Deterministically generated bytes.
    Generated(GeneratedDataSource),
    /// Pre-allocated device-resident resource (immutable reuse).
    Resident(Resource),
}

/// Deterministic data generation specification.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum GeneratedDataSource {
    /// Repeated byte pattern.
    Pattern {
        /// Fill byte.
        fill: u8,
        /// Total byte length.
        length: usize,
    },
    /// Zero-filled buffer.
    Zeroed(usize),
    /// Deterministic custom generated buffer with a descriptive name.
    Custom {
        /// Descriptive name.
        name: String,
        /// Expected length in bytes.
        length: usize,
        /// Byte payload.
        bytes: Vec<u8>,
    },
}

impl ResourceDataSource {
    /// In-memory byte buffer.
    #[must_use]
    pub fn memory(bytes: impl Into<Vec<u8>>) -> Self {
        Self::Memory(bytes.into())
    }

    /// File slice with exact byte offset and length.
    #[must_use]
    pub fn file(path: impl Into<PathBuf>, offset: u64, length: u64) -> Self {
        Self::File {
            path: path.into(),
            offset,
            length,
        }
    }

    /// Byte range with an associated source identity.
    #[must_use]
    pub fn byte_range(
        source_id: Digest,
        offset: u64,
        length: u64,
        bytes: impl Into<Vec<u8>>,
    ) -> Self {
        Self::ByteRange {
            source_id,
            offset,
            length,
            bytes: bytes.into(),
        }
    }

    /// Repeated byte fill pattern.
    #[must_use]
    pub fn pattern(fill: u8, length: usize) -> Self {
        Self::Generated(GeneratedDataSource::Pattern { fill, length })
    }

    /// Zero-filled byte buffer of the requested length.
    #[must_use]
    pub fn zeroed(length: usize) -> Self {
        Self::Generated(GeneratedDataSource::Zeroed(length))
    }

    /// Pre-allocated device resident buffer.
    #[must_use]
    pub fn resident(resource: Resource) -> Self {
        Self::Resident(resource)
    }

    /// Read or generate the payload bytes for transfer to device.
    ///
    /// For [`ResourceDataSource::Resident`], returns `None` as the resource
    /// is already resident on device.
    pub fn fetch_bytes(&self) -> Result<Option<Vec<u8>>, ResourceIngestionError> {
        match self {
            Self::Memory(bytes) => Ok(Some(bytes.clone())),
            Self::File {
                path,
                offset,
                length,
            } => {
                let mut file =
                    std::fs::File::open(path).map_err(|err| ResourceIngestionError::Io {
                        path: path.display().to_string(),
                        error: err.to_string(),
                    })?;
                use std::io::{Read, Seek, SeekFrom};
                file.seek(SeekFrom::Start(*offset))
                    .map_err(|err| ResourceIngestionError::Io {
                        path: path.display().to_string(),
                        error: err.to_string(),
                    })?;
                let mut buf = vec![0u8; *length as usize];
                file.read_exact(&mut buf)
                    .map_err(|err| ResourceIngestionError::Io {
                        path: path.display().to_string(),
                        error: err.to_string(),
                    })?;
                Ok(Some(buf))
            }
            Self::ByteRange { bytes, length, .. } => {
                if bytes.len() != *length as usize {
                    return Err(ResourceIngestionError::DataLengthMismatch {
                        expected: *length,
                        actual: bytes.len() as u64,
                    });
                }
                Ok(Some(bytes.clone()))
            }
            Self::Generated(gen) => match gen {
                GeneratedDataSource::Pattern { fill, length } => Ok(Some(vec![*fill; *length])),
                GeneratedDataSource::Zeroed(length) => Ok(Some(vec![0u8; *length])),
                GeneratedDataSource::Custom { bytes, length, .. } => {
                    if bytes.len() != *length {
                        return Err(ResourceIngestionError::DataLengthMismatch {
                            expected: *length as u64,
                            actual: bytes.len() as u64,
                        });
                    }
                    Ok(Some(bytes.clone()))
                }
            },
            Self::Resident(_) => Ok(None),
        }
    }

    /// Expected byte length without necessarily reading the entire file.
    #[must_use]
    pub fn byte_len(&self) -> Option<u64> {
        match self {
            Self::Memory(bytes) => Some(bytes.len() as u64),
            Self::File { length, .. } => Some(*length),
            Self::ByteRange { length, .. } => Some(*length),
            Self::Generated(GeneratedDataSource::Pattern { length, .. })
            | Self::Generated(GeneratedDataSource::Zeroed(length))
            | Self::Generated(GeneratedDataSource::Custom { length, .. }) => Some(*length as u64),
            Self::Resident(_) => None,
        }
    }
}

/// One typed resource specification associating an artifact value id with its data source and schema.
#[derive(Clone, Debug, PartialEq, Eq)]
pub struct TypedResource {
    /// Canonical artifact value identity.
    pub value: ArtifactValueId,
    /// Data source.
    pub source: ResourceDataSource,
    /// Expected data type.
    pub dtype: Option<DataType>,
    /// Expected logical element count.
    pub element_count: Option<u64>,
    /// Expected semantic lifetime.
    pub lifetime: Option<ResourceLifetime>,
    /// Expected ABI access permissions.
    pub access: Option<AbiAccess>,
    /// Expected device generation.
    pub generation: Option<u64>,
    /// Expected content digest.
    pub identity: Option<Digest>,
}

impl TypedResource {
    /// Construct a new typed resource with the given value id and data source.
    #[must_use]
    pub fn new(value: ArtifactValueId, source: ResourceDataSource) -> Self {
        Self {
            value,
            source,
            dtype: None,
            element_count: None,
            lifetime: None,
            access: None,
            generation: None,
            identity: None,
        }
    }

    /// In-memory byte buffer resource.
    #[must_use]
    pub fn memory(value: ArtifactValueId, bytes: impl Into<Vec<u8>>) -> Self {
        Self::new(value, ResourceDataSource::memory(bytes))
    }

    /// File slice resource.
    #[must_use]
    pub fn file(
        value: ArtifactValueId,
        path: impl Into<PathBuf>,
        offset: u64,
        length: u64,
    ) -> Self {
        Self::new(value, ResourceDataSource::file(path, offset, length))
    }

    /// Byte range resource.
    #[must_use]
    pub fn byte_range(
        value: ArtifactValueId,
        source_id: Digest,
        offset: u64,
        length: u64,
        bytes: impl Into<Vec<u8>>,
    ) -> Self {
        Self::new(
            value,
            ResourceDataSource::byte_range(source_id, offset, length, bytes),
        )
    }

    /// Repeated byte pattern resource.
    #[must_use]
    pub fn pattern(value: ArtifactValueId, fill: u8, length: usize) -> Self {
        Self::new(value, ResourceDataSource::pattern(fill, length))
    }

    /// Zero-filled buffer resource.
    #[must_use]
    pub fn zeroed(value: ArtifactValueId, length: usize) -> Self {
        Self::new(value, ResourceDataSource::zeroed(length))
    }

    /// Pre-allocated resident buffer resource (immutable reuse).
    #[must_use]
    pub fn resident(value: ArtifactValueId, resource: Resource) -> Self {
        Self::new(value, ResourceDataSource::resident(resource))
    }

    /// Specify expected data type.
    #[must_use]
    pub fn with_dtype(mut self, dtype: DataType) -> Self {
        self.dtype = Some(dtype);
        self
    }

    /// Specify expected element count.
    #[must_use]
    pub fn with_element_count(mut self, element_count: u64) -> Self {
        self.element_count = Some(element_count);
        self
    }

    /// Specify expected resource lifetime.
    #[must_use]
    pub fn with_lifetime(mut self, lifetime: ResourceLifetime) -> Self {
        self.lifetime = Some(lifetime);
        self
    }

    /// Specify expected ABI access permissions.
    #[must_use]
    pub fn with_access(mut self, access: AbiAccess) -> Self {
        self.access = Some(access);
        self
    }

    /// Specify expected device generation.
    #[must_use]
    pub fn with_generation(mut self, generation: u64) -> Self {
        self.generation = Some(generation);
        self
    }

    /// Specify expected content digest.
    #[must_use]
    pub fn with_identity(mut self, identity: Digest) -> Self {
        self.identity = Some(identity);
        self
    }
}

/// A collection of typed resources prepared for ingestion against an artifact ABI.
#[derive(Clone, Debug, Default, PartialEq, Eq)]
pub struct TypedResourceDataset {
    resources: BTreeMap<ArtifactValueId, TypedResource>,
}

impl TypedResourceDataset {
    /// Create an empty dataset.
    #[must_use]
    pub fn new() -> Self {
        Self {
            resources: BTreeMap::new(),
        }
    }

    /// Insert one typed resource, failing if a conflicting resource for the same value already exists.
    pub fn insert(&mut self, resource: TypedResource) -> Result<(), ResourceIngestionError> {
        if let Some(existing) = self.resources.get(&resource.value) {
            if existing != &resource {
                return Err(ResourceIngestionError::DuplicateConflictingResource {
                    value: resource.value,
                });
            }
        }
        self.resources.insert(resource.value, resource);
        Ok(())
    }

    /// Chain builder to insert one typed resource.
    #[must_use]
    pub fn with_resource(mut self, resource: TypedResource) -> Self {
        self.resources.insert(resource.value, resource);
        self
    }

    /// Helper to add an in-memory byte buffer.
    pub fn add_memory(&mut self, value: ArtifactValueId, bytes: impl Into<Vec<u8>>) -> &mut Self {
        self.resources
            .insert(value, TypedResource::memory(value, bytes));
        self
    }

    /// Helper to add a pre-allocated resident resource.
    pub fn add_resident(&mut self, value: ArtifactValueId, resource: Resource) -> &mut Self {
        self.resources
            .insert(value, TypedResource::resident(value, resource));
        self
    }

    /// Look up a typed resource by its canonical value identity.
    #[must_use]
    pub fn get(&self, value: ArtifactValueId) -> Option<&TypedResource> {
        self.resources.get(&value)
    }

    /// Total number of resources in the dataset.
    #[must_use]
    pub fn len(&self) -> usize {
        self.resources.len()
    }

    /// Whether the dataset is empty.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.resources.is_empty()
    }

    /// Iterator over value identities and their typed resources.
    pub fn iter(&self) -> impl Iterator<Item = (&ArtifactValueId, &TypedResource)> {
        self.resources.iter()
    }

    /// Iterator over typed resources.
    pub fn values(&self) -> impl Iterator<Item = &TypedResource> {
        self.resources.values()
    }

    /// Construct a dataset from an iterator of typed resources.
    pub fn from_resources(
        resources: impl IntoIterator<Item = TypedResource>,
    ) -> Result<Self, ResourceIngestionError> {
        let mut dataset = Self::new();
        for res in resources {
            dataset.insert(res)?;
        }
        Ok(dataset)
    }

    /// Construct a dataset from an AOT resource manifest.
    pub fn from_manifest(manifest: &ResourceManifest) -> Result<Self, ResourceIngestionError> {
        manifest.to_dataset()
    }

    /// Construct a dataset from an AOT resource manifest relative to a base directory.
    pub fn from_manifest_with_base_dir(
        manifest: &ResourceManifest,
        base_dir: &Path,
    ) -> Result<Self, ResourceIngestionError> {
        manifest.to_dataset_with_base_dir(base_dir)
    }
}

/// Serialized AOT bundle resource manifest describing external resources for an artifact.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceManifest {
    /// Manifest schema version.
    pub schema_version: u32,
    /// Canonical artifact digest this manifest targets, if bound to a specific compile.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub artifact_digest: Option<Digest>,
    /// Manifest resource entries.
    pub entries: Vec<ResourceManifestEntry>,
}

/// One external resource entry in an AOT bundle manifest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct ResourceManifestEntry {
    /// Canonical artifact value identity.
    pub value: ArtifactValueId,
    /// Optional human-readable resource name.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Element data type.
    pub dtype: DataType,
    /// Logical element count.
    pub element_count: u64,
    /// Byte count.
    pub byte_count: u64,
    /// Semantic lifetime class.
    pub lifetime: ResourceLifetime,
    /// Required ABI access.
    pub access: AbiAccess,
    /// External data source.
    pub source: ResourceManifestSource,
    /// Optional content checksum / digest.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub identity: Option<Digest>,
}

/// External data source in an AOT bundle manifest.
#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ResourceManifestSource {
    /// File path with offset and length.
    File {
        /// Relative or absolute path.
        path: String,
        /// Byte offset in file.
        offset: u64,
        /// Byte count.
        length: u64,
    },
    /// Inline byte buffer.
    InlineBytes {
        /// Raw bytes.
        bytes: Vec<u8>,
    },
    /// Zero-filled buffer.
    Zeroed {
        /// Byte count.
        byte_count: u64,
    },
    /// Repeated byte pattern.
    Pattern {
        /// Fill byte.
        fill: u8,
        /// Byte count.
        byte_count: u64,
    },
}

impl ResourceManifest {
    /// Current manifest schema version.
    pub const CURRENT_SCHEMA_VERSION: u32 = 1;

    /// Create a new resource manifest.
    #[must_use]
    pub fn new(artifact_digest: Option<Digest>, entries: Vec<ResourceManifestEntry>) -> Self {
        Self {
            schema_version: Self::CURRENT_SCHEMA_VERSION,
            artifact_digest,
            entries,
        }
    }

    /// Serialize manifest to JSON bytes.
    pub fn to_bytes(&self) -> Result<Vec<u8>, serde_json::Error> {
        serde_json::to_vec(self)
    }

    /// Deserialize manifest from JSON bytes.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self, serde_json::Error> {
        serde_json::from_slice(bytes)
    }

    /// Convert to a typed resource dataset using current working directory for relative paths.
    pub fn to_dataset(&self) -> Result<TypedResourceDataset, ResourceIngestionError> {
        self.to_dataset_with_base_dir(Path::new("."))
    }

    /// Convert to a typed resource dataset using the provided base directory for relative paths.
    pub fn to_dataset_with_base_dir(
        &self,
        base_dir: &Path,
    ) -> Result<TypedResourceDataset, ResourceIngestionError> {
        let mut dataset = TypedResourceDataset::new();
        for entry in &self.entries {
            let source = match &entry.source {
                ResourceManifestSource::File {
                    path,
                    offset,
                    length,
                } => {
                    let full_path = if Path::new(path).is_absolute() {
                        PathBuf::from(path)
                    } else {
                        base_dir.join(path)
                    };
                    ResourceDataSource::file(full_path, *offset, *length)
                }
                ResourceManifestSource::InlineBytes { bytes } => {
                    ResourceDataSource::memory(bytes.clone())
                }
                ResourceManifestSource::Zeroed { byte_count } => {
                    ResourceDataSource::zeroed(*byte_count as usize)
                }
                ResourceManifestSource::Pattern { fill, byte_count } => {
                    ResourceDataSource::pattern(*fill, *byte_count as usize)
                }
            };
            let mut tr = TypedResource::new(entry.value, source)
                .with_dtype(entry.dtype.clone())
                .with_element_count(entry.element_count)
                .with_lifetime(entry.lifetime)
                .with_access(entry.access);
            if let Some(id) = entry.identity {
                tr = tr.with_identity(id);
            }
            dataset.insert(tr)?;
        }
        Ok(dataset)
    }
}

/// Errors occurring during typed resource validation and ingestion transactions.
#[derive(Clone, Debug, PartialEq, Eq, Error)]
pub enum ResourceIngestionError {
    /// Missing required resource for an artifact entry point.
    #[error("dataset missing required resource `{resource_name}` for canonical value {} (required by entry `{entry_name}`). Fix: supply a TypedResource for `{resource_name}` in the ingestion dataset.", value.0)]
    MissingResource {
        /// Value identity.
        value: ArtifactValueId,
        /// Stable graph value name the artifact resource set records, or the
        /// sentence stating that the set records none. A caller binds by name,
        /// so a value number alone leaves it comparing integers it never chose.
        resource_name: String,
        /// Entry point name requiring this resource.
        entry_name: String,
    },
    /// Caller supplied a resource for an artifact-owned workspace value.
    #[error("canonical value {} is workspace-owned; bind the artifact workspace and drop it from caller dataset. Fix: allocate an ArtifactWorkspace and omit workspace-owned value {0} from caller dataset.", value.0)]
    WorkspaceOwnedCollision {
        /// Value identity.
        value: ArtifactValueId,
    },
    /// Unknown canonical value not declared in the artifact ABI.
    #[error("unknown canonical value {} not declared in artifact ABI. Fix: supply resources matching the artifact's declared canonical value identities.", value.0)]
    UnknownValue {
        /// Value identity.
        value: ArtifactValueId,
    },
    /// Data type mismatch against artifact ABI.
    #[error("typed resource schema mismatch for value {}: expected dtype {expected:?}, got {actual:?}. Fix: match the artifact ABI data type for value {0}.", value.0)]
    DtypeMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected ABI data type.
        expected: DataType,
        /// Actual supplied data type.
        actual: DataType,
    },
    /// Element count mismatch against artifact ABI.
    #[error("typed resource element count mismatch for value {}: expected {expected}, got {actual}. Fix: provide the exact element count declared by the artifact ABI for value {0}.", value.0)]
    ElementCountMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected element count.
        expected: u64,
        /// Actual element count.
        actual: u64,
    },
    /// Byte count mismatch against artifact ABI.
    #[error("typed resource byte count mismatch for value {}: expected {expected}, got {actual}. Fix: provide the exact byte count declared by the artifact ABI for value {0}.", value.0)]
    ByteCountMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected byte count.
        expected: u64,
        /// Actual byte count.
        actual: u64,
    },
    /// Lifetime mismatch against artifact ABI.
    #[error("typed resource lifetime mismatch for value {}: expected {expected:?}, got {actual:?}. Fix: match the artifact ABI lifetime for value {0}.", value.0)]
    LifetimeMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected lifetime.
        expected: ResourceLifetime,
        /// Actual lifetime.
        actual: ResourceLifetime,
    },
    /// Access permission mismatch against artifact ABI.
    #[error("typed resource access mismatch for value {}: expected {expected:?}, got {actual:?}. Fix: match the artifact ABI access permissions for value {0}.", value.0)]
    AccessMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected access.
        expected: AbiAccess,
        /// Actual access.
        actual: AbiAccess,
    },
    /// Generation mismatch against active device.
    #[error("typed resource generation mismatch for value {}: expected device generation {expected}, got {actual}. Fix: re-ingest resources on the current active device generation.", value.0)]
    GenerationMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected device generation.
        expected: u64,
        /// Actual supplied generation.
        actual: u64,
    },
    /// Content identity digest mismatch.
    #[error("typed resource identity mismatch for value {}: expected digest {expected:?}, got {actual:?}. Fix: supply data whose content matches the expected digest.", value.0)]
    IdentityMismatch {
        /// Value identity.
        value: ArtifactValueId,
        /// Expected digest.
        expected: Digest,
        /// Actual digest.
        actual: Digest,
    },
    /// Duplicate conflicting resource for the same canonical value.
    #[error("duplicate conflicting typed resource for value {}. Fix: provide exactly one resource specification per canonical value.", value.0)]
    DuplicateConflictingResource {
        /// Value identity.
        value: ArtifactValueId,
    },
    /// I/O error reading external file data.
    #[error("failed to read resource file `{path}`: {error}. Fix: ensure the resource file exists and is readable at the specified path and byte range.")]
    Io {
        /// File path.
        path: String,
        /// Error message.
        error: String,
    },
    /// Payload length mismatch between data source declaration and data buffer.
    #[error("resource data source length mismatch: expected {expected} bytes, got {actual} bytes. Fix: ensure data source length matches buffer byte count.")]
    DataLengthMismatch {
        /// Expected length.
        expected: u64,
        /// Actual length.
        actual: u64,
    },
    /// Concrete driver allocation failed.
    #[error("driver allocation failed for value {}: {error}. Fix: check device memory budget and retry with smaller resident allocations.", value.0)]
    AllocationFailed {
        /// Value identity.
        value: ArtifactValueId,
        /// Error message.
        error: String,
    },
    /// Resource resolution reached a non-resident entry that phase one left unprepared.
    #[error("no prepared payload for canonical value {} at resource resolution. Fix: prepare a payload for every non-resident dataset entry before resolving resources.", value.0)]
    PayloadNotPrepared {
        /// Value identity.
        value: ArtifactValueId,
    },
    /// Concrete driver upload failed.
    #[error("driver upload failed for value {}: {error}. Fix: verify device connectivity and retry upload.", value.0)]
    UploadFailed {
        /// Value identity.
        value: ArtifactValueId,
        /// Error message.
        error: String,
    },
}
