use super::{
    GraphCsrSkewedQueuePrepared, QUEUE_ACTIVE_QUEUE_INDEX, QUEUE_EDGE_KIND_INDEX,
    QUEUE_EDGE_OFFSETS_INDEX, QUEUE_EDGE_TARGETS_INDEX, QUEUE_FRONTIER_IN_INDEX,
    QUEUE_FRONTIER_OUT_INDEX, QUEUE_HIGH_LEN_INDEX, QUEUE_HIGH_QUEUE_INDEX, QUEUE_LEN_INDEX,
    QUEUE_RESET_GRID,
};

const QUEUE_RESET_RESOURCE_INDICES: [usize; 1] = [QUEUE_LEN_INDEX];
const QUEUE_HIGH_RESET_RESOURCE_INDICES: [usize; 1] = [QUEUE_HIGH_LEN_INDEX];
const QUEUE_BUILD_RESOURCE_INDICES: [usize; 4] = [
    QUEUE_FRONTIER_IN_INDEX,
    QUEUE_ACTIVE_QUEUE_INDEX,
    QUEUE_LEN_INDEX,
    QUEUE_FRONTIER_OUT_INDEX,
];
const QUEUE_TRAVERSE_RESOURCE_INDICES: [usize; 6] = [
    QUEUE_ACTIVE_QUEUE_INDEX,
    QUEUE_LEN_INDEX,
    QUEUE_EDGE_OFFSETS_INDEX,
    QUEUE_EDGE_TARGETS_INDEX,
    QUEUE_EDGE_KIND_INDEX,
    QUEUE_FRONTIER_OUT_INDEX,
];
const QUEUE_SPLIT_LOW_RESOURCE_INDICES: [usize; 8] = [
    QUEUE_ACTIVE_QUEUE_INDEX,
    QUEUE_LEN_INDEX,
    QUEUE_EDGE_OFFSETS_INDEX,
    QUEUE_EDGE_TARGETS_INDEX,
    QUEUE_EDGE_KIND_INDEX,
    QUEUE_FRONTIER_OUT_INDEX,
    QUEUE_HIGH_QUEUE_INDEX,
    QUEUE_HIGH_LEN_INDEX,
];
const QUEUE_HIGH_TRAVERSE_RESOURCE_INDICES: [usize; 6] = [
    QUEUE_HIGH_QUEUE_INDEX,
    QUEUE_HIGH_LEN_INDEX,
    QUEUE_EDGE_OFFSETS_INDEX,
    QUEUE_EDGE_TARGETS_INDEX,
    QUEUE_EDGE_KIND_INDEX,
    QUEUE_FRONTIER_OUT_INDEX,
];

crate::cases::queue_stage::define_resident_queue_sequence_dispatch!(
    pub(super) dispatch_resident_queue_sequence,
    GraphCsrSkewedQueuePrepared,
    "skewed CSR"
);

crate::cases::queue_stage::define_host_queue_sequence_dispatch!(
    pub(super) dispatch_host_queue_sequence,
    GraphCsrSkewedQueuePrepared,
    "skewed CSR"
);
