//! The release workload families the release plan requires.
//!
//! One row per proof workload. The table is the declaration a release reads;
//! matching benchmark cases against it happens in the parent module.

/// One release workload family and how a benchmark case is matched to it.
pub(super) struct ReleaseWorkloadFamily {
    pub(super) id: &'static str,
    pub(super) title: &'static str,
    pub(super) release_plan_workload: u8,
    pub(super) required: bool,
    pub(super) any_terms: &'static [&'static str],
    pub(super) all_terms: &'static [&'static str],
    pub(super) bench_target_id: &'static str,
    pub(super) dispatch_policy: &'static str,
    pub(super) requires_cpu_sota_baseline: bool,
    pub(super) non_megakernel_justification: Option<&'static str>,
}

/// Every release workload family, in release-plan order.
pub(super) const RELEASE_WORKLOADS: &[ReleaseWorkloadFamily] = &[
    ReleaseWorkloadFamily {
        id: "condition-eval",
        title: "Bytecode-compatible condition evaluation",
        release_plan_workload: 1,
        required: true,
        any_terms: &["release.condition_eval", "conditions.yara_like"],
        all_terms: &["condition"],
        bench_target_id: "release.workload.condition_eval",
        requires_cpu_sota_baseline: true,
        dispatch_policy: "megakernel",
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "string-bitmap-scatter",
        title: "String bitmap scatter",
        release_plan_workload: 2,
        required: true,
        any_terms: &["release.string_bitmap_scatter"],
        all_terms: &["string", "bitmap"],
        bench_target_id: "release.workload.string_bitmap_scatter",
        requires_cpu_sota_baseline: true,
        dispatch_policy: "megakernel",
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "offset-count-aggregation",
        title: "Offset/count/length aggregation",
        release_plan_workload: 3,
        required: true,
        any_terms: &["release.offset_count_aggregation"],
        all_terms: &["release.offset_count_aggregation"],
        bench_target_id: "release.workload.offset_count_aggregation",
        dispatch_policy: "megakernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "metadata-conditions",
        title: "PE/header/file metadata condition evaluation",
        release_plan_workload: 4,
        required: true,
        any_terms: &["metadata.condition"],
        all_terms: &["metadata.condition"],
        bench_target_id: "release.workload.pe_metadata",
        dispatch_policy: "megakernel",
        non_megakernel_justification: None,
        requires_cpu_sota_baseline: true,
    },
    ReleaseWorkloadFamily {
        id: "entropy-window",
        title: "Entropy/window predicates",
        release_plan_workload: 5,
        required: true,
        any_terms: &["release.entropy_window"],
        all_terms: &["release.entropy_window"],
        bench_target_id: "release.workload.entropy_window",
        dispatch_policy: "megakernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "quantified-condition-loops",
        title: "Bounded quantified condition loops",
        release_plan_workload: 6,
        required: true,
        any_terms: &["release.quantified_condition_loops"],
        all_terms: &["quantifier", "condition"],
        bench_target_id: "release.workload.for_any_all_n",
        dispatch_policy: "megakernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "alias-reaching-def",
        title: "Alias-aware reaching-definition predicates",
        release_plan_workload: 7,
        required: true,
        any_terms: &["release.alias_reaching_def", "dataflow.reaching_def.bitset"],
        all_terms: &["alias"],
        bench_target_id: "release.workload.alias_reaching_def",
        dispatch_policy: "specialized-dataflow-kernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: alias-aware reaching-definition workloads use sparse relation kernels with fixpoint convergence rather than independent condition-slot dispatch",
        ),
    },
    ReleaseWorkloadFamily {
        id: "ifds-witness",
        title: "IFDS reachability and witness predicates",
        release_plan_workload: 8,
        required: true,
        any_terms: &["release.ifds_witness", "dataflow.ifds"],
        all_terms: &["ifds", "witness"],
        bench_target_id: "release.workload.ifds_witness",
        dispatch_policy: "specialized-dataflow-kernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: IFDS witness extraction uses frontier/fact-table scheduling and predecessor reconstruction that need dataflow-specific kernels",
        ),
    },
    ReleaseWorkloadFamily {
        id: "ast-motif-traversal",
        title: "AST-shaped node motif predicate traversal",
        release_plan_workload: 9,
        required: true,
        any_terms: &["release.ast_motif_traversal"],
        all_terms: &["release.ast_motif_traversal"],
        bench_target_id: "release.workload.ast_motif_traversal",
        dispatch_policy: "single-kernel-count",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: AST motif traversal evaluates node-kind, depth and motif predicates over table-shaped node columns, which is a single counting pass rather than a queued rule opcode stream",
        ),
    },
    ReleaseWorkloadFamily {
        id: "megakernel-queued-batches",
        title: "Persistent megakernel queued condition batches",
        release_plan_workload: 10,
        required: true,
        any_terms: &["release.megakernel_queue", "runtime.megakernel.condition"],
        all_terms: &["megakernel", "queue"],
        bench_target_id: "release.workload.megakernel_stream",
        dispatch_policy: "megakernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "semantic-optimizer-impact",
        title: "Canonical semantic optimizer impact",
        release_plan_workload: 11,
        required: true,
        any_terms: &["foundation.optimizer.impact", "optimizer"],
        all_terms: &[],
        bench_target_id: "release.optimization.foundation_optimizer_impact",
        dispatch_policy: "canonical-program-optimizer",
        requires_cpu_sota_baseline: false,
        non_megakernel_justification: Some(
            "architectural: semantic optimization executes before verified lowering and target materialization",
        ),
    },
    ReleaseWorkloadFamily {
        id: "sparse-output-compaction",
        title: "Sparse fired-rule readback and output compaction",
        release_plan_workload: 12,
        required: true,
        any_terms: &["sparse.compaction", "sparse_output"],
        all_terms: &["sparse"],
        bench_target_id: "release.workload.conformance_sparse_readback",
        dispatch_policy: "megakernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: None,
    },
    ReleaseWorkloadFamily {
        id: "callgraph-reachability",
        title: "Graph traversal and callgraph reachability",
        release_plan_workload: 13,
        required: true,
        any_terms: &["callgraph.reachability", "graph.reachability"],
        all_terms: &["reachability"],
        bench_target_id: "release.workload.callgraph_reachability",
        dispatch_policy: "specialized-graph-kernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: callgraph reachability is frontier graph traversal with convergence state, not independent rule-condition slot evaluation",
        ),
    },
    ReleaseWorkloadFamily {
        id: "compound-fused-filter",
        title: "Compound resident literal/dataflow/score filtering",
        release_plan_workload: 14,
        required: false,
        any_terms: &["compound.pipeline.fused_filter", "compound"],
        all_terms: &["resident", "dataflow"],
        bench_target_id: "release.workload.compound_fused_filter",
        dispatch_policy: "resident-fused-kernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: compound filtering fuses independent matching, dataflow, score, and taint-class predicates into one resident pass without condition-slot queue orchestration",
        ),
    },
    ReleaseWorkloadFamily {
        id: "adaptive-routing",
        title: "GPU-resident adaptive workload routing",
        release_plan_workload: 15,
        required: false,
        any_terms: &["runtime.adaptive_routing", "adaptive-routing"],
        all_terms: &["resident", "scheduler"],
        bench_target_id: "release.workload.adaptive_routing",
        dispatch_policy: "resident-routing-kernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: adaptive routing is GPU-side scheduling metadata generation rather than execution of a queued rule opcode stream",
        ),
    },
    ReleaseWorkloadFamily {
        id: "quantized-linear",
        title: "Fused grouped INT4 linear inference",
        release_plan_workload: 16,
        required: false,
        any_terms: &["nn.linear_4bit_affine_grouped", "quantized"],
        all_terms: &["resident", "inference"],
        bench_target_id: "release.workload.quantized_linear",
        dispatch_policy: "resident-fused-kernel",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: grouped INT4 linear fuses packed weight decode, scale/zero-point sidecars, and accumulation in one inference kernel instead of queueing scalar condition opcodes",
        ),
    },
    ReleaseWorkloadFamily {
        id: "egraph-saturation",
        title: "Rewrite-equivalence saturation predicates",
        release_plan_workload: 17,
        // Carries the tenth CPU-SOTA 100x contract, so the release depends on it.
        required: true,
        any_terms: &["release.egraph_saturation", "egraph"],
        all_terms: &["optimization", "rewrite"],
        bench_target_id: "release.workload.egraph_saturation",
        dispatch_policy: "single-kernel-count",
        requires_cpu_sota_baseline: true,
        non_megakernel_justification: Some(
            "architectural: rewrite-equivalence saturation evaluates independent opcode and class-membership predicates in one counting pass rather than queueing a rule opcode stream",
        ),
    },
];
