//! Integration contracts for the registered gate DAG.
//!
//! Enforces that the registered gate DAG is acyclic, closed over prerequisites,
//! and that every declared prerequisite corresponds to an artifact-to-input relation.

use xtask::gate::{GateBehavior, GateCtx};
use xtask::gate_dag::{DagError, GateDag};
use xtask::gate_metadata::{descriptor_by_name, GATE_METADATA};
use xtask::gates::gate_dag_gate::GateDagGate;

/// WHY: Section 182 requires the gate DAG to be a complete acyclic ordering over all registered gates.
#[test]
fn gate_dag_topological_order_is_complete_and_acyclic() {
    let dag = GateDag::from_descriptors(GATE_METADATA)
        .expect("live GATE_METADATA must construct a valid DAG");
    let order = dag
        .topological_order()
        .expect("topological sort over live GATE_METADATA must succeed");

    assert_eq!(
        order.len(),
        GATE_METADATA.len(),
        "topological sort must include every registered gate"
    );

    // Verify ordering: for each gate, every prerequisite must appear earlier in the order.
    for (idx, &gate_name) in order.iter().enumerate() {
        let node = dag.get(gate_name).expect("node must exist");
        for prereq in &node.prerequisites {
            let prereq_idx = order
                .iter()
                .position(|&name| name == *prereq)
                .expect("prerequisite must be present in topological order");
            assert!(
                prereq_idx < idx,
                "prerequisite `{prereq}` must precede `{gate_name}` in topological order"
            );
        }
    }
}

/// WHY: Section 182 requires live GATE_METADATA to pass full DAG validation with zero failures.
#[test]
fn gate_dag_validation_is_clean_on_live_metadata() {
    let dag = GateDag::from_descriptors(GATE_METADATA)
        .expect("live GATE_METADATA must construct a valid DAG");
    let root = xtask::checkout::checkout_root();
    let failures = dag.validate(&root);
    assert!(
        failures.is_empty(),
        "DAG validation reported unexpected failures: {failures:?}"
    );
}

/// WHY: Section 182 requires detecting missing prerequisites when an input is regenerated by another gate.
#[test]
fn gate_dag_detects_missing_prerequisite() {
    let mut descriptors = GATE_METADATA.to_vec();
    let arch_idx = descriptors
        .iter()
        .position(|d| d.name == "architecture-contract")
        .expect("architecture-contract must exist");

    // Remove backend-matrix prerequisite from architecture-contract
    let mut modified = descriptors[arch_idx];
    modified.prerequisites = &["operation-schema"];
    descriptors[arch_idx] = modified;

    let dag = GateDag::from_descriptors(&descriptors).expect("DAG should construct");
    let root = xtask::checkout::checkout_root();
    let failures = dag.validate(&root);

    assert!(
        failures.iter().any(|f| f.contains("architecture-contract")
            && f.contains("backend-matrix")
            && f.contains("does not declare `backend-matrix` as a prerequisite")),
        "DAG validation must fail when a required prerequisite is omitted: {failures:?}"
    );
}

/// WHY: Section 182 requires rejecting unjustified prerequisites that have no artifact-to-input relation.
#[test]
fn gate_dag_detects_unjustified_prerequisite() {
    let mut descriptors = GATE_METADATA.to_vec();
    let arch_idx = descriptors
        .iter()
        .position(|d| d.name == "architecture-contract")
        .expect("architecture-contract must exist");

    // Add unjustified prerequisite on gate-dag to architecture-contract
    let mut modified = descriptors[arch_idx];
    modified.prerequisites = &["backend-matrix", "gate-dag", "operation-schema"];
    descriptors[arch_idx] = modified;

    let dag = GateDag::from_descriptors(&descriptors).expect("DAG should construct");
    let root = xtask::checkout::checkout_root();
    let failures = dag.validate(&root);

    assert!(
        failures.iter().any(|f| f.contains("architecture-contract")
            && f.contains("gate-dag")
            && f.contains("produces no artifact matching any declared input")),
        "DAG validation must reject unjustified prerequisites: {failures:?}"
    );
}

/// WHY: Section 182 requires detecting dependency cycles during DAG construction.
#[test]
fn gate_dag_detects_dependency_cycle() {
    let mut descriptors = GATE_METADATA.to_vec();
    let bm_idx = descriptors
        .iter()
        .position(|d| d.name == "backend-matrix")
        .expect("backend-matrix must exist");

    // Add architecture-contract as prerequisite of backend-matrix, creating a 2-node cycle
    let mut modified = descriptors[bm_idx];
    modified.prerequisites = &["architecture-contract"];
    descriptors[bm_idx] = modified;

    let res = GateDag::from_descriptors(&descriptors);
    assert!(
        res.is_err(),
        "constructing a DAG with a cycle must return an error"
    );
    assert!(
        matches!(res.unwrap_err(), DagError::DependencyCycle { .. }),
        "error must be DagError::DependencyCycle"
    );
}

/// WHY: Section 182 requires GateDagGate to record complete subject coverage and zero findings.
#[test]
fn gate_dag_gate_reports_complete_coverage() {
    let root = xtask::checkout::checkout_root();
    let ctx = GateCtx::new(root, Vec::new());
    let report = GateDagGate.run(&ctx).expect("GateDagGate must run cleanly");

    assert_eq!(
        report.count(),
        0,
        "GateDagGate must report zero findings: {:?}",
        report.findings
    );

    assert_eq!(
        report.coverage.len(),
        1,
        "GateDagGate must produce exactly one coverage row"
    );

    let cov = &report.coverage[0];
    assert_eq!(cov.subject, "registered gate DAG");
    assert_eq!(cov.discovered, GATE_METADATA.len());
    assert_eq!(cov.judged, GATE_METADATA.len());
    assert_eq!(cov.exemptions.len(), 0);
    assert_eq!(cov.discovered_identities.len(), GATE_METADATA.len());

    assert!(
        report.coverage_failures().is_empty(),
        "coverage failures must be empty: {:?}",
        report.coverage_failures()
    );
    assert!(
        report
            .contract_failures(descriptor_by_name("gate-dag"))
            .is_empty(),
        "contract failures must be empty: {:?}",
        report.contract_failures(descriptor_by_name("gate-dag"))
    );
}

/// WHY: the registered gate set is derived at run time, so the contract fails
/// when a gate has no baseline row, no mutation suite reference, or no owner, so adding a gate
/// without those turns the suite red.
#[test]
fn runtime_registered_gate_set_has_owner_proof_and_baseline() {
    let root = xtask::checkout::checkout_root();
    let baseline_content = std::fs::read_to_string(root.join("xtask/gate-baselines.toml"))
        .expect("gate-baselines.toml must be readable");
    let baseline_data: toml::Value =
        toml::from_str(&baseline_content).expect("gate-baselines.toml must parse as valid TOML");
    let baseline_gates = baseline_data
        .get("gate")
        .and_then(|g| g.as_array())
        .expect("gate-baselines.toml must contain [[gate]] array");
    let baseline_names: std::collections::BTreeSet<&str> = baseline_gates
        .iter()
        .filter_map(|g| g.get("name").and_then(|n| n.as_str()))
        .collect();

    // Derive registered gate descriptors at run time
    let registered_descriptors = GATE_METADATA;
    assert!(
        !registered_descriptors.is_empty(),
        "registered gate set must not be empty"
    );

    for desc in registered_descriptors {
        // 1. Must have an authoritative owner in known packages
        let owner = desc.owner();
        assert!(
            ["xtask", "xtask-registry", "xtask-evidence"].contains(&owner),
            "gate `{}` has invalid or missing owner: `{owner}`",
            desc.name
        );

        // 2. Must have a valid mutation suite reference
        let proof = desc.mutation_suite().trim();
        assert!(
            !proof.is_empty() && proof != "definition-site mutation tests",
            "gate `{}` must declare an authoritative mutation suite reference, found `{proof}`",
            desc.name
        );

        // 3. Must have a baseline row in gate-baselines.toml
        assert!(
            baseline_names.contains(desc.name),
            "gate `{}` has no baseline row in xtask/gate-baselines.toml",
            desc.name
        );

        // 4. Must pass descriptor self-validation
        let failures = desc.failures();
        assert!(
            failures.is_empty(),
            "gate `{}` descriptor validation failed: {failures:?}",
            desc.name
        );
    }
}

/// WHY: a gate missing owner, proof, or baseline must fail the contract.
#[test]
fn runtime_gate_validation_fails_on_missing_owner_proof_or_baseline() {
    let mut desc = *descriptor_by_name("architecture-contract");

    // Missing owner
    desc.package = "unknown-package";
    let failures = desc.failures();
    assert!(
        failures.iter().any(|f| f.contains("unknown owner package")),
        "validation must fail on unknown/missing owner: {failures:?}"
    );

    // Missing proof
    let mut desc_no_proof = *descriptor_by_name("architecture-contract");
    desc_no_proof.proof = "";
    let failures = desc_no_proof.failures();
    assert!(
        failures
            .iter()
            .any(|f| f.contains("declares no mutation-proof test")),
        "validation must fail on missing mutation proof: {failures:?}"
    );
}
