//! The facade's `[features]` table, rendered from the roster.
//!
//! The table was a hand-maintained list of one row per domain feature, beside a
//! second hand-maintained list of the same features in the domain manifests.
//! Two lists of one fact disagree, and splitting `vyre-libs` into domain
//! packages made every row a second declaring package for a name the domain
//! already owned. The roster is the one copy, and this renders the table from
//! it, so a row cannot forward to a package the record does not name and a
//! recorded domain feature cannot be missing a row.

use std::fmt::Write as _;

use super::roster::{FacadeFeature, FacadeRoster};

/// The heading `--write` puts above the generated table.
const HEADER: &str = "# Generated by `cargo xtask configuration-model --write` from the [facade]\n\
                      # roster in docs/CRATE_OWNERSHIP.toml. Edit that record, not this table.\n";

/// The body one facade row carries, in the order the table renders it.
///
/// `requires` is the facade's own curation of what a selection exposes.
/// `dep:` activates the domain package when the facade declares it optional,
/// and the trailing entry forwards the name to the package that declares it,
/// weakly when the dependency is optional because cargo rejects a strong
/// forward into an inactive optional dependency.
#[must_use]
pub fn row_body(feature: &FacadeFeature, optional: bool) -> Vec<String> {
    let mut body = feature.requires.clone();
    body.extend(
        feature
            .activates
            .iter()
            .map(|dependency| format!("dep:{dependency}")),
    );
    if optional {
        body.push(format!("dep:{}", feature.domain));
        body.push(format!("{}?/{}", feature.domain, feature.name));
    } else {
        body.push(format!("{}/{}", feature.domain, feature.name));
    }
    body
}

/// Render one TOML array of feature names on a single line.
fn inline(names: &[String]) -> String {
    let quoted: Vec<String> = names.iter().map(|name| format!("\"{name}\"")).collect();
    format!("[{}]", quoted.join(", "))
}

/// Render one TOML array of feature names one per line.
fn block(names: &[String]) -> String {
    let mut text = String::from("[\n");
    for name in names {
        let _ = writeln!(text, "    \"{name}\",");
    }
    text.push(']');
    text
}

/// The whole `[features]` table the roster describes, header included.
///
/// `full` names every published feature. A feature declared and left out of
/// `full` compiles in a workspace build because another member unifies it back
/// in, and fails only when the facade is built alone, so the generated set has
/// no room for the omission.
#[must_use]
pub fn render(roster: &FacadeRoster) -> String {
    let mut text = String::from(HEADER);
    text.push_str("[features]\n");
    let _ = writeln!(text, "default = {}", block(&roster.default));
    text.push('\n');

    let mut full: Vec<String> = roster
        .feature
        .iter()
        .map(|entry| entry.name.clone())
        .collect();
    full.extend(roster.aggregate.iter().map(|entry| entry.name.clone()));
    let _ = writeln!(text, "full = {}", block(&full));
    text.push('\n');

    for aggregate in &roster.aggregate {
        let _ = writeln!(text, "{} = {}", aggregate.name, inline(&aggregate.selects));
    }
    if !roster.aggregate.is_empty() {
        text.push('\n');
    }
    for local in &roster.local {
        let _ = writeln!(text, "{local} = []");
    }

    for domain in &roster.domain {
        let rows: Vec<&FacadeFeature> = roster
            .feature
            .iter()
            .filter(|entry| entry.domain == domain.package)
            .collect();
        if rows.is_empty() {
            continue;
        }
        text.push('\n');
        for row in rows {
            let _ = writeln!(
                text,
                "{} = {}",
                row.name,
                inline(&row_body(row, domain.optional))
            );
        }
    }
    text
}

/// Splice the rendered table into `manifest`, leaving every other section byte
/// for byte as it was.
///
/// The table is one contiguous region: it starts at the generated header or the
/// `[features]` line, whichever comes first, and ends at the next section
/// heading. Everything outside it, `[dependencies]` included, stays
/// hand-authored and is only checked.
///
/// # Errors
///
/// Returns the reason the manifest has no `[features]` table to replace.
pub fn splice(manifest: &str, table: &str) -> Result<String, String> {
    let normalised = manifest.replace("\r\n", "\n");
    let mut lines: Vec<&str> = normalised.split('\n').collect();
    let features = lines
        .iter()
        .position(|line| line.trim_end() == "[features]")
        .ok_or_else(|| "the manifest declares no [features] table".to_string())?;
    let mut start = features;
    while start > 0 {
        let previous = lines[start - 1].trim_start();
        if previous.starts_with('#') {
            start -= 1;
        } else {
            break;
        }
    }
    let end = lines
        .iter()
        .enumerate()
        .skip(features + 1)
        .find(|(_, line)| line.trim_start().starts_with('['))
        .map_or(lines.len(), |(index, _)| index);
    let mut replacement: Vec<&str> = table.trim_end_matches('\n').split('\n').collect();
    replacement.push("");
    lines.splice(start..end, replacement);
    Ok(lines.join("\n"))
}
