//! PTX text emitter for vyre `KernelDescriptor`.
//!
//! Consumes a substrate-neutral `vyre_lower::KernelDescriptor` and
//! produces NVRTC-compatible PTX assembly text. The emitter owns only
//! PTX construction; descriptor shaping and substrate-neutral
//! analyses stay in `vyre-lower`.
//!
//! ## Op coverage
//!
//! Mirrors `vyre-emit-naga` for parity:
//! - `Literal` (U32, I32, F32, Bool)
//! - `LocalInvocationId` / `GlobalInvocationId` / `WorkgroupId` (axis 0/1/2)
//! - `LoadGlobal` / `StoreGlobal` (scalar U32/I32/F32/Bool, plus packed
//!   `v2`/`v4` U32/I32/F32 chains when the descriptor presents unit-stride
//!   adjacent accesses)
//! - `BinOpKind` for the common arithmetic/logic set
//! - `UnOpKind` for Negate / LogicalNot / BitNot
//! - `Cast` between scalar types
//! - `Select`, `Fma`
//! - `StructuredIfThen`, `StructuredIfThenElse`, `StructuredBlock`,
//!   `Region`, `Return`, workgroup-scope `Barrier`
//!
//! Out of scope (returns `EmitError::UnsupportedOp` or
//! `EmitError::InvalidDescriptor`): indirect-dispatch (host concern),
//! `MemoryOrdering::GridSync` until a native cooperative-grid lowering is
//! wired, and descriptor forms without a PTX-safe lowering.
//!
//! ## PTX output shape
//!
//! ```text
//! //
//! // Generated by vyre-emit-ptx (target sm_70)
//! //
//! .version 7.0
//! .target sm_70
//! .address_size 64
//!
//! .visible .entry main(
//!     .param .u64 _arg_<binding_name>
//! )
//! {
//!     .reg .pred  %p<N>;
//!     .reg .u32   %r<N>;
//!     .reg .s32   %s<N>;
//!     .reg .f32   %f<N>;
//!     .reg .u64   %rd<N>;
//!
//!     <body>
//!
//!     ret;
//! }
//! ```

mod emitter;
mod error;
mod index_facts;
pub mod patterns;
mod reg;
mod target;

use vyre_lower::KernelDescriptor;

pub use error::EmitError;
pub use target::{ComputeCapability, PtxEmitOptions};

/// Digest of this emitter's source, stamped in at build time.
///
/// A PTX cache keyed on the program and a hand-edited lowering label cannot see
/// that the emitter changed: the key stays the same and stale PTX, in memory or
/// on disk, answers for a fixed lowering. Mixing this into the key ties every
/// cached artifact to the emitter that produced it, whether or not the label was
/// edited.
pub const LOWERING_DIGEST: &str = env!("VYRE_PTX_LOWERING_DIGEST");

/// Module-scope symbol holding the trap record for one loaded module.
///
/// [`vyre_lower::TRAP_SIDECAR_WORDS`] u32 words: word 0 is the claim flag (CAS 0
/// to 1, so exactly one lane writes the rest), word 1 the address operand the
/// trapping op carried, word 2 the trap tag code, word 3 the flattened global
/// invocation id. Same layout the secondary text emitter writes, so a host
/// decodes either target's record with one reader.
pub const TRAP_SIDECAR_SYMBOL: &str = "_vyre_trap_sidecar";

/// Comment prefix carrying one `code tag` pair per declared trap in the emitted
/// text.
///
/// The table travels in the module text rather than beside it so the host decodes
/// word 2 against the module it loaded. A module is cached by its text and target,
/// so a table parsed out of that text cannot belong to a different descriptor.
pub const TRAP_TAG_PTX_MARKER: &str = "// vyre trap tag ";

/// Emit PTX for the default compute capability.
pub fn emit(desc: &KernelDescriptor) -> Result<String, EmitError> {
    emit_with_target(desc, ComputeCapability::default())
}

/// Emit PTX for an explicit compute capability.
pub fn emit_with_target(
    desc: &KernelDescriptor,
    target: ComputeCapability,
) -> Result<String, EmitError> {
    emit_with_options(desc, PtxEmitOptions::for_target(target))
}

/// Emit PTX using explicit instruction-selection options.
pub fn emit_with_options(
    desc: &KernelDescriptor,
    options: PtxEmitOptions,
) -> Result<String, EmitError> {
    if options.subgroup_size == 0
        || options.subgroup_size > 32
        || !options.subgroup_size.is_power_of_two()
    {
        return Err(EmitError::InvalidDescriptor(format!(
            "invalid CUDA subgroup size {}. Fix: pass the probed CUDA warp size.",
            options.subgroup_size
        )));
    }
    emitter::emit_text(desc, options)
}
