//! Rendering the merged rows as the canonical matrix TOML.

use super::manual_rows::SCAN_CONSTRUCT_MATRIX;
use super::record::OpRecord;

pub(super) fn render_matrix(records: &[OpRecord]) -> String {
    let mut out = String::new();
    out.push_str("# Canonical op/backend optimization and coverage matrix.\n");
    out.push_str("# Generated by `./cargo_full run --bin xtask -- op-matrix --write` from the live operation registry.\n");
    out.push_str(
        "# Do not hand-edit generated rows; change the source registry or generator instead.\n\n",
    );
    out.push_str("schema = 2\n\n");
    out.push_str("backend_status_values = [\n");
    out.push_str("  \"supported\",\n  \"experimental\",\n  \"not_applicable\",\n  \"blocked_release\",\n]\n\n");
    out.push_str("tier_values = [\n");
    out.push_str("  \"foundation_ir\",\n  \"intrinsic\",\n  \"libs\",\n  \"external\",\n]\n\n");
    out.push_str(SCAN_CONSTRUCT_MATRIX);

    for record in records {
        out.push_str("[[op]]\n");
        push_string(&mut out, "family", &record.family);
        push_string(&mut out, "tier", record.tier.matrix_value());
        push_array(&mut out, "owners", &record.owners);
        push_array(&mut out, "ops", &record.ops);
        push_array(&mut out, "registry_sources", &record.registry_sources);
        if record.duplicate_ok {
            out.push_str("duplicate_ok = true\n");
        }
        push_string(&mut out, "reference", record.reference);
        push_string(&mut out, "foundation_ir", record.foundation_ir);
        push_string(&mut out, "cuda", record.cuda);
        push_string(&mut out, "wgpu", record.wgpu);
        push_string(&mut out, "spirv", record.spirv);
        push_string(
            &mut out,
            "release_blocking_notes",
            &record.release_blocking_notes,
        );
        push_array(&mut out, "tests", &record.tests);
        push_array(&mut out, "bench_targets", &record.bench_targets);
        out.push('\n');
    }
    out
}

fn push_string(out: &mut String, key: &str, value: &str) {
    out.push_str(key);
    out.push_str(" = ");
    out.push_str(&format!("{value:?}"));
    out.push('\n');
}

fn push_array(out: &mut String, key: &str, values: &[String]) {
    out.push_str(key);
    out.push_str(" = [");
    if values.is_empty() {
        out.push_str("]\n");
        return;
    }
    for (index, value) in values.iter().enumerate() {
        if index != 0 {
            out.push_str(", ");
        }
        out.push_str(&format!("{value:?}"));
    }
    out.push_str("]\n");
}
