//! The command line of an xtask binary that takes no arguments.
//!
//! Three of these binaries exist and two of them accept nothing but `--help`.
//! Each carried its own `print_help` and its own argument loop, and the loop is
//! where the exit codes live: `2` for an argument nobody declared, `0` for the
//! help page. `docs/CLI.toml` is generated by parsing that help page, so a
//! binary whose loop drifted stopped being documented rather than failing.
//!
//! The help page is fixed here: a summary line, a `Usage:` line, and an
//! `Exit codes:` block whose last row is always the argument error, because
//! that row is produced by this module and not by the caller.

/// What the command line of a no-argument binary asks for.
#[derive(Debug, Eq, PartialEq)]
pub enum Request {
    /// Do the binary's work.
    Run,
    /// Print the help page and exit `0`.
    Help,
    /// Reject the named argument and exit `2`.
    Unknown(String),
}

/// Classify the arguments after the binary name.
///
/// `--help` is only help when it is the whole command line. `--help extra` is
/// an unknown argument, because a binary that takes nothing has no reading of
/// the extra word that is better than saying so.
#[must_use]
pub fn request(arguments: impl IntoIterator<Item = String>) -> Request {
    let mut arguments = arguments.into_iter();
    let Some(first) = arguments.next() else {
        return Request::Run;
    };
    if matches!(first.as_str(), "-h" | "--help") && arguments.next().is_none() {
        return Request::Help;
    }
    Request::Unknown(first)
}

/// One no-argument binary's help page.
pub struct NoArguments<'a> {
    /// Name the binary is invoked by.
    pub binary: &'a str,
    /// One sentence naming what the binary does.
    pub summary: &'a str,
    /// What exit `0` means.
    pub success: &'a str,
    /// What exit `1` means.
    pub failure: &'a str,
}

impl NoArguments<'_> {
    /// The help page, exactly as the binary prints it.
    #[must_use]
    pub fn help(&self) -> String {
        let Self {
            binary,
            summary,
            success,
            failure,
        } = self;
        format!(
            "{summary}\n\nUsage: {binary}\n\nExit codes:\n  0  {success}\n  1  {failure}\n  2  command-line arguments are invalid\n"
        )
    }

    /// The message printed for an argument the binary does not take.
    #[must_use]
    pub fn unknown_argument(&self, argument: &str) -> String {
        format!(
            "Fix: unknown argument `{argument}`. Use `{} --help`.",
            self.binary
        )
    }

    /// Resolve the process command line, exiting for every outcome but `Run`.
    pub fn accept(&self) {
        match request(std::env::args().skip(1)) {
            Request::Run => {}
            Request::Help => {
                print!("{}", self.help());
                std::process::exit(0);
            }
            Request::Unknown(argument) => {
                eprintln!("{}", self.unknown_argument(&argument));
                std::process::exit(2);
            }
        }
    }
}
