//! Which directories a gate reads, in one place.
//!
//! Every gate that judges the checked-in tree walks it and prunes the same
//! directories: build outputs and version control hold generated bytes, and a
//! gate that read them would report findings against whatever the last build
//! left behind. Seven walks carried their own copy of that rule and four of the
//! copies disagreed, so a directory added to one prune list was still read by
//! the other six.
//!
//! The walk results are yielded unchanged. A gate reports an unreadable subtree
//! in its own words, and swallowing the error here would let one read as empty.

use std::path::Path;

use walkdir::{DirEntry, WalkDir};

/// Build outputs and version control. No gate reads these.
pub(crate) const BUILD_OUTPUT_AND_VCS: &[&str] = &[
    "target",
    "target-codex",
    "target_tests",
    ".cargo-target",
    ".git",
];

/// Walk `root`, pruning every entry named in `skip`.
///
/// The name test applies to files as well as directories, which is what the
/// walks this replaced did: a file named `target` is generated too.
pub(crate) fn pruned<'a>(
    root: &Path,
    skip: &'a [&'a str],
) -> impl Iterator<Item = walkdir::Result<DirEntry>> + 'a {
    pruned_by(root, move |name| !skip.contains(&name))
}

/// Walk `root`, keeping only entries whose name `keep` accepts.
///
/// For a prune rule that is more than a name list. Rejecting a directory prunes
/// everything under it.
pub(crate) fn pruned_by(
    root: &Path,
    mut keep: impl FnMut(&str) -> bool,
) -> impl Iterator<Item = walkdir::Result<DirEntry>> {
    WalkDir::new(root)
        .into_iter()
        .filter_entry(move |entry| keep(entry.file_name().to_string_lossy().as_ref()))
}
