//! Composition provenance gate over the linked operation registry.
//!
//! The LEGO-block rule requires every Category A composition to keep its own
//! identity on the region it hands out: `print-composition`, `gate1`, and the
//! duplicate-family report all key on the entry region's `generator`, and an op
//! that returns a bare body instead is invisible to every one of them. A
//! builder that forgets `region::tag_program` still compiles, still lowers, and
//! still passes its own fixture, so nothing else fails.
//!
//! # Why the member list is read from the registry
//!
//! The list of operations comes from the operation registry, which is built at
//! run time from the `inventory` submissions the linked crate carries. A
//! hardcoded list of op ids would cover the ops someone had in mind on the day
//! they wrote it, and the next op registered would be silently uncovered, which
//! is the same as having no gate. Reading the registry covers a new
//! registration the moment it links.

use vyre_foundation::ir::Node;
use vyre_libs::operation_catalog::all_entries;

/// Registrations whose entry region names an operation other than themselves.
///
/// Every row carries the concrete reason its identity belongs to another op.
const FOREIGN_ENTRY_REGION_OP_IDS: &[(&str, &str)] = &[(
    "vyre-libs::math::matmul_bias::scalar",
    "A registered 1x1x1 dispatch shape of vyre-libs::math::matmul_bias, sharing that \
     builder so it can carry a scalar fixture the 2x2x2 registration cannot. The \
     composition it opens is matmul_bias, and naming itself there would claim a second \
     composition that does not exist.",
)];

#[test]
fn every_library_operation_stamps_its_own_id_on_its_entry_region() {
    let exemptions: std::collections::HashMap<&str, &str> =
        FOREIGN_ENTRY_REGION_OP_IDS.iter().copied().collect();

    let mut checked = 0usize;
    let mut offenders: Vec<String> = Vec::new();
    for operation in all_entries() {
        if exemptions.contains_key(operation.id) {
            continue;
        }
        let Some(program) = operation.program() else {
            continue;
        };
        checked += 1;
        match program.entry().first() {
            Some(Node::Region { generator, .. }) if generator == operation.id => {}
            Some(Node::Region { generator, .. }) => offenders.push(format!(
                "  - {} opens a region generated by `{generator}`",
                operation.id
            )),
            Some(other) => offenders.push(format!(
                "  - {} opens with {} instead of a region",
                operation.id,
                node_kind(other)
            )),
            None => offenders.push(format!("  - {} builds an empty entry", operation.id)),
        }
    }

    // Without this the gate would pass on a registry the test binary failed to
    // link, which is the one failure mode an empty offender list cannot show.
    assert!(
        checked > 100,
        "only {checked} library operations reached the provenance check. Fix: the linked \
         inventory is incomplete, so this gate is measuring nothing."
    );

    assert!(
        offenders.is_empty(),
        "composition provenance lost: a library operation does not name itself on its entry \
         region.\n{}\nFix: return `region::tag_program(OP_ID, program)` from the builder, or \
         record the reason in FOREIGN_ENTRY_REGION_OP_IDS.",
        offenders.join("\n")
    );
}

fn node_kind(node: &Node) -> &'static str {
    match node {
        Node::Let { .. } => "a let binding",
        Node::Assign { .. } => "an assignment",
        Node::Store { .. } => "a store",
        Node::If { .. } => "a conditional",
        Node::Loop { .. } => "a loop",
        Node::Block(_) => "a bare block",
        Node::Barrier { .. } => "a barrier",
        Node::Return => "a return",
        _ => "a non-region node",
    }
}
