//! Composition provenance gate over the linked operation registry.
//!
//! The LEGO-block rule requires every Category A composition to keep its own
//! identity on the region it hands out: `print-composition`, `gate1`, and the
//! duplicate-family report all key on the entry region's `generator`, and an op
//! that returns a bare body instead is invisible to every one of them. A
//! builder that forgets `region::tag_program` still compiles, still lowers, and
//! still passes its own fixture, so nothing else fails.
//!
//! # Why the member list is read from the registry
//!
//! The list of operations comes from the operation registry, which is built at
//! run time from the `inventory` submissions the linked crate carries. A
//! hardcoded list of op ids would cover the ops someone had in mind on the day
//! they wrote it, and the next op registered would be silently uncovered, which
//! is the same as having no gate. Reading the registry covers a new
//! registration the moment it links.

use vyre_foundation::ir::Node;
use vyre_libs::operation_catalog::all_entries;

/// Registrations whose entry region names an operation other than themselves.
///
/// Every row carries the concrete reason its identity belongs to another op.
const FOREIGN_ENTRY_REGION_OP_IDS: &[(&str, &str)] = &[(
    "vyre-libs::math::matmul_bias::scalar",
    "A registered 1x1x1 dispatch shape of vyre-libs::math::matmul_bias, sharing that \
     builder so it can carry a scalar fixture the 2x2x2 registration cannot. The \
     composition it opens is matmul_bias, and naming itself there would claim a second \
     composition that does not exist.",
)];

#[test]
fn every_library_operation_stamps_its_own_id_on_its_entry_region() {
    let exemptions: std::collections::HashMap<&str, &str> =
        FOREIGN_ENTRY_REGION_OP_IDS.iter().copied().collect();

    let mut checked = 0usize;
    let mut offenders: Vec<String> = Vec::new();
    let mut without_program: Vec<&str> = Vec::new();
    let mut stale_exemptions: Vec<&str> = Vec::new();
    for operation in all_entries() {
        let Some(program) = operation.program() else {
            without_program.push(operation.id);
            continue;
        };
        let exempt = exemptions.contains_key(operation.id);
        checked += 1;
        match program.entry().first() {
            Some(Node::Region { generator, .. }) if generator == operation.id => {
                if exempt {
                    stale_exemptions.push(operation.id);
                }
            }
            _ if exempt => {}
            Some(Node::Region { generator, .. }) => offenders.push(format!(
                "  - {} opens a region generated by `{generator}`",
                operation.id
            )),
            Some(other) => offenders.push(format!(
                "  - {} opens with {} instead of a region",
                operation.id,
                node_kind(other)
            )),
            None => offenders.push(format!("  - {} builds an empty entry", operation.id)),
        }
    }

    // The population is the registry this build linked, which grows and shrinks
    // with the enabled dialect features, so a pinned count would be wrong under
    // every feature set but the one it was measured on. These three assertions
    // pin the shape instead: the registry linked, no operation slipped past the
    // check unexamined, and no exemption is describing an operation that now
    // obeys the rule.
    assert!(
        checked > 0,
        "no library operation reached the provenance check. Fix: the operation registry linked \
         empty, so this gate is measuring nothing."
    );
    assert!(
        without_program.is_empty(),
        "these library operations carry no program builder, so their provenance is unchecked: \
         {without_program:?}. Fix: register the builder, or drop the registration."
    );
    assert!(
        stale_exemptions.is_empty(),
        "these FOREIGN_ENTRY_REGION_OP_IDS rows name operations that already stamp their own \
         id: {stale_exemptions:?}. Fix: delete the row."
    );

    assert!(
        offenders.is_empty(),
        "composition provenance lost: a library operation does not name itself on its entry \
         region.\n{}\nFix: return `region::tag_program(OP_ID, program)` from the builder, or \
         record the reason in FOREIGN_ENTRY_REGION_OP_IDS.",
        offenders.join("\n")
    );
}

/// An exemption for an id no registration submits describes nothing.
///
/// The liveness check above only sees rows whose feature is enabled in this
/// build, so a row for a dialect this build left out would survive forever. The
/// id is read out of the crate source, which covers every feature at once.
#[test]
fn every_exemption_names_an_operation_this_crate_registers() {
    let mut sources = Vec::new();
    let crate_dir = vyre_test_support::monorepo::vyre_crate_directory(env!("CARGO_PKG_NAME"));
    vyre_test_support::collect_rust_files(crate_dir.join("src").as_path(), &mut sources);
    let text: String = sources
        .iter()
        .map(|path| std::fs::read_to_string(path).expect("Fix: crate source must be readable"))
        .collect();
    assert!(
        text.contains("OperationRegistration::library"),
        "no registration text was read. Fix: the source walk found nothing, so this test is \
         measuring nothing."
    );

    let unknown: Vec<&str> = FOREIGN_ENTRY_REGION_OP_IDS
        .iter()
        .map(|(id, _)| *id)
        .filter(|id| !text.contains(&format!("\"{id}\"")))
        .collect();
    assert!(
        unknown.is_empty(),
        "these FOREIGN_ENTRY_REGION_OP_IDS rows name ids no source registers: {unknown:?}. \
         Fix: delete the row, or correct the id."
    );
}

fn node_kind(node: &Node) -> &'static str {
    match node {
        Node::Let { .. } => "a let binding",
        Node::Assign { .. } => "an assignment",
        Node::Store { .. } => "a store",
        Node::If { .. } => "a conditional",
        Node::Loop { .. } => "a loop",
        Node::Block(_) => "a bare block",
        Node::Barrier { .. } => "a barrier",
        Node::Return => "a return",
        _ => "a non-region node",
    }
}
