//! Multi-Token Prediction (MTP): speculative draft-head graphs, provisional KV state,
//! and transactional verification/rollback.
//!
//! # Architecture
//!
//! Multi-Token Prediction (MTP) accelerates autoregressive model inference by predicting
//! multiple future tokens ($K$ draft heads) concurrently with the main language model head.
//!
//! Key principles:
//! - **Provisional KV Writes**: Draft-head KV-cache writes and prefix-cache reference
//!   changes remain strictly provisional until verified.
//! - **Transactional Verification & Rollback**: When $m \le K$ draft tokens are accepted,
//!   only the verified prefix of $m$ tokens is committed to the cache. All unaccepted
//!   tokens ($m < k \le K$), cancellations, or device failures immediately roll back
//!   their provisional KV entries and release reserved pages, without exposing draft
//!   state to any other request.
//! - **Intermediate Hidden-State Residency**: Compatible intermediate states are kept
//!   resident across heads (via register forwarding, shared memory, or global resident buffers).

use thiserror::Error;

use crate::prefix_cache::{PrefixCache, PrefixCacheError, PrefixCacheKey};

/// Storage candidate strategy for intermediate hidden states across draft heads.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MtpStorageCandidate {
    /// Fused execution: forward intermediates directly through registers when register pressure permits.
    RegisterForwarded,
    /// Fast on-chip shared memory candidate.
    SharedResidentMemory,
    /// Resident global device buffer candidate.
    GlobalResidentBuffer,
}

/// Configuration parameters for Multi-Token Prediction (MTP).
#[derive(Debug, Clone, PartialEq)]
pub struct MtpConfig {
    /// Maximum prediction depth (number of speculative draft heads $K$).
    pub max_depth: usize,
    /// Hidden dimension of token activations.
    pub hidden_dim: usize,
    /// Vocabulary size.
    pub vocab_size: usize,
    /// Storage candidate for intermediate representations.
    pub storage_candidate: MtpStorageCandidate,
}

impl Default for MtpConfig {
    fn default() -> Self {
        Self {
            max_depth: 3,
            hidden_dim: 4096,
            vocab_size: 32000,
            storage_candidate: MtpStorageCandidate::RegisterForwarded,
        }
    }
}

/// Errors occurring during MTP execution or verification.
#[derive(Debug, Clone, PartialEq, Eq, Error)]
pub enum MtpError {
    /// Prediction depth exceeds configured maximum.
    #[error("requested MTP draft depth {depth} exceeds configured maximum {max_depth}")]
    DepthExceeded {
        /// Requested depth.
        depth: usize,
        /// Maximum allowed depth.
        max_depth: usize,
    },
    /// Verification failed due to mismatch or invalid state.
    #[error("MTP verification error: {0}")]
    VerificationFailure(String),
    /// Underlying prefix cache error.
    #[error("prefix cache error: {0}")]
    PrefixCacheError(#[from] PrefixCacheError),
    /// Speculative execution was cancelled.
    #[error("MTP speculative step was cancelled")]
    Cancelled,
}

/// A speculative draft token proposal from a draft head.
#[derive(Debug, Clone, PartialEq)]
pub struct MtpDraftToken {
    /// Draft head depth (1-indexed: 1, 2, ..., K).
    pub depth: usize,
    /// Speculative predicted token ID.
    pub token_id: u32,
    /// Logit / confidence score.
    pub confidence: f32,
    /// Provisional physical page IDs allocated for this draft token's KV cache.
    pub provisional_page_ids: Vec<u32>,
}

/// Provisional state held during speculative MTP execution before verification.
#[derive(Debug, Clone)]
pub struct MtpProvisionalState {
    /// Request identifier.
    pub request_id: u64,
    /// Verified prefix length before this speculative burst.
    pub base_prefix_tokens: Vec<u32>,
    /// Speculative draft tokens generated by draft heads.
    pub draft_tokens: Vec<MtpDraftToken>,
    /// Cache key under which provisional pages are reserved.
    pub cache_key: PrefixCacheKey,
}

/// Outcome of MTP verification against the target model / main head logits.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MtpVerificationResult {
    /// Tokens verified and accepted (including main head token and matching draft tokens).
    pub accepted_tokens: Vec<u32>,
    /// Number of speculative draft tokens accepted ($0 \le m \le K$).
    pub accepted_draft_count: usize,
    /// Number of speculative draft tokens rolled back.
    pub rolled_back_count: usize,
    /// Pages committed permanently into the prefix cache.
    pub committed_pages: Vec<u32>,
    /// Provisional pages discarded and rolled back.
    pub released_pages: Vec<u32>,
}

/// MTP lifecycle and verification coordinator.
pub struct MtpCoordinator {
    config: MtpConfig,
    prefix_cache: PrefixCache,
}

impl MtpCoordinator {
    /// Create a new MTP coordinator.
    #[must_use]
    pub fn new(config: MtpConfig, prefix_cache: PrefixCache) -> Self {
        Self {
            config,
            prefix_cache,
        }
    }

    /// Access MTP configuration.
    #[must_use]
    pub const fn config(&self) -> &MtpConfig {
        &self.config
    }

    /// Stage a speculative MTP step: reserves provisional pages for draft tokens.
    ///
    /// # Errors
    ///
    /// Returns [`MtpError`] if depth exceeds configuration or cache allocation fails.
    pub fn stage_speculative_step(
        &self,
        request_id: u64,
        cache_key: &PrefixCacheKey,
        base_prefix: &[u32],
        draft_proposals: &[(u32, f32)], // (token_id, confidence)
    ) -> Result<MtpProvisionalState, MtpError> {
        let depth = draft_proposals.len();
        if depth > self.config.max_depth {
            return Err(MtpError::DepthExceeded {
                depth,
                max_depth: self.config.max_depth,
            });
        }

        let mut full_sequence = base_prefix.to_vec();
        let mut draft_tokens = Vec::with_capacity(depth);

        for (i, &(token_id, confidence)) in draft_proposals.iter().enumerate() {
            full_sequence.push(token_id);
            // Reserve provisional page in cache
            let provisional_pages =
                self.prefix_cache
                    .insert_or_extend(cache_key, &full_sequence, &[])?;

            draft_tokens.push(MtpDraftToken {
                depth: i + 1,
                token_id,
                confidence,
                provisional_page_ids: provisional_pages,
            });
        }

        Ok(MtpProvisionalState {
            request_id,
            base_prefix_tokens: base_prefix.to_vec(),
            draft_tokens,
            cache_key: cache_key.clone(),
        })
    }

    /// Verify draft tokens against ground-truth main head verification tokens.
    ///
    /// Commits accepted tokens to the cache and rolls back rejected draft entries.
    ///
    /// # Errors
    ///
    /// Returns [`MtpError`] on verification or cache release failure.
    pub fn verify_and_commit(
        &self,
        provisional: MtpProvisionalState,
        verified_ground_truth: &[u32], // Sequence of ground-truth verified tokens
    ) -> Result<MtpVerificationResult, MtpError> {
        let mut accepted_tokens = provisional.base_prefix_tokens;
        let mut accepted_draft_count = 0;
        let mut committed_pages = Vec::new();
        let mut released_pages = Vec::new();

        let mut mismatch_occurred = false;

        for (i, draft) in provisional.draft_tokens.iter().enumerate() {
            if !mismatch_occurred
                && i < verified_ground_truth.len()
                && draft.token_id == verified_ground_truth[i]
            {
                // Draft token accepted
                accepted_tokens.push(draft.token_id);
                accepted_draft_count += 1;
                committed_pages.extend_from_slice(&draft.provisional_page_ids);
            } else {
                // Draft token rejected or downstream from a mismatch: roll back!
                mismatch_occurred = true;
                released_pages.extend_from_slice(&draft.provisional_page_ids);
            }
        }

        // Add any ground-truth token produced by the main head at the mismatch point
        if verified_ground_truth.len() > accepted_draft_count {
            accepted_tokens.push(verified_ground_truth[accepted_draft_count]);
        }

        // Release rejected provisional pages back to the cache pool
        if !released_pages.is_empty() {
            self.prefix_cache.release(&released_pages)?;
        }

        let rolled_back_count = provisional.draft_tokens.len() - accepted_draft_count;

        Ok(MtpVerificationResult {
            accepted_tokens,
            accepted_draft_count,
            rolled_back_count,
            committed_pages,
            released_pages,
        })
    }

    /// Roll back all provisional draft state in case of cancellation or device failure.
    ///
    /// # Errors
    ///
    /// Returns [`MtpError`] on cache release failure.
    pub fn rollback_all(&self, provisional: MtpProvisionalState) -> Result<(), MtpError> {
        let mut all_pages = Vec::new();
        for draft in provisional.draft_tokens {
            all_pages.extend_from_slice(&draft.provisional_page_ids);
        }
        if !all_pages.is_empty() {
            self.prefix_cache.release(&all_pages)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::prefix_cache::{PrefixCacheLayout, PrefixCacheLimits};
    use vyre_foundation::ir::DataType;

    fn test_key() -> PrefixCacheKey {
        PrefixCacheKey {
            model_id: [1u8; 32],
            tokenizer_id: [2u8; 32],
            weights_digest: [3u8; 32],
            config_digest: [4u8; 32],
            dtype: DataType::F32,
            layout: PrefixCacheLayout {
                kv_heads: 2,
                head_dim: 32,
                block_tokens: 16,
            },
            device_generation: 1,
            cache_schema_version: 1,
            isolation_domain: "tenant_mtp".to_string(),
            trust_domain: None,
        }
    }

    #[test]
    fn mtp_partial_acceptance_and_rollback() {
        let prefix_cache = PrefixCache::new(PrefixCacheLimits::default(), 1);
        let config = MtpConfig {
            max_depth: 3,
            hidden_dim: 128,
            vocab_size: 1000,
            storage_candidate: MtpStorageCandidate::RegisterForwarded,
        };
        let coordinator = MtpCoordinator::new(config, prefix_cache.clone());
        let key = test_key();

        let base_prefix = vec![10, 20];
        // Draft proposes tokens: 30, 40, 50
        let draft_proposals = vec![(30, 0.9), (40, 0.8), (50, 0.7)];

        let staged = coordinator
            .stage_speculative_step(1, &key, &base_prefix, &draft_proposals)
            .expect("stage");

        // Ground truth verification: token 30 is accepted, but second token is 45 (not 40).
        let ground_truth = vec![30, 45];

        let result = coordinator
            .verify_and_commit(staged, &ground_truth)
            .expect("verify");

        // Token 30 accepted, token 40 and 50 rejected
        assert_eq!(result.accepted_draft_count, 1);
        assert_eq!(result.rolled_back_count, 2);
        // Result sequence: base [10, 20] + accepted draft [30] + main head correction [45]
        assert_eq!(result.accepted_tokens, vec![10, 20, 30, 45]);
        assert!(!result.released_pages.is_empty());
    }

    #[test]
    fn mtp_full_cancellation_rollback() {
        let prefix_cache = PrefixCache::new(PrefixCacheLimits::default(), 1);
        let coordinator = MtpCoordinator::new(MtpConfig::default(), prefix_cache.clone());
        let key = test_key();

        let staged = coordinator
            .stage_speculative_step(1, &key, &[1, 2], &[(3, 0.9), (4, 0.9)])
            .expect("stage");

        // Rollback all without committing anything
        coordinator.rollback_all(staged).expect("rollback");
    }
}
