use std::fmt::Write as _;

use rustc_hash::FxHashSet;
use vyre_lower::{
    DescriptorTrapTag, KernelDescriptor, KernelOpKind, MemoryClass, TRAP_SIDECAR_NAME,
    TRAP_SIDECAR_WORDS,
};

use super::param_identifier::sanitize_param_name;
use super::text_capacity::{body_op_count_recursive, estimate_body_text_capacity};
use super::BodyCtx;
use crate::{EmitError, PtxEmitOptions, TRAP_SIDECAR_SYMBOL, TRAP_TAG_PTX_MARKER};

/// How many `MemoryOrdering::GridSync` barriers the descriptor contains.
///
/// Each lowers to a monotonic-counter cooperative barrier
/// ([`BodyCtx::emit_grid_sync_barrier`]) that reads and writes the module-scope
/// `_vyre_grid_barrier` counter, so a nonzero count is what makes the module
/// declare that counter. The same recursive iterator drives
/// `requires_full_workgroup_entry`, so detection here and the all-lanes-live
/// entry stay in lockstep.
///
/// The count, rather than a bare yes/no, is what lets the body tell a lane exit
/// that still has a barrier ahead of it from one that has none left: the counter
/// is only stranded by a lane that leaves before its CTA's last arrival.
pub(super) fn descriptor_grid_sync_barrier_count(desc: &KernelDescriptor) -> u32 {
    desc.ops_iter()
        .filter(|op| {
            matches!(op.kind, KernelOpKind::Barrier { ordering } if ordering.requires_grid_sync())
        })
        .count()
        .try_into()
        .unwrap_or(u32::MAX)
}

pub(super) struct ModuleBuilder {
    options: PtxEmitOptions,
    text: String,
}

impl ModuleBuilder {
    pub(super) fn new(options: PtxEmitOptions, text_capacity: usize) -> Self {
        Self {
            options,
            text: String::with_capacity(text_capacity),
        }
    }

    pub(super) fn write_preamble(&mut self) {
        let target = self.options.target;
        // PTX `.version` must rise alongside `.target` because each
        // new sm_NN ISA bumps the minimum PTX ISA version that can
        // name it. Driver/JIT rejects mismatched pairs with
        // CUDA_ERROR_INVALID_PTX. Mapping per the NVIDIA PTX ISA
        // tables (see CUDA 12.x Programming Guide, "PTX ISA
        // Versions"):
        //   sm_120 (Blackwell-2)       → PTX 8.7+
        //   sm_100 / sm_101 (Blackwell)→ PTX 8.6+
        //   sm_90  (Hopper)            → PTX 8.0+
        //   sm_70..sm_89 (Volta–Ada)   → PTX 6.0+ (8.5 covers all)
        let ptx_version = match target.major * 10 + target.minor {
            120.. => "8.7",
            100..=119 => "8.6",
            90..=99 => "8.0",
            _ => "8.5",
        };
        let _ = writeln!(
            self.text,
            "//\n// Generated by vyre-emit-ptx (target sm_{}{})\n//\n.version {ptx_version}\n.target sm_{}{}\n.address_size 64\n",
            target.major, target.minor, target.major, target.minor
        );
    }

    /// Declare the module-scope trap sidecar and the tag table that decodes it.
    ///
    /// The sidecar is four u32 words at module scope, not an entry parameter.
    /// Every launch path on this target builds its kernel argument list from the
    /// program's buffers, and the sidecar is a descriptor binding with no program
    /// buffer behind it, so adding a parameter would require each of those paths
    /// to synthesize an allocation in exactly the right position. A position
    /// mismatch there compiles and launches, and reads whatever the neighbouring
    /// argument points at. Module scope needs no argument at all, and the host
    /// resolves the symbol from the loaded module the same way it resolves
    /// `_vyre_grid_barrier`.
    ///
    /// Module scope means one sidecar per loaded module rather than one per
    /// launch, so the host serializes launches of a trap-declaring module for the
    /// same reason it serializes cooperative ones: overlapping launches would let
    /// one launch's zeroing erase another's record.
    ///
    /// The tag markers carry the code-to-tag table in the PTX text, so the host
    /// decodes word 2 from the module it actually loaded rather than from a
    /// descriptor it was separately handed. `vyre-lower` owns the numbering, so a
    /// code means the same tag here as on every other target.
    fn write_trap_sidecar(&mut self, trap_tags: &[DescriptorTrapTag]) -> Result<(), EmitError> {
        if trap_tags.is_empty() {
            return Ok(());
        }
        let _ = writeln!(
            self.text,
            ".global .align 4 .u32 {TRAP_SIDECAR_SYMBOL}[{TRAP_SIDECAR_WORDS}];"
        );
        for entry in trap_tags {
            if entry.tag.contains('\n') {
                return Err(EmitError::InvalidDescriptor(format!(
                    "trap tag `{}` spans lines, so it cannot be carried in a PTX comment marker. Fix: give the trap a single-line tag.",
                    entry.tag
                )));
            }
            let _ = writeln!(
                self.text,
                "{TRAP_TAG_PTX_MARKER}{} {}",
                entry.code, entry.tag
            );
        }
        self.text.push('\n');
        Ok(())
    }

    pub(super) fn write_entry_point(&mut self, desc: &KernelDescriptor) -> Result<(), EmitError> {
        // One walk for the whole emission: the sidecar declaration below and the
        // body's per-trap store both need the same code-to-tag table, and a second
        // walk could disagree with the first only by being a different function.
        let trap_tags = vyre_lower::descriptor_trap_tags(&desc.body).map_err(|source| {
            EmitError::InvalidDescriptor(format!("trap tag codes unavailable: {source}"))
        })?;
        if self.options.cooperative_grid_sync && descriptor_grid_sync_barrier_count(desc) > 0 {
            // Module-scope arrival counter for the cooperative grid barrier. A
            // single u32, zeroed by the host before each cooperative launch; each
            // CTA leader bumps it once per barrier and spins until it reaches
            // (barrier_index + 1) * gridSize. `.global` (not `.const`) because it
            // is written from the device; `.align 4` matches the u32 atom.
            self.text
                .push_str(".global .align 4 .u32 _vyre_grid_barrier[1];\n\n");
        }
        self.write_trap_sidecar(&trap_tags)?;
        self.text.push_str(".visible .entry main(\n");
        let mut first = true;
        for binding in &desc.bindings.slots {
            if matches!(binding.memory_class, MemoryClass::Shared)
                || binding.name == TRAP_SIDECAR_NAME
            {
                continue;
            }
            if !first {
                self.text.push_str(",\n");
            }
            first = false;
            let _ = write!(
                self.text,
                "    .param .u64 _arg_{}",
                sanitize_param_name(&binding.name, binding.slot)
            );
        }
        if !first {
            self.text.push_str(",\n");
        }
        self.text.push_str("    .param .u64 params_buf");
        self.text.push_str("\n) {\n");

        let read_only_cache_slots = vyre_lower::analyses::analyze_texture_promote(desc)
            .candidates
            .into_iter()
            .map(|candidate| candidate.binding_slot)
            .collect::<FxHashSet<_>>();
        let mut body_ctx = BodyCtx::new(
            desc,
            &desc.bindings,
            self.options,
            read_only_cache_slots,
            estimate_body_text_capacity(&desc.body, &desc.bindings),
            body_op_count_recursive(&desc.body),
            &trap_tags,
        );
        body_ctx.preload_bindings(desc)?;
        body_ctx.emit_body(&desc.body)?;
        body_ctx.finish_with_return();

        let mut decl_block = String::with_capacity(192);
        decl_block.push_str("    // register declarations\n");
        if body_ctx.next_pred > 0 {
            let _ = writeln!(decl_block, "    .reg .pred  %p<{}>;", body_ctx.next_pred);
        }
        if body_ctx.next_b16 > 0 {
            let _ = writeln!(decl_block, "    .reg .b16   %h<{}>;", body_ctx.next_b16);
        }
        if body_ctx.next_u32 > 0 {
            let _ = writeln!(decl_block, "    .reg .u32   %r<{}>;", body_ctx.next_u32);
        }
        if body_ctx.next_i32 > 0 {
            let _ = writeln!(decl_block, "    .reg .s32   %s<{}>;", body_ctx.next_i32);
        }
        if body_ctx.next_f32 > 0 {
            let _ = writeln!(decl_block, "    .reg .f32   %f<{}>;", body_ctx.next_f32);
        }
        if body_ctx.next_u64 > 0 {
            let _ = writeln!(decl_block, "    .reg .u64   %rd<{}>;", body_ctx.next_u64);
        }
        decl_block.push('\n');

        self.text.push_str(&decl_block);
        self.text.push_str(&body_ctx.text);
        self.text.push_str("}\n");
        Ok(())
    }

    pub(super) fn finish(self) -> String {
        self.text
    }
}
