//! The two documents rendered from the manifest and the resolved graph.
//!
//! Both are generated. The gate rejects a checked-in copy that differs from
//! what these functions produce, so neither can drift from the manifests.

use std::collections::BTreeMap;

use super::*;

/// Records in package order, which is the order both documents render in.
fn ordered(records: &[CrateRecord]) -> Vec<&CrateRecord> {
    let mut ordered: Vec<&CrateRecord> = records.iter().collect();
    ordered.sort_by(|left, right| left.package.cmp(&right.package));
    ordered
}

/// Layers by rank, then by name, which is how both documents order them.
fn ranked(layers: &[LayerRecord]) -> Vec<&LayerRecord> {
    let mut ranked: Vec<&LayerRecord> = layers.iter().collect();
    ranked.sort_by(|left, right| {
        left.rank
            .cmp(&right.rank)
            .then_with(|| left.name.cmp(&right.name))
    });
    ranked
}

/// Every production edge, source first, as one flat sorted list.
fn production_edges<'a>(state: &'a WorkspaceState) -> Vec<(&'a str, &'a str, &'a DependencyUse)> {
    let mut edges = Vec::new();
    for (package, destinations) in &state.dependencies {
        for (destination, use_) in destinations {
            if use_.is_production() {
                edges.push((package.as_str(), destination.as_str(), use_));
            }
        }
    }
    edges
}

/// The seam a destination row names, or an error when it has no row.
fn seam_of<'a>(
    records: &BTreeMap<&str, &'a CrateRecord>,
    package: &str,
) -> Result<&'a str, GateError> {
    records
        .get(package)
        .map(|record| record.seam.as_str())
        .ok_or_else(|| {
            GateError::new(
                format!("`{package}` is named as a dependency and carries no manifest row"),
                "declare the crate in docs/CRATE_OWNERSHIP.toml before rendering the graph; a node with no row has no place in the document",
            )
        })
}

/// The dependency graph document.
///
/// Every edge here comes from cargo. The document is a rendering of the graph
/// the build resolves, annotated with the layer and seam each edge crosses, so
/// it cannot disagree with the manifests: `--write` rewrites it and the gate
/// rejects a checked-in copy that differs.
pub fn render_graph(
    records: &[CrateRecord],
    layers: &[LayerRecord],
    state: &WorkspaceState,
) -> Result<String, GateError> {
    let ordered = ordered(records);
    let by_package: BTreeMap<&str, &CrateRecord> = ordered
        .iter()
        .map(|record| (record.package.as_str(), *record))
        .collect();
    let ids: BTreeMap<&str, String> = ordered
        .iter()
        .enumerate()
        .map(|(index, record)| (record.package.as_str(), format!("C{index}")))
        .collect();
    let node = |package: &str| -> Result<String, GateError> {
        ids.get(package).cloned().ok_or_else(|| {
            GateError::new(
                format!("`{package}` is named as a dependency and carries no manifest row"),
                "declare the crate in docs/CRATE_OWNERSHIP.toml before rendering the graph; a node with no row has no place in the document",
            )
        })
    };
    let mut lines = vec![
        "# Vyre Crate Graph".to_string(),
        String::new(),
        format!("This file is generated by `{WRITE_COMMAND}` from"),
        "the workspace manifests and `docs/CRATE_OWNERSHIP.toml`. Edit those authorities"
            .to_string(),
        "together, then regenerate this file.".to_string(),
        String::new(),
        "## Layer ranks".to_string(),
        String::new(),
        "A production dependency is legal only when the consumer's layer outranks the".to_string(),
        "dependency's layer and the dependency's layer admits the consumer's. Two layers"
            .to_string(),
        "share a rank when neither depends on the other. Every layer names the closed set"
            .to_string(),
        "of consumer layers admitted to it, its own name included when its members reach"
            .to_string(),
        "each other; a layer that admits none states `None`.".to_string(),
        String::new(),
        "| Rank | Layer | Admitted consumer layers | Purpose |".to_string(),
        "| --- | --- | --- | --- |".to_string(),
    ];
    for layer in ranked(layers) {
        lines.push(format!(
            "| `{}` | `{}` | {} | {} |",
            layer.rank,
            layer.name,
            format_list(&layer.consumed_by),
            layer.purpose
        ));
    }
    let edges = production_edges(state);
    lines.extend([
        String::new(),
        "## Workspace dependency graph".to_string(),
        String::new(),
        format!(
            "The workspace contains {} crates and {} internal production edges, resolved",
            ordered.len(),
            edges.len()
        ),
        "under the union of every feature. An arrow points from a crate to an internal".to_string(),
        "normal or build dependency. Development dependencies are excluded.".to_string(),
        String::new(),
        "```mermaid".to_string(),
        "graph TD".to_string(),
    ]);
    for record in &ordered {
        lines.push(format!(
            "  {}[\"{}\"]",
            node(&record.package)?,
            record.package
        ));
    }
    for (source, destination, _) in &edges {
        lines.push(format!("  {} --> {}", node(source)?, node(destination)?));
    }
    lines.extend([
        "```".to_string(),
        String::new(),
        "## Resolved production edges".to_string(),
        String::new(),
        "| Consumer | Dependency | Seam crossed | Kinds | Conditions | Destination features | Optional | Default features | Activated by |".to_string(),
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |".to_string(),
    ]);
    for (source, destination, use_) in &edges {
        lines.push(format!(
            "| `{source}` | `{destination}` | `{}` | {} | {} | {} | `{}` | `{}` | {} |",
            seam_of(&by_package, destination)?,
            format_list(&use_.kinds),
            format_list(&use_.conditions),
            format_list(&use_.features),
            use_.optional,
            use_.default_features,
            format_list(&use_.activating_features)
        ));
    }
    lines.extend([
        String::new(),
        "## Changing a dependency".to_string(),
        String::new(),
        "Change the Cargo manifest. The architecture manifest needs an edit only when the"
            .to_string(),
        "edge crosses a seam the destination's layer does not admit, when the curated".to_string(),
        "surface starts carrying a new seam, or when a member is added or moved.".to_string(),
        String::new(),
    ]);
    Ok(lines.join("\n"))
}

/// The per-crate ownership document.
pub fn render_ownership(
    records: &[CrateRecord],
    layers: &[LayerRecord],
    state: &WorkspaceState,
) -> Result<String, GateError> {
    let ordered = ordered(records);
    let by_package: BTreeMap<&str, &CrateRecord> = ordered
        .iter()
        .map(|record| (record.package.as_str(), *record))
        .collect();
    let rank: BTreeMap<&str, i64> = layers
        .iter()
        .map(|layer| (layer.name.as_str(), layer.rank))
        .collect();
    let mut lines = vec![
        "# Vyre Crate Ownership".to_string(),
        String::new(),
        format!("This file is generated by `{WRITE_COMMAND}` from"),
        "`docs/CRATE_OWNERSHIP.toml` and the workspace manifests.".to_string(),
        String::new(),
        "## Boundary rule".to_string(),
        String::new(),
        "Each workspace crate owns one concern and exposes one named seam. Every internal"
            .to_string(),
        "production dependency crosses the destination's seam, and the interface stated"
            .to_string(),
        "on that destination's row is what crossing it provides, for every consumer.".to_string(),
        String::new(),
        "## Per-crate ownership".to_string(),
        String::new(),
    ];
    for record in &ordered {
        let empty = BTreeMap::new();
        let outbound = state.dependencies.get(&record.package).unwrap_or(&empty);
        let mut inbound: Vec<(&str, &DependencyUse)> = Vec::new();
        for (source, destinations) in &state.dependencies {
            if let Some(use_) = destinations.get(&record.package) {
                if use_.is_production() {
                    inbound.push((source.as_str(), use_));
                }
            }
        }
        lines.extend([
            format!("### `{}`", record.package),
            String::new(),
            record.responsibility.clone(),
            String::new(),
            format!("- Path: `{}`", record.path),
            format!(
                "- Layer: `{}` (rank {})",
                record.layer,
                rank.get(record.layer.as_str())
                    .map_or_else(|| "unranked".to_string(), i64::to_string)
            ),
            format!("- Publication class: `{}`", record.publication_class),
            format!("- Seam: `{}`", record.seam),
            format!("- Interface: {}", record.interface),
            format!(
                "- Carried by the curated surface: `{}`",
                record.facade_exported
            ),
            format!("- Consumed by {} production edge(s)", inbound.len()),
            String::new(),
        ]);
        let production: Vec<(&String, &DependencyUse)> = outbound
            .iter()
            .filter(|(_, use_)| use_.is_production())
            .collect();
        if production.is_empty() {
            continue;
        }
        lines.extend([
            "| Dependency | Seam crossed | Interface | Activated by |".to_string(),
            "| --- | --- | --- | --- |".to_string(),
        ]);
        for (destination, use_) in production {
            let target = by_package.get(destination.as_str()).ok_or_else(|| {
                GateError::new(
                    format!("`{destination}` is named as a dependency and carries no manifest row"),
                    "declare the crate in docs/CRATE_OWNERSHIP.toml before rendering the document",
                )
            })?;
            lines.push(format!(
                "| `{destination}` | `{}` | {} | {} |",
                target.seam,
                target.interface,
                format_list(&use_.activating_features)
            ));
        }
        lines.push(String::new());
    }
    lines.extend([
        "## Changing a boundary".to_string(),
        String::new(),
        "1. Change the Cargo manifest.".to_string(),
        "2. Change `docs/CRATE_OWNERSHIP.toml` when the member set, a layer, a seam, a".to_string(),
        "   publication class or the curated surface changes.".to_string(),
        format!("3. Run `{WRITE_COMMAND}`."),
        "4. Add a public import migration test when the curated surface changes.".to_string(),
        String::new(),
    ]);
    Ok(lines.join("\n"))
}
