//! GPU-IR vs CPU-ref parity for `math::bigint_add_carry`, the load-and-half-add
//! primitive of the parallel-prefix bigint carry resolver.
//!
//! One lane per limb emits `sum_partial[i] = (a[i] + b[i]) mod 2^32` and
//! `carry_partial[i] = (sum < a[i]) ? 1 : 0` (unsigned-overflow detect). It is a
//! single-round, per-lane op, so `reference_eval` models it exactly. Every
//! shipped test drives `bigint_add_carry_cpu` or checks Program shape; the actual
//! IR (the `sum < a` overflow compare + the select-to-{0,1}) was never executed.
//! A wrong overflow predicate (e.g. `sum < b` vs `sum < a` differ only when the
//! carry is generated by the operand order), a swapped output binding, or a
//! dropped `i < limb_count` bound all diverge here. The test also verifies the
//! split (sum, carry) form composes back into the true multi-limb sum via
//! `resolve_carry_chain_cpu`, so a self-consistent-but-wrong oracle+IR pair
//! cannot both hide.
#![forbid(unsafe_code)]
#![cfg(all(feature = "math", feature = "cpu-parity"))]

use proptest::prelude::*;
use vyre_primitives::math::bigint_add_carry::{
    bigint_add_carry, bigint_add_carry_cpu, resolve_carry_chain_cpu,
};
use vyre_primitives::wire::{decode_u32_le_bytes_all as unpack, pack_u32_slice as pack};
use vyre_reference::value::Value;

/// Drive the real IR and return `(sum_partial, carry_partial)`. Buffer binding
/// order: a(0), b(1), sum_partial(2, RW), carry_partial(3, RW). reference_eval
/// returns the two ReadWrite buffers in binding order.
fn gpu_add_carry(a: &[u32], b: &[u32]) -> (Vec<u32>, Vec<u32>) {
    let program = bigint_add_carry(a.len() as u32);
    let outputs = vyre_reference::reference_eval(
        &program,
        &[
            Value::from(pack(a)),
            Value::from(pack(b)),
            Value::from(pack(&vec![0u32; a.len()])),
            Value::from(pack(&vec![0u32; a.len()])),
        ],
    )
    .expect("bigint_add_carry reference evaluation must succeed");
    (
        unpack(&outputs[0].to_bytes()),
        unpack(&outputs[1].to_bytes()),
    )
}

proptest! {
    #![proptest_config(ProptestConfig::with_cases(2000))]

    #[test]
    fn ir_matches_cpu_ref_over_random_limbs(
        // Values biased toward the overflow boundary so carries fire often:
        // half fully-random, half near u32::MAX.
        limbs in proptest::collection::vec(
            (any::<u32>(), prop_oneof![any::<u32>(), (u32::MAX - 4..=u32::MAX)]),
            1..600,
        )
    ) {
        let a: Vec<u32> = limbs.iter().map(|&(x, _)| x).collect();
        let b: Vec<u32> = limbs.iter().map(|&(_, y)| y).collect();
        let (exp_sum, exp_carry) = bigint_add_carry_cpu(&a, &b).expect("equal lengths");
        let (got_sum, got_carry) = gpu_add_carry(&a, &b);
        prop_assert_eq!(&got_sum, &exp_sum, "sum_partial IR diverged from cpu_ref");
        prop_assert_eq!(&got_carry, &exp_carry, "carry_partial IR diverged from cpu_ref");

        // Independent cross-check: the IR's split form must resolve to the same
        // full multi-limb sum the CPU oracle's split form does.
        let (ir_full, ir_cout) = resolve_carry_chain_cpu(&got_sum, &got_carry).expect("valid split");
        let (ref_full, ref_cout) = resolve_carry_chain_cpu(&exp_sum, &exp_carry).expect("valid split");
        prop_assert_eq!(ir_full, ref_full, "resolved full sum diverged");
        prop_assert_eq!(ir_cout, ref_cout, "resolved final carry-out diverged");
    }
}

/// Deterministic anchors: the exact overflow boundary, all-max ripple, no-carry
/// case, and a length crossing the 256-lane block seam.
#[test]
fn ir_matches_cpu_ref_on_boundary_limbs() {
    // Per-limb overflow boundary: MAX + 1 wraps to 0 with carry 1; MAX + 0 does
    // not carry; 1 + MAX carries.
    let a = vec![u32::MAX, u32::MAX, 1, 0];
    let b = vec![1u32, 0, u32::MAX, 0];
    let (exp_sum, exp_carry) = bigint_add_carry_cpu(&a, &b).unwrap();
    assert_eq!(exp_sum, vec![0, u32::MAX, 0, 0], "cpu_ref sum boundary");
    assert_eq!(exp_carry, vec![1, 0, 1, 0], "cpu_ref carry boundary");
    let (got_sum, got_carry) = gpu_add_carry(&a, &b);
    assert_eq!(
        got_sum, exp_sum,
        "IR sum must match at the overflow boundary"
    );
    assert_eq!(
        got_carry, exp_carry,
        "IR carry must match at the overflow boundary"
    );

    // 513 limbs of MAX + 1: every lane wraps to 0 and carries. Crosses the
    // 256-lane workgroup seam twice, so a dropped tail block would leave zeros
    // in the carry buffer's high lanes.
    let n = 513usize;
    let a = vec![u32::MAX; n];
    let b = vec![1u32; n];
    let (exp_sum, exp_carry) = bigint_add_carry_cpu(&a, &b).unwrap();
    let (got_sum, got_carry) = gpu_add_carry(&a, &b);
    assert_eq!(got_sum, exp_sum, "block-seam sum must match");
    assert_eq!(
        got_carry, exp_carry,
        "block-seam carry must match (all lanes carry)"
    );
    assert_eq!(got_carry, vec![1u32; n], "every MAX+1 lane carries");
}
