//! Generated catalog of machine-readable codes this crate emits.
//!
//! Two families live here. [`ErrorCode`] classifies a backend dispatch
//! failure and carries a stable u32 a consumer can filter on without parsing
//! message text. Diagnostic codes are the string ids attached to warnings the
//! decoder surfaces. Both are rendered from the definitions that emit them, so
//! the catalog cannot drift from the binary: the only way to change a row is to
//! change the code that produces it.

use super::ErrorCode;
use crate::registry::migration::DEPRECATED_OP_CODE;

/// String-coded diagnostics this crate emits, with the invariant each one
/// reports. Rendered into the catalog beside the integer codes.
const DIAGNOSTIC_CODES: &[(&str, &str)] = &[(
    DEPRECATED_OP_CODE,
    "A resolved op is marked deprecated in the migration registry; the \
     diagnostic carries the op location and the migration note as its \
     suggested fix.",
)];

/// Render the catalog as TOML.
///
/// The committed copy at `docs/generated/driver-error-codes.toml` is compared
/// against this on every test run.
#[must_use]
pub fn render_catalog_toml() -> String {
    let mut out = String::with_capacity(4096);
    out.push_str("# Generated by vyre-driver. Do not edit by hand.\n");
    out.push_str("# Regenerate: VYRE_WRITE_ERROR_CATALOG=1 ./cargo_full test -p vyre-driver\n");
    out.push_str("#\n");
    out.push_str("# Integer ids are append-only: an existing assignment is never reused or\n");
    out.push_str("# renumbered, because consumers persist them in telemetry and alert rules.\n");

    for code in ErrorCode::ALL {
        out.push_str("\n[[backend_error]]\n");
        out.push_str(&format!("variant = {:?}\n", format!("{code:?}")));
        out.push_str(&format!("id = {}\n", code.stable_id()));
        out.push_str(&format!("summary = {:?}\n", code.summary()));
    }

    for (code, summary) in DIAGNOSTIC_CODES {
        out.push_str("\n[[diagnostic]]\n");
        out.push_str(&format!("code = {code:?}\n"));
        out.push_str(&format!("summary = {summary:?}\n"));
    }

    out
}
